// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "a9c56b73-af40-5199-a20f-7ccf0b2a216a",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "accountCategory",
  label: "Account Category",
  icon: "IconBuildingStore",
  isNullable: true,
  options: [
    {
      id: "45c26cbf-aa38-5265-bd54-9aa99ab00647",
      color: "green",
      label: "Retail Shop",
      value: "RETAIL_SHOP",
      position: 0
    },
    {
      id: "7cc759da-6617-59d1-9f28-46690b6b15e6",
      color: "turquoise",
      label: "Hotel",
      value: "HOTEL",
      position: 1
    },
    {
      id: "8a8db231-a347-517a-857e-db1714afd28c",
      color: "sky",
      label: "Supermarket",
      value: "SUPERMARKET",
      position: 2
    },
    {
      id: "c8b3c0f6-863b-59b5-bd69-4f1b1f41f70d",
      color: "blue",
      label: "Weddings Events",
      value: "WEDDINGS_EVENTS",
      position: 3
    },
    {
      id: "73730d05-9cac-50cd-8cda-2a774d426c63",
      color: "purple",
      label: "Micro Buyer",
      value: "MICRO_BUYER",
      position: 4
    },
    {
      id: "e80eef2e-f64a-564e-a991-3ca65b9ca6f5",
      color: "green",
      label: "Online",
      value: "ONLINE",
      position: 5
    },
    {
      id: "386d0bfa-da9a-511c-9c70-cf04b8eb122d",
      color: "red",
      label: "Bulk",
      value: "BULK",
      position: 6
    },
    {
      id: "f5d11e38-4ac7-52c4-a5b4-4f10f80f533b",
      color: "orange",
      label: "Fully Serviced",
      value: "FULLY_SERVICED",
      position: 7
    }
  ]
});
