// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "ab2fd4ee-e098-58ab-9e2d-b37674758415",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "accountStatus",
  label: "Account Status",
  icon: "IconHeartbeat",
  isNullable: true,
  options: [
    {
      id: "93450950-911c-51f1-bda3-406f966936d9",
      color: "green",
      label: "Never Ordered",
      value: "NEVER_ORDERED",
      position: 0
    },
    {
      id: "98a545f9-59fc-5320-a3e3-3a99d78059a0",
      color: "green",
      label: "Active",
      value: "ACTIVE",
      position: 1
    },
    {
      id: "4fbf742a-66d6-58e6-847b-a1c40e150d1a",
      color: "sky",
      label: "Inactive",
      value: "INACTIVE",
      position: 2
    },
    {
      id: "5ec08a0b-f9a1-57c1-b854-0b390d9458dc",
      color: "red",
      label: "Blocked",
      value: "BLOCKED",
      position: 3
    },
    {
      id: "06ffa4b1-fd55-59bc-b161-23c4f79912ad",
      color: "gray",
      label: "Churned",
      value: "CHURNED",
      position: 4
    },
    {
      id: "d48a7909-15df-552c-acc2-6985e2a9bce9",
      color: "pink",
      label: "Cold List",
      value: "COLD_LIST",
      position: 5
    },
    {
      id: "3e9104cb-b3c6-50f9-a6c9-a0382420ff7d",
      color: "red",
      label: "Closed",
      value: "CLOSED",
      position: 6
    }
  ]
});
