// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "ab2910a1-3e80-56ce-8732-193550e1e30a",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "acquisitionSource",
  label: "Acquisition Source",
  icon: "IconTargetArrow",
  isNullable: true,
  options: [
    {
      id: "cc884160-6749-5b93-a53c-9973c1853778",
      color: "green",
      label: "Sm Ads",
      value: "SM_ADS",
      position: 0
    },
    {
      id: "049a84e7-d4df-58f9-bb67-320bd8d9e148",
      color: "turquoise",
      label: "Sm Dm",
      value: "SM_DM",
      position: 1
    },
    {
      id: "433cd575-186c-5b45-8ca0-085601354d6b",
      color: "sky",
      label: "Sm Message",
      value: "SM_MESSAGE",
      position: 2
    },
    {
      id: "29dd831d-5368-580b-af92-a28ab297f78a",
      color: "blue",
      label: "Mp Chat",
      value: "MP_CHAT",
      position: 3
    },
    {
      id: "62096cf8-140d-5efb-8374-2bfaa0af1a59",
      color: "purple",
      label: "Mp Selfreg",
      value: "MP_SELFREG",
      position: 4
    },
    {
      id: "1cd44d60-1382-54fe-8ac2-9ae237c92c8e",
      color: "pink",
      label: "Mp Care",
      value: "MP_CARE",
      position: 5
    },
    {
      id: "d0e7825b-1c04-5aad-bf1c-c9b22baa9d17",
      color: "red",
      label: "Ref Am",
      value: "REF_AM",
      position: 6
    },
    {
      id: "d8908eca-635e-56b9-b3c2-e0c108445a39",
      color: "orange",
      label: "Ref Partner",
      value: "REF_PARTNER",
      position: 7
    },
    {
      id: "6be62993-8fd0-58f0-929e-d388d70ca269",
      color: "yellow",
      label: "Ref Account",
      value: "REF_ACCOUNT",
      position: 8
    },
    {
      id: "b6d60a25-234a-58d5-8e85-63e867254128",
      color: "gray",
      label: "Scrape Maps",
      value: "SCRAPE_MAPS",
      position: 9
    },
    {
      id: "8ebee7ca-cd56-53ef-8f65-88b5360a84c0",
      color: "green",
      label: "Scrape Bleems",
      value: "SCRAPE_BLEEMS",
      position: 10
    },
    {
      id: "0e069750-2b65-5efc-b0b7-74d3bdbf3d81",
      color: "turquoise",
      label: "Scrape Flooww",
      value: "SCRAPE_FLOOWW",
      position: 11
    },
    {
      id: "823c606f-64ee-563c-a74f-0781b8d992b1",
      color: "sky",
      label: "Scrape Other",
      value: "SCRAPE_OTHER",
      position: 12
    },
    {
      id: "77144e2a-121b-5c0b-a61d-91c6830b9d45",
      color: "blue",
      label: "Walk In",
      value: "WALK_IN",
      position: 13
    },
    {
      id: "d40793db-f124-5444-931a-98f692678252",
      color: "purple",
      label: "Event",
      value: "EVENT",
      position: 14
    },
    {
      id: "51eaa304-593f-58b4-9048-1ac95b440ed7",
      color: "pink",
      label: "Outbound",
      value: "OUTBOUND",
      position: 15
    },
    {
      id: "28d4c3df-238e-5749-b652-d1b71fb9003e",
      color: "red",
      label: "Inbound Call",
      value: "INBOUND_CALL",
      position: 16
    },
    {
      id: "39d03d7f-2f17-5a69-ab82-47d64e1de499",
      color: "orange",
      label: "Website",
      value: "WEBSITE",
      position: 17
    },
    {
      id: "82572ea2-06eb-584f-a615-525272458023",
      color: "yellow",
      label: "Other",
      value: "OTHER",
      position: 18
    },
    {
      id: "c8b10165-3504-53e5-89d6-06684f8f9491",
      color: "gray",
      label: "Legacy Migration",
      value: "LEGACY_MIGRATION",
      position: 19
    }
  ]
});
