// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "4ac4a2f1-fe80-59e4-81af-21318c239901",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.CURRENCY,
  name: "agingReceivable",
  label: "Receivable Aging >90d",
  description: "(sync)",
  icon: "IconHourglass",
  isNullable: true
});
