// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "dc14a0b9-2add-58e8-a833-a5e5ee205914",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.TEXT,
  name: "arabicName",
  label: "Arabic Name",
  icon: "IconLanguage",
  isNullable: true
});
