// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "95a4ea1e-9de5-4ab3-be1c-328bcb4dc9f9",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.SELECT,
  name: "billingCurrency",
  label: "Currency",
  description: "Billing currency used for customer registration",
  icon: "IconCoins",
  isNullable: true,
  options: [
    {
      id: "49670076-b9cb-4249-98b5-fc7dd0f80b59",
      color: "green",
      label: "AED — UAE dirham",
      value: "AED",
      position: 0
    },
    {
      id: "38fe8ea1-2fc0-4df2-8300-a76e39baf5ac",
      color: "turquoise",
      label: "AFN — Afghan afghani",
      value: "AFN",
      position: 1
    },
    {
      id: "f1d2f675-5652-46b6-8393-dffc4323697f",
      color: "sky",
      label: "ALL — Albanian lek",
      value: "ALL",
      position: 2
    },
    {
      id: "d007d437-3ee5-49d2-8dc3-29c8f0dab8f4",
      color: "blue",
      label: "AMD — Armenian dram",
      value: "AMD",
      position: 3
    },
    {
      id: "18a6de84-0ed1-40e8-8b61-37b053d7ffac",
      color: "purple",
      label: "ANG — Netherlands Antillean guilder",
      value: "ANG",
      position: 4
    },
    {
      id: "51c79196-03a7-4eed-aae9-aad84e365b8d",
      color: "pink",
      label: "AOA — Angolan kwanza",
      value: "AOA",
      position: 5
    },
    {
      id: "e1b25528-6b32-4f2f-a4de-7c553add8895",
      color: "red",
      label: "ARS — Argentine peso",
      value: "ARS",
      position: 6
    },
    {
      id: "98571b54-a1db-4063-b48e-b158f26831b9",
      color: "orange",
      label: "AUD — Australian dollar",
      value: "AUD",
      position: 7
    },
    {
      id: "b37e57bc-423a-4429-8d2c-77f2f866c5d4",
      color: "yellow",
      label: "AWG — Aruban florin",
      value: "AWG",
      position: 8
    },
    {
      id: "2a38c799-ff7c-446d-87d7-c601407fb474",
      color: "gray",
      label: "AZN — Azerbaijani manat",
      value: "AZN",
      position: 9
    },
    {
      id: "df1603f7-c622-48ec-abf9-17f8d8f019c9",
      color: "green",
      label: "BAM — Bosnia and Herzegovina mark",
      value: "BAM",
      position: 10
    },
    {
      id: "6633f0b2-c518-4ed7-a2c0-b0c611ae71a0",
      color: "turquoise",
      label: "BBD — Barbados dollar",
      value: "BBD",
      position: 11
    },
    {
      id: "a17a0ce0-4d1d-4430-bf09-725f6a537db8",
      color: "sky",
      label: "BDT — Bangladeshi taka",
      value: "BDT",
      position: 12
    },
    {
      id: "161a1ce1-5cb6-4722-8795-9d94730c602a",
      color: "blue",
      label: "BGN — Bulgarian lev",
      value: "BGN",
      position: 13
    },
    {
      id: "13310276-024e-4a64-9e3c-92e24176de88",
      color: "purple",
      label: "BHD — Bahraini dinar",
      value: "BHD",
      position: 14
    },
    {
      id: "05eae410-44f2-4c62-8c07-9768cfe99265",
      color: "pink",
      label: "BIF — Burundian franc",
      value: "BIF",
      position: 15
    },
    {
      id: "0558b0cd-1473-488d-8d4c-d55751296b20",
      color: "red",
      label: "BMD — Bermudian dollar",
      value: "BMD",
      position: 16
    },
    {
      id: "ec34740c-7fd0-47ec-97fe-2dd5e0fc15ed",
      color: "orange",
      label: "BND — Brunei dollar",
      value: "BND",
      position: 17
    },
    {
      id: "18d28d79-e938-42d2-99c4-24aa5a1dcd4c",
      color: "yellow",
      label: "BOB — Boliviano",
      value: "BOB",
      position: 18
    },
    {
      id: "46133b7d-3528-47f9-a4b9-cda905b73943",
      color: "gray",
      label: "BRL — Brazilian real",
      value: "BRL",
      position: 19
    },
    {
      id: "4aac5164-bb47-47d6-b8e7-5db3d77d9f50",
      color: "green",
      label: "BSD — Bahamian dollar",
      value: "BSD",
      position: 20
    },
    {
      id: "323f2001-498d-4a8f-8a1e-60cc1e195cf9",
      color: "turquoise",
      label: "BTN — Bhutanese ngultrum",
      value: "BTN",
      position: 21
    },
    {
      id: "75d3651c-3404-4ab0-959c-19da82b78447",
      color: "sky",
      label: "BWP — Botswana pula",
      value: "BWP",
      position: 22
    },
    {
      id: "64266323-d8d3-4031-89e7-6c1fca8bb2d0",
      color: "blue",
      label: "BYN — Belarusian ruble",
      value: "BYN",
      position: 23
    },
    {
      id: "469fc929-4959-47e4-95f7-546745576da3",
      color: "purple",
      label: "BZD — Belize dollar",
      value: "BZD",
      position: 24
    },
    {
      id: "b665561a-fc0e-4179-a3d5-bdb6c0d6c9d9",
      color: "pink",
      label: "CAD — Canadian dollar",
      value: "CAD",
      position: 25
    },
    {
      id: "71163c16-529e-400b-b68c-d6e103b303f1",
      color: "red",
      label: "CDF — Congolese franc",
      value: "CDF",
      position: 26
    },
    {
      id: "e9ddc6d1-69c7-436d-be70-64eb0eaa4924",
      color: "orange",
      label: "CHF — Swiss franc",
      value: "CHF",
      position: 27
    },
    {
      id: "450ff71d-0e61-4a00-99e2-fc7aa4278e50",
      color: "yellow",
      label: "CLP — Chilean peso",
      value: "CLP",
      position: 28
    },
    {
      id: "eee03ca2-431c-46a1-a80e-0761f3fc4c4b",
      color: "gray",
      label: "CLF — Unidad de Fomento",
      value: "CLF",
      position: 29
    },
    {
      id: "19df6ca6-8f92-4283-8bc7-821fffa1c2a3",
      color: "green",
      label: "CNY — Chinese yuan",
      value: "CNY",
      position: 30
    },
    {
      id: "c8f75deb-cf6f-4130-b541-7215e4bc6c72",
      color: "turquoise",
      label: "COP — Colombian peso",
      value: "COP",
      position: 31
    },
    {
      id: "aa87777a-e32b-4284-998b-95e95e4ed0d7",
      color: "sky",
      label: "CRC — Costa Rican colon",
      value: "CRC",
      position: 32
    },
    {
      id: "93e22199-ae12-4120-b253-4894dec1803a",
      color: "blue",
      label: "CUP — Cuban peso",
      value: "CUP",
      position: 33
    },
    {
      id: "08f6ec7c-6294-4e6b-8334-7f9d0e500f77",
      color: "purple",
      label: "CVE — Cape Verdean escudo",
      value: "CVE",
      position: 34
    },
    {
      id: "68e4a535-cd6f-44fc-a36b-42e8f0d00e7e",
      color: "pink",
      label: "CZK — Czech koruna",
      value: "CZK",
      position: 35
    },
    {
      id: "751ca104-0d90-4227-aa26-1c4fea5c830f",
      color: "red",
      label: "DJF — Djiboutian franc",
      value: "DJF",
      position: 36
    },
    {
      id: "6017a3e1-6ac5-4880-9b57-1b29e6353ce7",
      color: "orange",
      label: "DKK — Danish krone",
      value: "DKK",
      position: 37
    },
    {
      id: "27e307d8-fdd8-4409-b251-9aad11909d4a",
      color: "yellow",
      label: "DOP — Dominican peso",
      value: "DOP",
      position: 38
    },
    {
      id: "28b05e43-51f3-4b3c-967e-282abfb4a23b",
      color: "gray",
      label: "DZD — Algerian Dinar",
      value: "DZD",
      position: 39
    },
    {
      id: "abca06d4-48c1-4ef6-8ede-a1738a331159",
      color: "green",
      label: "EGP — Egyptian pound",
      value: "EGP",
      position: 40
    },
    {
      id: "e18c3615-77b5-457a-8ea1-00b2d114e668",
      color: "turquoise",
      label: "ERN — Eritrean nakfa",
      value: "ERN",
      position: 41
    },
    {
      id: "2eafea93-bec6-4e9a-a0d3-f7a338d1a9a0",
      color: "sky",
      label: "ETB — Ethiopian birr",
      value: "ETB",
      position: 42
    },
    {
      id: "9c87eee5-f511-4cfd-97c8-0686cdaedcf5",
      color: "blue",
      label: "EUR — Euro",
      value: "EUR",
      position: 43
    },
    {
      id: "8c06d1c2-6862-413d-a9da-b69209fbce3e",
      color: "purple",
      label: "FJD — Fiji dollar",
      value: "FJD",
      position: 44
    },
    {
      id: "bca7546a-eefb-4081-81e2-b35c159b21f7",
      color: "pink",
      label: "FKP — Falkland Islands pound",
      value: "FKP",
      position: 45
    },
    {
      id: "eb52b0bc-f2b5-4f81-8684-d0ae24a6e782",
      color: "red",
      label: "GBP — British pound",
      value: "GBP",
      position: 46
    },
    {
      id: "fffee3ae-7faa-40f0-abdf-d0b8c38d2d11",
      color: "orange",
      label: "GEL — Georgian lari",
      value: "GEL",
      position: 47
    },
    {
      id: "74516ab7-8ce6-475a-91ca-b3ef7b6011ee",
      color: "yellow",
      label: "GHS — Ghanaian cedi",
      value: "GHS",
      position: 48
    },
    {
      id: "c40bdc17-52e3-4d56-909b-382b0bf38167",
      color: "gray",
      label: "GIP — Gibraltar pound",
      value: "GIP",
      position: 49
    },
    {
      id: "6bf1d751-142b-4506-8553-c89e4f1a697a",
      color: "green",
      label: "GMD — Gambian dalasi",
      value: "GMD",
      position: 50
    },
    {
      id: "9644fafa-2527-42be-80f2-00f10e61b032",
      color: "turquoise",
      label: "GNF — Guinean franc",
      value: "GNF",
      position: 51
    },
    {
      id: "cb4f70c3-514b-42eb-af66-5d1eeadee926",
      color: "sky",
      label: "GTQ — Guatemalan quetzal",
      value: "GTQ",
      position: 52
    },
    {
      id: "b1cecbcf-6bcd-4ce2-81a7-3828821b1eb7",
      color: "blue",
      label: "GYD — Guyanese dollar",
      value: "GYD",
      position: 53
    },
    {
      id: "20fd0a0e-ce3f-4462-9442-ab51360e58d3",
      color: "purple",
      label: "HKD — Hong Kong dollar",
      value: "HKD",
      position: 54
    },
    {
      id: "af7e54c1-89fc-4c0b-8fcd-cd34e92b3149",
      color: "pink",
      label: "HNL — Honduran lempira",
      value: "HNL",
      position: 55
    },
    {
      id: "93d7ce9d-b693-4f14-a22a-07eac9c861dd",
      color: "red",
      label: "HTG — Haitian gourde",
      value: "HTG",
      position: 56
    },
    {
      id: "b55edb1a-3136-4bdc-9d6f-132d0a0b392d",
      color: "orange",
      label: "HUF — Hungarian forint",
      value: "HUF",
      position: 57
    },
    {
      id: "12adf1ab-098e-4f90-9faf-7ebe9c63544d",
      color: "yellow",
      label: "IDR — Indonesian rupiah",
      value: "IDR",
      position: 58
    },
    {
      id: "b250d9b4-3e3e-47e8-a4b2-2ed5dc2c702e",
      color: "gray",
      label: "ILS — Israeli shekel",
      value: "ILS",
      position: 59
    },
    {
      id: "d7292e4d-f70c-465b-915d-2d3875bfc639",
      color: "green",
      label: "INR — Indian rupee",
      value: "INR",
      position: 60
    },
    {
      id: "a3f1b9b2-43cb-4343-85a2-c38167987dfc",
      color: "turquoise",
      label: "IQD — Iraqi dinar",
      value: "IQD",
      position: 61
    },
    {
      id: "37e04482-cbff-405b-bf83-0988bec2a415",
      color: "sky",
      label: "IRR — Iranian rial",
      value: "IRR",
      position: 62
    },
    {
      id: "1ecec726-4fb1-437c-8363-f32b29de669f",
      color: "blue",
      label: "ISK — Icelandic króna",
      value: "ISK",
      position: 63
    },
    {
      id: "51f64da8-a994-47e4-9f83-552ab48f82fe",
      color: "purple",
      label: "JMD — Jamaican dollar",
      value: "JMD",
      position: 64
    },
    {
      id: "b0df9c6c-9f10-4692-a69c-edc4250ce85b",
      color: "pink",
      label: "JOD — Jordanian dinar",
      value: "JOD",
      position: 65
    },
    {
      id: "a30af65d-e72b-458a-8734-5a901bd729ba",
      color: "red",
      label: "JPY — Japanese yen",
      value: "JPY",
      position: 66
    },
    {
      id: "2e2683fc-fb65-4163-abfb-93d7d499294d",
      color: "orange",
      label: "KES — Kenyan shilling",
      value: "KES",
      position: 67
    },
    {
      id: "efab2ed4-6c29-43db-b8a6-b718a501e849",
      color: "yellow",
      label: "KGS — Kyrgyzstani som",
      value: "KGS",
      position: 68
    },
    {
      id: "3dd017eb-36c9-413c-8128-d23ffdc34e85",
      color: "gray",
      label: "KHR — Cambodian riel",
      value: "KHR",
      position: 69
    },
    {
      id: "78949f27-7132-47e2-b9aa-e213a343f2a7",
      color: "green",
      label: "KMF — Comoro franc",
      value: "KMF",
      position: 70
    },
    {
      id: "bf332ec6-ee7e-4cc4-b5b1-e3b1170b5e31",
      color: "turquoise",
      label: "KPW — North Korean won",
      value: "KPW",
      position: 71
    },
    {
      id: "c5d91833-e217-4c81-a2d2-9025d34c2c47",
      color: "sky",
      label: "KRW — South Korean won",
      value: "KRW",
      position: 72
    },
    {
      id: "05a6caf5-4fd2-4ee2-b5a3-4939e5eaf291",
      color: "blue",
      label: "KWD — Kuwaiti dinar",
      value: "KWD",
      position: 73
    },
    {
      id: "ecb7177e-e49a-4032-bd85-82bb8c2b4e09",
      color: "purple",
      label: "KYD — Cayman Islands dollar",
      value: "KYD",
      position: 74
    },
    {
      id: "a8733341-ce49-40f8-a30b-d52e4c827959",
      color: "pink",
      label: "KZT — Kazakhstani tenge",
      value: "KZT",
      position: 75
    },
    {
      id: "0afc7f1d-0750-4703-ad01-50ec2efa29db",
      color: "red",
      label: "LAK — Lao kip",
      value: "LAK",
      position: 76
    },
    {
      id: "4d34a62c-decb-4214-991c-82937dff2b33",
      color: "orange",
      label: "LBP — Lebanese pound",
      value: "LBP",
      position: 77
    },
    {
      id: "a60517f2-b9f6-41b9-8a15-09a7ea52bd6b",
      color: "yellow",
      label: "LKR — Sri Lankan rupee",
      value: "LKR",
      position: 78
    },
    {
      id: "3d01e7b6-ba23-4395-98df-3f90b32a50a0",
      color: "gray",
      label: "LRD — Liberian dollar",
      value: "LRD",
      position: 79
    },
    {
      id: "a4ec8bad-1088-4fc2-acab-555c06878642",
      color: "green",
      label: "LSL — Lesotho loti",
      value: "LSL",
      position: 80
    },
    {
      id: "42a4c798-85a0-4a8d-a210-a8ba8478385e",
      color: "turquoise",
      label: "LYD — Libyan dinar",
      value: "LYD",
      position: 81
    },
    {
      id: "ab0c6242-9d50-414f-87d9-fe39d65b8d4a",
      color: "sky",
      label: "MAD — Moroccan dirham",
      value: "MAD",
      position: 82
    },
    {
      id: "57017424-2a90-4656-8fca-b346b6a40b35",
      color: "blue",
      label: "MDL — Moldovan leu",
      value: "MDL",
      position: 83
    },
    {
      id: "c091d91e-f21a-4797-9d74-a99e2819eb48",
      color: "purple",
      label: "MGA — Malagasy ariary",
      value: "MGA",
      position: 84
    },
    {
      id: "74a92375-ae00-440e-aac3-9afc18d5ba91",
      color: "pink",
      label: "MKD — Macedonian denar",
      value: "MKD",
      position: 85
    },
    {
      id: "5b8c4f52-16a2-4ef4-abf6-1c7d60160295",
      color: "red",
      label: "MMK — Myanmar kyat",
      value: "MMK",
      position: 86
    },
    {
      id: "0cef27e9-5559-42cf-98aa-2bf653acd732",
      color: "orange",
      label: "MNT — Mongolian tögrög",
      value: "MNT",
      position: 87
    },
    {
      id: "3d9f8172-68ea-4fa5-89fa-6e11c6d32711",
      color: "yellow",
      label: "MOP — Macanese pataca",
      value: "MOP",
      position: 88
    },
    {
      id: "6d622dc2-e4e2-4ca4-9d06-e86169bc319f",
      color: "gray",
      label: "MRU — Mauritanian ouguiya",
      value: "MRU",
      position: 89
    },
    {
      id: "334d33b3-1ff3-40ca-bbe2-d1464441cb92",
      color: "green",
      label: "MUR — Mauritian rupee",
      value: "MUR",
      position: 90
    },
    {
      id: "5c8f2522-2fa3-4a1f-8865-e46a9141e468",
      color: "turquoise",
      label: "MVR — Maldivian rufiyaa",
      value: "MVR",
      position: 91
    },
    {
      id: "a02c6623-ccc7-4f86-8495-0cfaddbcdad7",
      color: "sky",
      label: "MWK — Malawian kwacha",
      value: "MWK",
      position: 92
    },
    {
      id: "26ddda89-d63d-4ad9-b08f-805c6f9015c7",
      color: "blue",
      label: "MXN — Mexican peso",
      value: "MXN",
      position: 93
    },
    {
      id: "1210e7ac-a5f2-4d86-8132-44b9ac6679b9",
      color: "purple",
      label: "MYR — Malaysian ringgit",
      value: "MYR",
      position: 94
    },
    {
      id: "dcfd48ea-8adf-4862-b5ad-3cff88da4168",
      color: "pink",
      label: "MZN — Mozambican metical",
      value: "MZN",
      position: 95
    },
    {
      id: "b9314682-0c24-4818-a66a-c1295a69b402",
      color: "red",
      label: "NAD — Namibian dollar",
      value: "NAD",
      position: 96
    },
    {
      id: "631bcafb-5311-419a-a5a0-3e4367a212c0",
      color: "orange",
      label: "NGN — Nigerian naira",
      value: "NGN",
      position: 97
    },
    {
      id: "ecc5567d-3a49-4ef5-8fef-082467304d54",
      color: "yellow",
      label: "NIO — Nicaraguan córdoba",
      value: "NIO",
      position: 98
    },
    {
      id: "31a42ecb-31df-4e8a-9e47-a549a5c41afb",
      color: "gray",
      label: "NOK — Norwegian krone",
      value: "NOK",
      position: 99
    },
    {
      id: "1e77159f-5ea7-499e-a6e3-6fa9f7154db5",
      color: "green",
      label: "NPR — Nepalese rupee",
      value: "NPR",
      position: 100
    },
    {
      id: "f924edde-3037-4f8d-8bce-9637b9da963d",
      color: "turquoise",
      label: "NZD — New Zealand dollar",
      value: "NZD",
      position: 101
    },
    {
      id: "5231f898-9063-4121-80f4-46338ed099e3",
      color: "sky",
      label: "OMR — Omani rial",
      value: "OMR",
      position: 102
    },
    {
      id: "4df0739e-c703-4a20-85a5-4d76f4e26de5",
      color: "blue",
      label: "PAB — Panamanian balboa",
      value: "PAB",
      position: 103
    },
    {
      id: "b828e2ac-06e9-4b9d-915d-7fb96cca1b14",
      color: "purple",
      label: "PEN — Peruvian sol",
      value: "PEN",
      position: 104
    },
    {
      id: "699f4ef5-d7a1-45f7-9252-bac9aaa866f3",
      color: "pink",
      label: "PGK — Papua New Guinean kina",
      value: "PGK",
      position: 105
    },
    {
      id: "c63d54b6-4d6a-4ce3-b883-372d5e30b87c",
      color: "red",
      label: "PHP — Philippine peso",
      value: "PHP",
      position: 106
    },
    {
      id: "162105c1-6fb6-4f87-92fe-86c990c0336c",
      color: "orange",
      label: "PKR — Pakistani rupee",
      value: "PKR",
      position: 107
    },
    {
      id: "1a025206-eef9-4567-bcd3-40b34bcdc9f6",
      color: "yellow",
      label: "PLN — Polish złoty",
      value: "PLN",
      position: 108
    },
    {
      id: "82390306-2243-474d-bfd6-33452cf153e4",
      color: "gray",
      label: "PYG — Paraguayan guaraní",
      value: "PYG",
      position: 109
    },
    {
      id: "9a3bce97-b90e-45a2-a5eb-2709a3bbff55",
      color: "green",
      label: "QAR — Qatari riyal",
      value: "QAR",
      position: 110
    },
    {
      id: "ef8e8034-823d-48a4-aa08-6c04061da769",
      color: "turquoise",
      label: "RON — Romanian leu",
      value: "RON",
      position: 111
    },
    {
      id: "d6613b62-897e-4751-a674-29d19380726e",
      color: "sky",
      label: "RSD — Serbian dinar",
      value: "RSD",
      position: 112
    },
    {
      id: "a257880a-1697-4a6f-a69b-ed40bdad51c7",
      color: "blue",
      label: "RUB — Russian ruble",
      value: "RUB",
      position: 113
    },
    {
      id: "7dd6b78a-bad3-4e8a-99ce-e102573fa741",
      color: "purple",
      label: "RWF — Rwandan franc",
      value: "RWF",
      position: 114
    },
    {
      id: "96e0ea19-0a65-4cf3-b445-efb8e8913d15",
      color: "pink",
      label: "SAR — Saudi riyal",
      value: "SAR",
      position: 115
    },
    {
      id: "a50ced7c-1320-4aba-87c6-57b0c9f23b8e",
      color: "red",
      label: "SBD — Solomon Islands dollar",
      value: "SBD",
      position: 116
    },
    {
      id: "2f652cbe-63c1-4767-a880-d70a97c4598d",
      color: "orange",
      label: "SCR — Seychelles rupee",
      value: "SCR",
      position: 117
    },
    {
      id: "ff9177f9-06bf-452f-b1e9-952babc28fb1",
      color: "yellow",
      label: "SDG — Sudanese pound",
      value: "SDG",
      position: 118
    },
    {
      id: "8d1e4cf4-5508-4bfb-8b18-98b5cae4a734",
      color: "gray",
      label: "SEK — Swedish krona",
      value: "SEK",
      position: 119
    },
    {
      id: "346a07be-06d8-4dad-9a1a-668b43ef570a",
      color: "green",
      label: "SGD — Singapore dollar",
      value: "SGD",
      position: 120
    },
    {
      id: "ef52eeb0-eb81-40bc-a005-5ec4f7899ff1",
      color: "turquoise",
      label: "SHP — Saint Helena pound",
      value: "SHP",
      position: 121
    },
    {
      id: "dec4988d-f371-4c33-a7f7-b95f6536cccc",
      color: "sky",
      label: "SLE — Sierra Leonean leone",
      value: "SLE",
      position: 122
    },
    {
      id: "31114e24-6a49-4aa7-a86b-1f0425d3a6a0",
      color: "blue",
      label: "SOS — Somalian shilling",
      value: "SOS",
      position: 123
    },
    {
      id: "324547cb-fed7-4c86-b80e-d4d256fcdfe5",
      color: "purple",
      label: "SRD — Surinamese dollar",
      value: "SRD",
      position: 124
    },
    {
      id: "54139eb7-5116-48ff-873c-c9abd9e86d48",
      color: "pink",
      label: "SSP — South Sudanese pound",
      value: "SSP",
      position: 125
    },
    {
      id: "ddda3047-da2c-4e80-87ba-e1ac4a4b7314",
      color: "red",
      label: "STN — São Tomé and Príncipe dobra",
      value: "STN",
      position: 126
    },
    {
      id: "89262cb7-04c5-4d7a-8a2c-9095daa1ef80",
      color: "orange",
      label: "SVC — Salvadoran colón",
      value: "SVC",
      position: 127
    },
    {
      id: "c395db4f-3413-432b-981f-c93df62730f3",
      color: "yellow",
      label: "SYP — Syrian pound",
      value: "SYP",
      position: 128
    },
    {
      id: "3c21cb09-b0f1-4236-926e-088b0ef9aa26",
      color: "gray",
      label: "SZL — Swazi lilangeni",
      value: "SZL",
      position: 129
    },
    {
      id: "80f0eee6-8ec2-427d-9bc5-dea9c64df7fa",
      color: "green",
      label: "THB — Thai Baht",
      value: "THB",
      position: 130
    },
    {
      id: "e93b2fa8-7416-49d8-8e0c-2a71276e55ce",
      color: "turquoise",
      label: "TJS — Tajikistani somoni",
      value: "TJS",
      position: 131
    },
    {
      id: "188feec2-bc48-489e-bb66-755854e33a07",
      color: "sky",
      label: "TMT — Turkmenistan manat",
      value: "TMT",
      position: 132
    },
    {
      id: "beecf9ad-7a47-42f3-9795-809b263ad55a",
      color: "blue",
      label: "TND — Tunisian dinar",
      value: "TND",
      position: 133
    },
    {
      id: "3eeaf978-cae8-48c0-9821-6ac6be25be74",
      color: "purple",
      label: "TOP — Tongan paʻanga",
      value: "TOP",
      position: 134
    },
    {
      id: "7e4723b9-a2a0-4f26-8e8e-2dd5b1149554",
      color: "pink",
      label: "TRY — Turkish lira",
      value: "TRY",
      position: 135
    },
    {
      id: "5aa11fae-c82f-4157-bff2-e176d0ca62c3",
      color: "red",
      label: "TTD — Trinidad and Tobago dollar",
      value: "TTD",
      position: 136
    },
    {
      id: "e645aacb-1738-405c-96ea-4bff5caf9578",
      color: "orange",
      label: "TWD — Taiwanese dollar",
      value: "TWD",
      position: 137
    },
    {
      id: "c0c49f4c-8a4c-452b-ab73-32151a48643b",
      color: "yellow",
      label: "TZS — Tanzanian shilling",
      value: "TZS",
      position: 138
    },
    {
      id: "384ad7b3-c438-4c36-b421-ab5946bbe95e",
      color: "gray",
      label: "UAH — Ukrainian hryvnia",
      value: "UAH",
      position: 139
    },
    {
      id: "e3182cdd-e7a1-46c9-86c1-877bdba4641f",
      color: "green",
      label: "UGX — Ugandan shilling",
      value: "UGX",
      position: 140
    },
    {
      id: "2bfa35e1-6c44-4ef7-83f5-ed2b71932cc3",
      color: "turquoise",
      label: "USD — United States dollar",
      value: "USD",
      position: 141
    },
    {
      id: "35723436-1c21-4647-ae5a-e24dfa19d352",
      color: "sky",
      label: "UYU — Uruguayan peso",
      value: "UYU",
      position: 142
    },
    {
      id: "e7d8d9f0-c9c1-4737-accf-3996df2d77cb",
      color: "blue",
      label: "UZS — Uzbekistani sum",
      value: "UZS",
      position: 143
    },
    {
      id: "f6db5bc8-fbab-4a7c-a4d2-20afe4dfb57d",
      color: "purple",
      label: "VES — Venezuelan bolívar",
      value: "VES",
      position: 144
    },
    {
      id: "0c4294cf-bd91-4ffd-8ba0-8a32be35d919",
      color: "pink",
      label: "VND — Vietnamese đồng",
      value: "VND",
      position: 145
    },
    {
      id: "4d5807e2-87b4-49b2-b2ff-24951a5c198b",
      color: "red",
      label: "VUV — Vanuatu vatu",
      value: "VUV",
      position: 146
    },
    {
      id: "99e282d5-91ed-4a0f-bdb3-f6af803bd40b",
      color: "orange",
      label: "WST — Samoan tala",
      value: "WST",
      position: 147
    },
    {
      id: "efc1f1e6-dcf3-4513-9f41-6f1e8239fa95",
      color: "yellow",
      label: "XCD — East Caribbean dollar",
      value: "XCD",
      position: 148
    },
    {
      id: "b4ae3fd7-3e68-4070-bd5f-2086a187f9ca",
      color: "gray",
      label: "XOF — West African CFA franc",
      value: "XOF",
      position: 149
    },
    {
      id: "759a364a-9818-492d-b6e5-075787040d94",
      color: "green",
      label: "YER — Yemeni rial",
      value: "YER",
      position: 150
    },
    {
      id: "680a806a-d70a-4c72-9221-6df819e7c625",
      color: "turquoise",
      label: "ZAR — South African rand",
      value: "ZAR",
      position: 151
    },
    {
      id: "57055fa7-99a4-4230-a7ca-417d6cb3973f",
      color: "sky",
      label: "ZMW — Zambian kwacha",
      value: "ZMW",
      position: 152
    },
    {
      id: "16dab4bb-abd0-4a15-aa47-7f8f028dcd47",
      color: "blue",
      label: "ZWG — Zimbabwe Gold",
      value: "ZWG",
      position: 153
    }
  ]
});
