// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "97c9f266-01a4-5bff-a35c-e5a2037d5593",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.NUMBER,
  name: "brokenPromiseCount",
  label: "Broken Promise Count",
  icon: "IconAlertTriangle",
  isNullable: true
});
