// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "c391f4c1-cae8-4463-9e7b-eb6965cd8cc3",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.TEXT,
  name: "businessName",
  label: "Business Name",
  description: "Official registered name, as opposed to the quick-capture lead name",
  icon: "IconBuildingStore",
  isNullable: true
});
