// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "6e051351-b14e-40e0-92fb-008e947d02e7",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.SELECT,
  name: "buyerSegment",
  label: "Buyer Segment",
  icon: "IconChartPie",
  isNullable: true,
  options: [
    {
      id: "70da2622-a8ff-4e2b-88ee-d2a430d9b23b",
      color: "green",
      label: "Retail",
      value: "RETAIL",
      position: 0
    },
    {
      id: "dc229512-8a81-4d00-ba26-b40fc3cd56a6",
      color: "sky",
      label: "Online Florists",
      value: "ONLINE_FLORISTS",
      position: 1
    },
    {
      id: "c5e9c31e-eaf7-4a36-8ea5-02c7918814f7",
      color: "turquoise",
      label: "Supermarkets",
      value: "SUPERMARKETS",
      position: 2
    },
    {
      id: "445ed4e5-70ac-4730-9b14-856dbf090aae",
      color: "orange",
      label: "Hotels",
      value: "HOTELS",
      position: 3
    },
    {
      id: "6cf5f051-1892-43d3-885e-ca6fd9f68d74",
      color: "pink",
      label: "Wedding and events",
      value: "WEDDING_AND_EVENTS",
      position: 4
    },
    {
      id: "ca257a8e-a7ee-49dd-98ad-71d7a35fc28c",
      color: "purple",
      label: "Wholesalers",
      value: "WHOLESALERS",
      position: 5
    }
  ]
});
