// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "a730b7c7-1ffa-4158-a5b3-b15a8e8cd243",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.TEXT,
  name: "city",
  label: "City",
  icon: "IconMapPin",
  isNullable: true
});
