// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "8aa9ae46-80c8-51f3-b7e8-f4feb9f23ab5",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "clientTier",
  label: "Client Tier",
  icon: "IconDiamond",
  isNullable: true,
  options: [
    {
      id: "f33ec10f-710b-5ab4-901e-edc09bf16ffa",
      color: "yellow",
      label: "Gold",
      value: "GOLD",
      position: 0
    },
    {
      id: "959e785a-8601-5cb9-8296-878a8c413167",
      color: "gray",
      label: "Silver",
      value: "SILVER",
      position: 1
    },
    {
      id: "569a1b22-5bf4-5e00-be69-e81b7d3613ad",
      color: "orange",
      label: "Bronze",
      value: "BRONZE",
      position: 2
    }
  ]
});
