// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "8942d97d-790a-50cc-a77c-e6a1093a2808",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "cmsStatus",
  label: "CMS Status",
  description: "(sync) platform registration state",
  icon: "IconProgress",
  isNullable: true,
  options: [
    {
      id: "dd5cae31-5e56-5d15-8b47-962c23cfc864",
      color: "green",
      label: "Pending",
      value: "PENDING",
      position: 0
    },
    {
      id: "307e285f-c116-55da-bac2-500b94eb1228",
      color: "turquoise",
      label: "Under Review",
      value: "UNDER_REVIEW",
      position: 1
    },
    {
      id: "f40ee36f-d7be-5c5a-af86-d2467fe10e6d",
      color: "sky",
      label: "Pending Setup",
      value: "PENDING_SETUP",
      position: 2
    },
    {
      id: "9ff5d01e-44bb-532d-965c-258bc9bb75cc",
      color: "green",
      label: "Approved",
      value: "APPROVED",
      position: 3
    },
    {
      id: "ac990c9e-aa8f-5b21-bb73-0dc15ecc9690",
      color: "red",
      label: "Rejected",
      value: "REJECTED",
      position: 4
    },
    {
      id: "2f9772e1-fbf2-56e9-8ba9-1d16f9d0a491",
      color: "pink",
      label: "Suspended",
      value: "SUSPENDED",
      position: 5
    }
  ]
});
