// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "e6741110-d9a5-5240-b2ce-5a09423b0c9e",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.TEXT,
  name: "cmsCustomerId",
  label: "CMS Customer Id",
  description: "customer-management-service customers._id (sync)",
  icon: "IconDatabase",
  isNullable: true
});
