// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, RelationType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "6bc07c35-3763-5160-88dd-64d5a6b0b58d",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.RELATION,
  name: "collectionsCases",
  label: "Collections Cases",
  icon: "IconGavel",
  isNullable: true,
  relationTargetObjectMetadataUniversalIdentifier: "d9fc138e-e50c-5835-85c1-51793672be07" /* collectionsCase */,
  relationTargetFieldMetadataUniversalIdentifier: "47c22935-fe39-5f89-b4b0-8049f41e242b",
  universalSettings: {
    relationType: RelationType.ONE_TO_MANY
  }
});
