// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "0bc0a045-7e12-54eb-9a96-db2f3b47c385",
  objectUniversalIdentifier: "20202020-e674-48e5-a542-72570eee7213" /* person */,
  type: FieldType.BOOLEAN,
  name: "consentGiven",
  label: "Consent Given",
  description: "NFR-07 messaging consent",
  icon: "IconShieldCheck",
  isNullable: true
});
