// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "ec5127b6-834f-4a3b-a577-e5b27eeb6396",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.TEXT,
  name: "country",
  label: "Country",
  icon: "IconMapPin",
  isNullable: true
});
