// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "b23c0b93-b252-5644-97de-a1d0033e28bb",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.CURRENCY,
  name: "creditLimit",
  label: "Credit Limit",
  description: "(sync from ERP payment terms)",
  icon: "IconWallet",
  isNullable: true
});
