// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "59ddc2c6-7c7a-463b-b4c1-68c4fc58b3d2",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.SELECT,
  name: "customerType",
  label: "Customer Type",
  icon: "IconBuildingStore",
  isNullable: true,
  options: [
    {
      id: "bde018d2-beca-4adc-8818-73fb1020da3f",
      color: "blue",
      label: "Reseller",
      value: "RESELLER",
      position: 0
    },
    {
      id: "2e831723-45d8-4581-b859-133f72644e3b",
      color: "green",
      label: "Retail",
      value: "RETAIL",
      position: 1
    },
    {
      id: "d4ff314f-7e82-4e8b-a06c-0e71f1d0bb2f",
      color: "orange",
      label: "FOB",
      value: "FOB",
      position: 2
    },
    {
      id: "d3f7df38-1f99-44d9-861f-afdef0a62115",
      color: "purple",
      label: "CIF",
      value: "CIF",
      position: 3
    }
  ]
});
