// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "2e3c4f02-c367-58a9-897b-0773ff609b49",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "customerType",
  label: "Customer Type",
  description: "(sync from ERP/CMS)",
  icon: "IconUsers",
  isNullable: true,
  options: [
    {
      id: "d357f8a2-d66c-56f1-808e-54b36ea7d7cf",
      color: "green",
      label: "Retail",
      value: "RETAIL",
      position: 0
    },
    {
      id: "a5ec98a5-537c-50fd-9140-bea51168755c",
      color: "turquoise",
      label: "Reseller",
      value: "RESELLER",
      position: 1
    },
    {
      id: "bcea6f85-5083-5172-8dce-ee47e33472cf",
      color: "sky",
      label: "Fob",
      value: "FOB",
      position: 2
    },
    {
      id: "4d456d45-0a55-5e26-92ba-d180e85043da",
      color: "blue",
      label: "Cif",
      value: "CIF",
      position: 3
    }
  ]
});
