// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "59ddc2c6-7c7a-463b-b4c1-68c4fc58b3d2",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.SELECT,
  name: "customerType",
  label: "Customer Type",
  icon: "IconBuildingStore",
  isNullable: true,
  options: [
    {
      id: "2e831723-45d8-4581-b859-133f72644e3b",
      color: "green",
      label: "Retail",
      value: "RETAIL",
      position: 0
    },
    {
      id: "7cf12d57-394c-415c-9883-a73747b88374",
      color: "sky",
      label: "E-Tailer",
      value: "E_TAILER",
      position: 1
    },
    {
      id: "4219b14a-3ab7-4789-bc83-c0db3814d1b0",
      color: "pink",
      label: "Wedding & Events",
      value: "WEDDING_EVENTS",
      position: 2
    },
    {
      id: "c24dfb85-561d-4925-b9f8-168c687081e4",
      color: "purple",
      label: "Wholesaler",
      value: "WHOLESALER",
      position: 3
    }
  ]
});
