// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "41148a43-6f17-43f2-a792-22ac200e84bb",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.SELECT,
  name: "customerCategory",
  label: "Customer Category",
  icon: "IconCategory",
  isNullable: true,
  options: [
    {
      id: "e51def48-7952-4665-93c2-eb4eecb001f4",
      color: "orange",
      label: "Hotels",
      value: "HOTELS",
      position: 0
    },
    {
      id: "c488b875-4d2c-4a5d-9a9e-560e5045b9e6",
      color: "sky",
      label: "Online",
      value: "ONLINE",
      position: 1
    },
    {
      id: "756afdef-cf9b-4726-96f1-255a7585c958",
      color: "green",
      label: "Plant Nurseries",
      value: "PLANT_NURSERIES",
      position: 2
    },
    {
      id: "94c8b96f-9892-4904-801d-1dcb6dfa315f",
      color: "turquoise",
      label: "Retail Shops",
      value: "RETAIL_SHOPS",
      position: 3
    },
    {
      id: "2ff5e6d0-c617-4be6-ab83-576ad2e45118",
      color: "blue",
      label: "Supermarkets",
      value: "SUPERMARKETS",
      position: 4
    },
    {
      id: "29e568e0-92fd-462e-bce2-865b6f29d028",
      color: "pink",
      label: "Weddings & Events",
      value: "WEDDINGS_EVENTS",
      position: 5
    },
    {
      id: "b1108335-0f44-4b16-a392-1cf46b152b06",
      color: "purple",
      label: "Wholesaler",
      value: "WHOLESALER",
      position: 6
    },
    {
      id: "2c8cf4a1-5e2e-4f65-9150-2f36766712b8",
      color: "gray",
      label: "Internal Users",
      value: "INTERNAL_USERS",
      position: 7
    },
    {
      id: "73b7fada-eb3e-4b9a-904b-3bf0fb3a2c31",
      color: "red",
      label: "Internal Buyers",
      value: "INTERNAL_BUYERS",
      position: 8
    }
  ]
});
