// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "414a93fa-a4a5-570e-b156-e5d821af876a",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.NUMBER,
  name: "daysSinceLastOrder",
  label: "Days Since Last Order",
  description: "(sync)",
  icon: "IconCalendarStats",
  isNullable: true
});
