// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "c9dc1d2c-4868-4e95-b3a4-75dab649a5c1",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.TEXT,
  name: "debtorNumber",
  label: "Debtor Number",
  description: "Set once the customer is registered; empty means pending registration",
  icon: "IconNumber",
  isNullable: true
});
