// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "1ea6631e-c368-5fc4-8854-805c8d5b5245",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.TEXT,
  name: "debtorNumber",
  label: "Debtor Number",
  description: "ERP business key — unique",
  icon: "IconId",
  isNullable: true
});
