// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "4949210f-43a8-5305-8c46-2211121f0cb3",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.DATE,
  name: "deferredUntil",
  label: "Deferred Until",
  icon: "IconCalendarPause",
  isNullable: true
});
