// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "81b6ffb2-3869-5618-a9ad-bc4b0d38839b",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "deliveryZone",
  label: "Delivery Zone",
  description: "CRM-managed territory key for AM assignment",
  icon: "IconMap",
  isNullable: true,
  options: [
    {
      id: "6f0bfd89-67c7-5077-b906-69acf4759569",
      color: "green",
      label: "Dubai",
      value: "DUBAI",
      position: 0
    },
    {
      id: "81e97815-d010-5aae-9984-f7fcb9daa095",
      color: "turquoise",
      label: "Dubai Out",
      value: "DUBAI_OUT",
      position: 1
    },
    {
      id: "36a3544a-be9b-50ff-84bb-5d34141c0910",
      color: "sky",
      label: "Auh 01",
      value: "AUH_01",
      position: 2
    },
    {
      id: "130d723c-b435-58db-b6c8-e0438e24b738",
      color: "blue",
      label: "Auh 02",
      value: "AUH_02",
      position: 3
    },
    {
      id: "eb66b5e6-4d53-5c1a-9b4f-f9f1f9e3b144",
      color: "purple",
      label: "Aan 01",
      value: "AAN_01",
      position: 4
    },
    {
      id: "baf22d97-3379-53dc-ad49-0bb4a2d61473",
      color: "pink",
      label: "Shj",
      value: "SHJ",
      position: 5
    },
    {
      id: "95c20e5c-6cd6-5c28-8c03-a10e1a99c4fb",
      color: "red",
      label: "Ajm",
      value: "AJM",
      position: 6
    },
    {
      id: "c62471aa-f1e1-54a1-8f17-d7b446ec171b",
      color: "orange",
      label: "Ne04",
      value: "NE04",
      position: 7
    },
    {
      id: "e80bebb4-703b-5586-8294-217dcb3d73bc",
      color: "yellow",
      label: "Rak",
      value: "RAK",
      position: 8
    },
    {
      id: "ae069256-d6cd-536c-8ab8-b520c0dc81a3",
      color: "gray",
      label: "Fjh",
      value: "FJH",
      position: 9
    },
    {
      id: "a0e0525a-5826-52f8-aa08-3b33432ab179",
      color: "green",
      label: "Uaq",
      value: "UAQ",
      position: 10
    }
  ]
});
