// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "0d7d96ad-f4d0-4272-8fe9-57e777faa1d0",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.TEXT,
  name: "disqualifiedReason",
  label: "Disqualified Reason",
  icon: "IconX",
  isNullable: true
});
