// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "2d13ea2c-2087-5f74-aa00-eac72fa63092",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.NUMBER,
  name: "erpUserId",
  label: "ERP User Id",
  description: "Floranow-ERP users.id (sync)",
  icon: "IconDatabase",
  isNullable: true
});
