// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "41dd11c0-a6b3-5aa8-88bb-01c80d0f313e",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "erpBlockedStatus",
  label: "ERP Blocked Status",
  description: "(sync) users.order_blocked_status",
  icon: "IconBan",
  isNullable: true,
  options: [
    {
      id: "092cd6c1-1688-5393-85b3-914686321b79",
      color: "green",
      label: "Unblocked",
      value: "UNBLOCKED",
      position: 0
    },
    {
      id: "0e17edeb-ea60-53a9-ad49-a877854cf32b",
      color: "turquoise",
      label: "Manual Block",
      value: "MANUAL_BLOCK",
      position: 1
    },
    {
      id: "3d1f8f62-82cd-5121-88f0-6491f5a2987e",
      color: "sky",
      label: "Exceed Limit",
      value: "EXCEED_LIMIT",
      position: 2
    },
    {
      id: "a3f7dd02-c040-5bde-aad8-eabf8982c634",
      color: "blue",
      label: "Overdue Invoices",
      value: "OVERDUE_INVOICES",
      position: 3
    },
    {
      id: "c6262676-71e2-5a8a-b490-d47bc33c1c01",
      color: "purple",
      label: "Other",
      value: "OTHER",
      position: 4
    }
  ]
});
