// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "61f6f577-913b-5f00-ac96-5fcb4c195386",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "erpRoute",
  label: "ERP Route",
  description: "(sync) delivery route mirror",
  icon: "IconRoute",
  isNullable: true,
  options: [
    {
      id: "0808ec85-4268-529f-9755-928d3409b68a",
      color: "green",
      label: "Dubai City",
      value: "DUBAI_CITY",
      position: 0
    },
    {
      id: "e8e20aa9-6578-585c-af9f-03dd47f33227",
      color: "turquoise",
      label: "Dubai Out Of City",
      value: "DUBAI_OUT_OF_CITY",
      position: 1
    },
    {
      id: "49f62b7b-58b0-5b1f-9c46-da7ce47c74ee",
      color: "sky",
      label: "Abu Dhabi City",
      value: "ABU_DHABI_CITY",
      position: 2
    },
    {
      id: "8aab8cfa-9223-53c4-a602-2e7b0c3ae2e9",
      color: "blue",
      label: "Abu Dhabi Out Of City",
      value: "ABU_DHABI_OUT_OF_CITY",
      position: 3
    },
    {
      id: "d2f7cdce-5ab3-56e3-968f-8645599b01b5",
      color: "purple",
      label: "Sharjah",
      value: "SHARJAH",
      position: 4
    },
    {
      id: "0f1fd75a-52a5-5703-9fd4-aabe87b2c19c",
      color: "pink",
      label: "Ajman",
      value: "AJMAN",
      position: 5
    },
    {
      id: "5e937694-3a0d-563a-be5a-f9c4339e673e",
      color: "red",
      label: "Ras Al Khaimah",
      value: "RAS_AL_KHAIMAH",
      position: 6
    },
    {
      id: "7eecd8d4-7bcd-5691-b4a3-14fc3970debc",
      color: "orange",
      label: "Al Ain",
      value: "AL_AIN",
      position: 7
    },
    {
      id: "db830080-9b6b-505a-843e-254842fb5b92",
      color: "yellow",
      label: "Al Ain 1",
      value: "AL_AIN_1",
      position: 8
    },
    {
      id: "d1672dec-2432-5df8-b3af-18bac789d0dc",
      color: "gray",
      label: "Northern Emirates",
      value: "NORTHERN_EMIRATES",
      position: 9
    },
    {
      id: "176cc1cf-5db7-5fcd-b12a-5f3a16ed1c83",
      color: "green",
      label: "Umm Al Quwain",
      value: "UMM_AL_QUWAIN",
      position: 10
    },
    {
      id: "44e32cd8-16e7-5265-9b93-23338c66342e",
      color: "turquoise",
      label: "Fujairah",
      value: "FUJAIRAH",
      position: 11
    },
    {
      id: "883c7589-114e-5c66-a286-dd45f4d52861",
      color: "sky",
      label: "Supermarkets",
      value: "SUPERMARKETS",
      position: 12
    },
    {
      id: "268ce838-fdf2-5037-9beb-0aecb14b1ab3",
      color: "blue",
      label: "Hotels",
      value: "HOTELS",
      position: 13
    },
    {
      id: "1be723f7-d345-5266-bf15-657f1f3c0a6b",
      color: "purple",
      label: "Internal Uae",
      value: "INTERNAL_UAE",
      position: 14
    },
    {
      id: "13f4c45e-88d0-53a6-b4db-187bc5af6a7b",
      color: "pink",
      label: "Alissar",
      value: "ALISSAR",
      position: 15
    }
  ]
});
