// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "9f5f3940-5523-5884-8b06-79b72c56d42f",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.BOOLEAN,
  name: "fcContactVerified",
  label: "FC-1 Contact Verified",
  icon: "IconChecklist",
  isNullable: true
});
