// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "caef83d4-0d43-55d5-9122-4532f5522da0",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.BOOLEAN,
  name: "fcLoginWorking",
  label: "FC-3 Login Working",
  icon: "IconChecklist",
  isNullable: true
});
