// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "fb60b80a-1548-5dd4-b09c-041a9c61cdaf",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.BOOLEAN,
  name: "fcProfileConfirmed",
  label: "FC-2 Profile Confirmed",
  icon: "IconChecklist",
  isNullable: true
});
