// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "14991962-648a-502e-b60f-be4ef07d7366",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "fcToolkitOffered",
  label: "FC-4 Toolkit Offered",
  icon: "IconGift",
  isNullable: true,
  options: [
    {
      id: "795b1390-0821-513e-96d0-10282cb1e534",
      color: "green",
      label: "Voucher 200",
      value: "VOUCHER_200",
      position: 0
    },
    {
      id: "9d174dc9-b127-5868-a199-def03005730e",
      color: "turquoise",
      label: "Samples",
      value: "SAMPLES",
      position: 1
    },
    {
      id: "ce215117-2693-5988-a94f-2c4e254d8569",
      color: "sky",
      label: "Live Deal",
      value: "LIVE_DEAL",
      position: 2
    },
    {
      id: "1840449f-217b-5c26-b92f-1045c798aee6",
      color: "blue",
      label: "Declined",
      value: "DECLINED",
      position: 3
    }
  ]
});
