// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "42978904-859b-526f-a2cb-2807808c4959",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.BOOLEAN,
  name: "fcVisitBooked",
  label: "FC-5 Visit Booked",
  icon: "IconChecklist",
  isNullable: true
});
