// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "eb06a59d-f8b8-542f-a299-c87c6d9628d5",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.DATE_TIME,
  name: "firstContactAt",
  label: "First Contact At",
  icon: "IconClockCheck",
  isNullable: true
});
