// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "ee40828b-2dc8-48d2-986f-7ba48dd80be3",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.DATE,
  name: "firstOrderAt",
  label: "First Order At",
  icon: "IconShoppingCart",
  isNullable: true
});
