// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "d8e4c5f6-ef3c-5faa-9a63-fc0211504cad",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.DATE_TIME,
  name: "firstVisitAt",
  label: "First Visit At",
  icon: "IconClockCheck",
  isNullable: true
});
