// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "60dc9a4b-98a8-568b-bd6b-7e934c3544ed",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "inactivitySubTag",
  label: "Inactivity Sub-Tag",
  icon: "IconTagOff",
  isNullable: true,
  options: [
    {
      id: "50ee1489-02a1-5c61-ba85-cf7312573cb8",
      color: "green",
      label: "Market Slow",
      value: "MARKET_SLOW",
      position: 0
    },
    {
      id: "0ce959b5-0f23-5ba2-891a-ca0ff33a7585",
      color: "turquoise",
      label: "Waiting To Restart",
      value: "WAITING_TO_RESTART",
      position: 1
    },
    {
      id: "dd855610-bbe1-57fd-a7df-dff2d3660edc",
      color: "sky",
      label: "Switched Supplier",
      value: "SWITCHED_SUPPLIER",
      position: 2
    },
    {
      id: "440dfdc2-c998-5a9b-a4f5-1addea04568b",
      color: "blue",
      label: "Wrong Account",
      value: "WRONG_ACCOUNT",
      position: 3
    },
    {
      id: "d9525bd9-3dfd-5c56-8b28-16da4f477a36",
      color: "purple",
      label: "Seasonal Sleeper",
      value: "SEASONAL_SLEEPER",
      position: 4
    },
    {
      id: "df0f6a73-fcf1-5d59-ae5b-38a6a4e0d6f1",
      color: "pink",
      label: "Closed Business",
      value: "CLOSED_BUSINESS",
      position: 5
    }
  ]
});
