// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, RelationType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "c90c62a7-6b11-5fee-82e2-e9227f058550",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.RELATION,
  name: "incidents",
  label: "Incidents",
  icon: "IconAlertHexagon",
  isNullable: true,
  relationTargetObjectMetadataUniversalIdentifier: "ab30bd09-9b3b-51be-b096-8554f631b30a" /* incident */,
  relationTargetFieldMetadataUniversalIdentifier: "35582677-183a-568e-9013-4cacf47b4d72",
  universalSettings: {
    relationType: RelationType.ONE_TO_MANY
  }
});
