// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "6cbaf470-a3c2-4970-a43a-3e5f98998f0e",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.LINKS,
  name: "instagram",
  label: "Instagram",
  icon: "IconBrandInstagram",
  isNullable: true
});
