// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "e3c731f7-0af8-5056-8169-2c3d390b0d13",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "ladderStep",
  label: "Ladder Step",
  icon: "IconStairsUp",
  isNullable: true,
  options: [
    {
      id: "fe0cc6f1-d0ac-5f92-b2fe-ebdfd2266df3",
      color: "green",
      label: "None",
      value: "NONE",
      position: 0
    },
    {
      id: "2feb82a6-5905-5c32-8ea0-c77a6caabfc5",
      color: "turquoise",
      label: "D1",
      value: "D1",
      position: 1
    },
    {
      id: "98e0998d-307d-5025-acdb-09d2329f6163",
      color: "sky",
      label: "D3",
      value: "D3",
      position: 2
    },
    {
      id: "a9d8b08e-1a91-50fa-932c-f97366817ea3",
      color: "blue",
      label: "D7",
      value: "D7",
      position: 3
    },
    {
      id: "c213075d-717b-5b88-9b20-f01f946cf964",
      color: "purple",
      label: "Handed Over",
      value: "HANDED_OVER",
      position: 4
    },
    {
      id: "f8b004d9-29b8-5ecc-901c-f0f98efb31e9",
      color: "pink",
      label: "D14 Legal",
      value: "D14_LEGAL",
      position: 5
    },
    {
      id: "adc837b4-4c01-5d15-a32e-103823597a5b",
      color: "red",
      label: "D21 Court",
      value: "D21_COURT",
      position: 6
    },
    {
      id: "5d4940f4-e40f-5f5a-97e1-3caf12dd948a",
      color: "orange",
      label: "Write Off",
      value: "WRITE_OFF",
      position: 7
    }
  ]
});
