// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "11ca0949-87bc-54a3-a5f6-f43a39288a71",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.DATE_TIME,
  name: "lastSyncAt",
  label: "Last Sync At",
  description: "(sync) freshness indicator FR-21",
  icon: "IconRefresh",
  isNullable: true
});
