// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "3abe3e0e-caa0-55d1-b133-16f07c5d5c21",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.DATE,
  name: "lastOrderDate",
  label: "Last Order Date",
  description: "(sync)",
  icon: "IconCalendar",
  isNullable: true
});
