// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "5abfed05-be38-5c60-9d63-e06c35ecad35",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "lastOrderChannel",
  label: "Last Order Channel",
  description: "(sync)",
  icon: "IconDeviceMobile",
  isNullable: true,
  options: [
    {
      id: "f34245da-b87a-56ce-8006-81730f2af5df",
      color: "green",
      label: "Online",
      value: "ONLINE",
      position: 0
    },
    {
      id: "cde2060b-5468-525b-8d01-1e77d30cbb04",
      color: "orange",
      label: "Offline",
      value: "OFFLINE",
      position: 1
    }
  ]
});
