// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "d9ee784f-c33f-5b02-a1c0-d30bd6f8942f",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "lifecycleStage",
  label: "Lifecycle Stage",
  icon: "IconStairs",
  isNullable: true,
  options: [
    {
      id: "c44a204b-bac6-5046-a8b5-c8062a352d62",
      color: "green",
      label: "Onboarding",
      value: "ONBOARDING",
      position: 0
    },
    {
      id: "b9e829dc-b747-5d29-be43-771f6a6c75d7",
      color: "turquoise",
      label: "Retention",
      value: "RETENTION",
      position: 1
    },
    {
      id: "c6177f17-a8c0-5da3-8782-bc9407cf67d5",
      color: "sky",
      label: "Win Back",
      value: "WIN_BACK",
      position: 2
    },
    {
      id: "bae4711e-0a22-5f56-9dc5-ff8cc213934e",
      color: "blue",
      label: "Closed",
      value: "CLOSED",
      position: 3
    }
  ]
});
