// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "a15a5193-ec1a-499f-a5c0-2738525c7f83",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.LINKS,
  name: "location",
  label: "Location",
  description: "Google Maps link to the lead's location",
  icon: "IconMap2",
  isNullable: true
});
