// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "15478194-737f-56c6-9205-146b12c7df30",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.NUMBER,
  name: "longitude",
  label: "Longitude",
  icon: "IconMapPin",
  isNullable: true
});
