// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "d6017527-9f46-5e09-9259-2b27282c34fa",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.CURRENCY,
  name: "m1NetRevenue",
  label: "M-1 Net Revenue",
  description: "(sync)",
  icon: "IconChartBar",
  isNullable: true
});
