// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "b28edb52-526c-5a7b-9cbe-9d1e5cfd1e92",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.CURRENCY,
  name: "m2NetRevenue",
  label: "M-2 Net Revenue",
  description: "(sync)",
  icon: "IconChartBar",
  isNullable: true
});
