// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "df8c0848-55fc-5375-963d-6cc3d312c394",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.CURRENCY,
  name: "m3NetRevenue",
  label: "M-3 Net Revenue",
  description: "(sync)",
  icon: "IconChartBar",
  isNullable: true
});
