// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "bad58d59-3eae-5c9d-84d4-08cab95bad4e",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.CURRENCY,
  name: "mtdNetRevenue",
  label: "MTD Net Revenue",
  description: "(sync)",
  icon: "IconChartBar",
  isNullable: true
});
