// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "27507dd4-7a7d-5816-b949-78028502744d",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.BOOLEAN,
  name: "newClientProtected",
  label: "New-Client Protected",
  description: "White Petals protocol window",
  icon: "IconShield",
  isNullable: true
});
