// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "10bed5fe-bf6b-4630-95fa-f16f055db13d",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "onboardingBlocker",
  label: "Onboarding Blocker",
  icon: "IconBarrierBlock",
  isNullable: true,
  options: [
    {
      id: "6da69893-bff6-4bf1-b0cc-111782b14b22",
      color: "sky",
      label: "Platform",
      value: "PLATFORM",
      position: 0
    },
    {
      id: "32b6b917-84ce-4475-8672-e5d0a5ce3e35",
      color: "orange",
      label: "Price",
      value: "PRICE",
      position: 1
    },
    {
      id: "55b7500e-5486-4166-be99-1d18d26aff48",
      color: "green",
      label: "Product",
      value: "PRODUCT",
      position: 2
    },
    {
      id: "23251acf-c884-48a1-8054-aa8279259928",
      color: "red",
      label: "Trust / Doesn’t trust online",
      value: "TRUST",
      position: 3
    },
    {
      id: "a9d8c776-0d65-4207-a6fa-88f09ef6cf15",
      color: "purple",
      label: "Language",
      value: "LANGUAGE",
      position: 4
    },
    {
      id: "be4fdcbe-b245-4adb-939d-89a505b78ebf",
      color: "yellow",
      label: "Habit / Prefers calling",
      value: "HABIT",
      position: 5
    },
    {
      id: "54f11795-24f4-48e1-a8cf-92053d2c2b3b",
      color: "pink",
      label: "UX Issue",
      value: "UX_ISSUE",
      position: 6
    },
    {
      id: "87b67ba4-6524-4f51-9e9c-0f67363d069a",
      color: "gray",
      label: "Other",
      value: "OTHER",
      position: 7
    }
  ]
});
