// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "a1e326f4-cb99-4680-8600-450f703dd833",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.LINKS,
  name: "onlineStoreUrl",
  label: "Online Store / URL",
  icon: "IconWorld",
  isNullable: true
});
