// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "bb94938b-98a5-54e1-9e2f-00c84a301cfb",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.NUMBER,
  name: "orderCountLifetime",
  label: "Order Count (Lifetime)",
  description: "(sync)",
  icon: "IconShoppingCart",
  isNullable: true
});
