// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "ee2819ad-3cc2-4c5c-a673-97a6fd7f33d9",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.SELECT,
  name: "orderFrequency",
  label: "Order Frequency",
  icon: "IconRepeat",
  isNullable: true,
  options: [
    {
      id: "9b801504-d95b-41f1-953c-752a2a4ea167",
      color: "green",
      label: "Daily",
      value: "DAILY",
      position: 0
    },
    {
      id: "bef31505-22e4-4ebb-a9f8-f7b613f4a740",
      color: "blue",
      label: "2–3x Week",
      value: "TWO_THREE_X_WEEK",
      position: 1
    },
    {
      id: "db214b3b-5690-4d80-9469-1db4fb7b3529",
      color: "sky",
      label: "Weekly",
      value: "WEEKLY",
      position: 2
    },
    {
      id: "f7bfe22a-f9b6-460a-8d90-3b7661bd038e",
      color: "orange",
      label: "Event Based",
      value: "EVENT_BASED",
      position: 3
    }
  ]
});
