// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, RelationType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "fc564050-d8b6-5668-9936-52b8ced972cc",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.RELATION,
  name: "orderEvents",
  label: "Order Events",
  icon: "IconTruckDelivery",
  isNullable: true,
  relationTargetObjectMetadataUniversalIdentifier: "aa860ef9-896f-5677-84f2-e69fefd3b630" /* orderEvent */,
  relationTargetFieldMetadataUniversalIdentifier: "6628254f-03b7-5fa8-8d4b-2511aed38443",
  universalSettings: {
    relationType: RelationType.ONE_TO_MANY
  }
});
