// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "66a258f9-e776-43d4-9006-f3e821f2b9f0",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.LINKS,
  name: "otherSocialLinks",
  label: "Other Social Links",
  description: "Any other social profile — X, LinkedIn, WhatsApp, Snapchat …",
  icon: "IconShare",
  isNullable: true
});
