// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, OnDeleteAction, RelationType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "edf62a0c-0466-5ac9-b485-cbcaf36e206a",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.RELATION,
  name: "parentCompany",
  label: "Parent Company",
  icon: "IconHierarchy",
  isNullable: true,
  relationTargetObjectMetadataUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  relationTargetFieldMetadataUniversalIdentifier: "9e360a6a-69a4-5872-8da9-a1ff1cc93ce1",
  universalSettings: {
    onDelete: OnDeleteAction.SET_NULL,
    relationType: RelationType.MANY_TO_ONE,
    joinColumnName: "parentCompanyId"
  }
});
