// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "cdf8b1c3-8d33-4ff3-9197-fddf6c161fb3",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.SELECT,
  name: "paymentHistory",
  label: "Payment History",
  icon: "IconCreditCard",
  isNullable: true,
  options: [
    {
      id: "056bebc7-563f-477b-a896-8e040e1eb9d0",
      color: "green",
      label: "Clean",
      value: "CLEAN",
      position: 0
    },
    {
      id: "35736d5f-80c6-4f3b-8b32-6559414abc32",
      color: "red",
      label: "Issues Noted",
      value: "ISSUES_NOTED",
      position: 1
    },
    {
      id: "93ba0c2e-e1e5-4dd0-97bf-6d1ac1b59418",
      color: "gray",
      label: "Unknown",
      value: "UNKNOWN",
      position: 2
    }
  ]
});
