// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, RelationType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "ca976ddd-e5f2-5fdc-846e-c3fbc21c7fbc",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.RELATION,
  name: "paymentPromises",
  label: "Payment Promises",
  icon: "IconHeartHandshake",
  isNullable: true,
  relationTargetObjectMetadataUniversalIdentifier: "730c3de2-6bc0-501d-bbde-d81453da11d2" /* paymentPromise */,
  relationTargetFieldMetadataUniversalIdentifier: "c31868c9-638f-5ebe-8d70-b4eeb7c4df23",
  universalSettings: {
    relationType: RelationType.ONE_TO_MANY
  }
});
