// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "bbae4390-f35d-53ce-8c4b-afcc407d092f",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "paymentTrack",
  label: "Payment Track",
  description: "Finance-only edit — paces the ladder",
  icon: "IconTrafficLights",
  isNullable: true,
  defaultValue: "'AMBER'",
  options: [
    {
      id: "4f10f765-9adf-56a2-b726-3a0997faa7af",
      color: "green",
      label: "Green",
      value: "GREEN",
      position: 0
    },
    {
      id: "86ac5fa0-902d-5474-8bed-36532ce37511",
      color: "yellow",
      label: "Amber",
      value: "AMBER",
      position: 1
    },
    {
      id: "0bc74e10-422b-5c56-8237-0e580148d341",
      color: "red",
      label: "Red",
      value: "RED",
      position: 2
    }
  ]
});
