// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "cf6ded16-e387-540a-8e5a-3610872d853d",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "paymentTerm",
  label: "Payment Term",
  icon: "IconCreditCard",
  isNullable: true,
  options: [
    {
      id: "e7ccd5bb-2763-5d99-b797-8835383f8b16",
      color: "green",
      label: "Cod",
      value: "COD",
      position: 0
    },
    {
      id: "9dff1495-e748-5eb0-81c8-d71ad850ebe1",
      color: "turquoise",
      label: "Prepay",
      value: "PREPAY",
      position: 1
    },
    {
      id: "9b3a4a82-7a74-5015-8102-8a8e05b0b8a6",
      color: "sky",
      label: "Net7",
      value: "NET7",
      position: 2
    },
    {
      id: "8a7582f0-fb30-5520-8cd8-ace74008b851",
      color: "blue",
      label: "Net14",
      value: "NET14",
      position: 3
    },
    {
      id: "e1fe176e-17fc-56e3-ba7f-67fc0c290165",
      color: "purple",
      label: "Net15",
      value: "NET15",
      position: 4
    },
    {
      id: "94283d60-8ab9-5eb5-a6b2-01cba2eb8d7c",
      color: "pink",
      label: "Net30",
      value: "NET30",
      position: 5
    },
    {
      id: "ce8cd1e0-752b-5e80-9d77-e33c203efff4",
      color: "red",
      label: "Net45",
      value: "NET45",
      position: 6
    },
    {
      id: "abac76ca-7f5f-5749-bf72-f95786a2e0b7",
      color: "orange",
      label: "Net60",
      value: "NET60",
      position: 7
    },
    {
      id: "4afda82f-a347-50c1-81f9-1773f22d3be0",
      color: "yellow",
      label: "Net90",
      value: "NET90",
      position: 8
    },
    {
      id: "512a00d9-434d-5e1e-b466-680d14403be5",
      color: "gray",
      label: "Nm 7th",
      value: "NM_7TH",
      position: 9
    },
    {
      id: "17e10e07-a4f3-5d13-9b2b-eb53cd7d8843",
      color: "green",
      label: "Nm 15th",
      value: "NM_15TH",
      position: 10
    },
    {
      id: "400f9d92-9c4e-5c92-97be-29eca2a26917",
      color: "turquoise",
      label: "Nm 25th",
      value: "NM_25TH",
      position: 11
    },
    {
      id: "6673a666-d5d2-52ee-afbf-61b050c3a061",
      color: "sky",
      label: "Nm 28th",
      value: "NM_28TH",
      position: 12
    },
    {
      id: "d7ab3685-416c-5efe-8537-94b7bbbc0527",
      color: "blue",
      label: "Without Invoicing",
      value: "WITHOUT_INVOICING",
      position: 13
    }
  ]
});
