// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "6285107f-f6f3-574b-95fe-c6a7911dfa89",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.CURRENCY,
  name: "potentialRevenue",
  label: "Potential Revenue",
  description: "(sync)",
  icon: "IconTrendingUp",
  isNullable: true
});
