// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "ad8d53e0-e7c0-5c6a-a715-4f31a1ba66aa",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.BOOLEAN,
  name: "prepayOnly",
  label: "Prepay Only",
  icon: "IconLock",
  isNullable: true
});
