// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "0f69bc82-756c-5ab4-88d6-1a777f258c48",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.NUMBER,
  name: "promiseKeptRate",
  label: "Promise-Kept Rate",
  icon: "IconPercentage",
  isNullable: true
});
