// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "92637bc4-e7e4-5ccf-a5f1-0fb8daeb9286",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.NUMBER,
  name: "protectedOrdersCount",
  label: "Protected Orders Count",
  icon: "IconShieldCheck",
  isNullable: true
});
