// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "24d0c985-9e96-4b35-ba30-adf26656b794",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.DATE,
  name: "qualificationDate",
  label: "Qualification Date",
  icon: "IconCalendarCheck",
  isNullable: true
});
