// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "cb838d33-9a3c-58a0-b70c-47c609f9ff2e",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.CURRENCY,
  name: "receivableM1",
  label: "Receivable M-1",
  description: "(sync)",
  icon: "IconCashBanknote",
  isNullable: true
});
