// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "ffc01070-0f5a-5ed4-b654-a40e96bcb15d",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.CURRENCY,
  name: "receivableM2",
  label: "Receivable M-2",
  description: "(sync)",
  icon: "IconCashBanknote",
  isNullable: true
});
