// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "5602ab24-fb2c-58d9-ad14-e84cb412dfd6",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.CURRENCY,
  name: "receivableM3",
  label: "Receivable M-3",
  description: "(sync)",
  icon: "IconCashBanknote",
  isNullable: true
});
