// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "985c544d-fb77-55e4-8e0f-515fe240323f",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.CURRENCY,
  name: "receivableMtd",
  label: "Receivable MTD",
  description: "(sync)",
  icon: "IconCashBanknote",
  isNullable: true
});
