// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "d2360ad3-700e-5c8b-b271-a77e180e772d",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.SELECT,
  name: "registrationPath",
  label: "Registration Path",
  description: "A = Marketing completes · B = AM verifies",
  icon: "IconGitFork",
  isNullable: true,
  options: [
    {
      id: "ed388373-18ff-5059-9bf4-8a4be2f86099",
      color: "green",
      label: "Path A",
      value: "PATH_A",
      position: 0
    },
    {
      id: "9c979733-bf86-56b7-99d4-4e01eae34c33",
      color: "turquoise",
      label: "Path B",
      value: "PATH_B",
      position: 1
    }
  ]
});
