// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "98875398-184f-544d-b4c9-b57b3ecbb0dc",
  objectUniversalIdentifier: "20202020-e674-48e5-a542-72570eee7213" /* person */,
  type: FieldType.SELECT,
  name: "role",
  label: "Role",
  description: "Collections ladder targets the Accountant",
  icon: "IconUserCog",
  isNullable: true,
  options: [
    {
      id: "a47c5579-5fb3-5ef8-bfdd-a85ee362f51b",
      color: "green",
      label: "Owner",
      value: "OWNER",
      position: 0
    },
    {
      id: "7682d295-f4fc-5511-8045-e173a8ea29f2",
      color: "turquoise",
      label: "Purchaser",
      value: "PURCHASER",
      position: 1
    },
    {
      id: "ec64a206-9dd1-55d0-80ed-0af34b806655",
      color: "sky",
      label: "Accountant",
      value: "ACCOUNTANT",
      position: 2
    },
    {
      id: "3bde0d8d-aef1-5357-be66-9d3583c05ef9",
      color: "blue",
      label: "Other",
      value: "OTHER",
      position: 3
    }
  ]
});
