// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from "twenty-sdk/define";

export default defineField({
  universalIdentifier: "4662fea5-eef3-4aea-ae67-666f8cae72c7",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.MULTI_SELECT,
  name: "salesChannels",
  label: "Sales Channels",
  description: "How this client sells to their own customers",
  icon: "IconShoppingCart",
  isNullable: true,
  options: [
    {
      id: "3a16e16b-f3be-4d1e-81c2-f004b46efad4",
      color: "green",
      label: "Physical Shop",
      value: "PHYSICAL_SHOP",
      position: 0
    },
    {
      id: "2c6f545a-a7db-4ea9-882e-40b61ca463f4",
      color: "turquoise",
      label: "Online Store",
      value: "ONLINE_STORE",
      position: 1
    },
    {
      id: "4acaf1ee-56f0-4cc4-a1d7-21a390f40ac5",
      color: "sky",
      label: "Instagram",
      value: "INSTAGRAM",
      position: 2
    },
    {
      id: "3f725582-c60e-4da1-ab4e-b3c9e57fc859",
      color: "blue",
      label: "WhatsApp",
      value: "WHATSAPP",
      position: 3
    },
    {
      id: "10709f98-595a-4b26-8f43-ac7190b2b667",
      color: "purple",
      label: "Phone Orders",
      value: "PHONE_ORDERS",
      position: 4
    },
    {
      id: "261a0c30-edeb-40a0-9a04-318153afb245",
      color: "pink",
      label: "Marketplace",
      value: "MARKETPLACE",
      position: 5
    },
    {
      id: "88ed6cad-9b51-40c1-9e1d-8aab5a0aae6c",
      color: "red",
      label: "Events & Weddings",
      value: "EVENTS_WEDDINGS",
      position: 6
    },
    {
      id: "58c942d3-0c3e-4839-9c6f-b0233e20299e",
      color: "orange",
      label: "Corporate / B2B",
      value: "CORPORATE",
      position: 7
    }
  ]
});
