// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "6734b6fe-6492-490c-ae8a-815124e979f1",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.DATE_TIME,
  name: "scQualityCall2At",
  label: "SC Quality Call 2",
  icon: "IconPhoneCheck",
  isNullable: true
});
