// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "0595cdf0-f7a2-4b2b-8522-4554b86f2232",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.DATE_TIME,
  name: "scQualityCall1At",
  label: "SC Quality Call 1",
  icon: "IconPhoneCheck",
  isNullable: true
});
