// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "1dcbdbdd-a764-4071-89b2-de3b28682537",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.DATE_TIME,
  name: "scQualityCall3At",
  label: "SC Quality Call 3",
  icon: "IconPhoneCheck",
  isNullable: true
});
