// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "3d34a6a8-f70a-566f-bc34-cd2fe791d0a0",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.MULTI_SELECT,
  name: "seasonalPattern",
  label: "Seasonal Pattern",
  icon: "IconCalendarHeart",
  isNullable: true,
  options: [
    {
      id: "41c71a08-d84e-5d7a-9ff2-c7dfc3507881",
      color: "green",
      label: "Valentines",
      value: "VALENTINES",
      position: 0
    },
    {
      id: "24fb1738-d4ae-566c-bd63-717e382a55b1",
      color: "turquoise",
      label: "Mothers Day",
      value: "MOTHERS_DAY",
      position: 1
    },
    {
      id: "4f1a0c10-6ce1-5ae9-a25b-663451f2de77",
      color: "sky",
      label: "Ramadan Eid",
      value: "RAMADAN_EID",
      position: 2
    },
    {
      id: "f316cd9d-be0b-5ef5-9a23-f9292bf10167",
      color: "blue",
      label: "Wedding Season",
      value: "WEDDING_SEASON",
      position: 3
    },
    {
      id: "b6096fd8-d49e-54c3-97c2-7ea13f7f3fd3",
      color: "purple",
      label: "Christmas",
      value: "CHRISTMAS",
      position: 4
    }
  ]
});
