// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "f85277a5-35f3-43a6-94cb-e86e0e06c849",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "serviceRecommended",
  label: "Service Recommended",
  icon: "IconStar",
  isNullable: true,
  options: [
    {
      id: "41e803be-46ab-4ce6-bfa8-83a916ddc368",
      color: "green",
      label: "Standing Order",
      value: "STANDING_ORDER",
      position: 0
    },
    {
      id: "ed0eec21-5821-4529-8ccd-1acf8acc4e82",
      color: "blue",
      label: "Farm-Direct",
      value: "FARM_DIRECT",
      position: 1
    },
    {
      id: "fca024ac-359f-4335-a77f-c85be5019a57",
      color: "orange",
      label: "Express Delivery",
      value: "EXPRESS",
      position: 2
    },
    {
      id: "b5256223-f88a-465b-9d05-d1b6028e5c59",
      color: "gray",
      label: "None",
      value: "NONE",
      position: 3
    }
  ]
});
