// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "82a318ff-1682-469b-ba70-f18608b32b7a",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.SELECT,
  name: "shopPresence",
  label: "Physical Shop",
  icon: "IconHome",
  isNullable: true,
  options: [
    {
      id: "3c0856c0-6ca7-47a2-ab68-796d62a253a0",
      color: "green",
      label: "Yes — Open",
      value: "YES_OPEN",
      position: 0
    },
    {
      id: "3b66cb09-b2f9-4ae6-9412-f389d5688895",
      color: "yellow",
      label: "Yes — Closed",
      value: "YES_CLOSED",
      position: 1
    },
    {
      id: "58a356d9-5889-42e9-9cab-38fcb9833fc2",
      color: "sky",
      label: "No — Online only",
      value: "NO_ONLINE_ONLY",
      position: 2
    },
    {
      id: "0749b0f9-5119-4b87-a286-efb2da3bb088",
      color: "gray",
      label: "Not yet open",
      value: "NOT_YET_OPEN",
      position: 3
    }
  ]
});
