// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "d8d2967b-877d-5109-8bfb-2dc33d1fc2b1",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.SELECT,
  name: "source",
  label: "Source",
  description: "BR-01.2 immutable after creation",
  icon: "IconTargetArrow",
  isNullable: true,
  options: [
    {
      id: "072da60e-3e7b-5a38-9fd2-86a23118ea37",
      color: "green",
      label: "Sm Ads",
      value: "SM_ADS",
      position: 0
    },
    {
      id: "dd70d3a5-977e-53a7-b0f8-8cbc5541e0d4",
      color: "turquoise",
      label: "Sm Dm",
      value: "SM_DM",
      position: 1
    },
    {
      id: "bb196457-7dde-5d88-ae25-7478fb44750e",
      color: "sky",
      label: "Sm Message",
      value: "SM_MESSAGE",
      position: 2
    },
    {
      id: "d09fec6d-0895-551e-b32e-e3564f97b7ee",
      color: "blue",
      label: "Mp Chat",
      value: "MP_CHAT",
      position: 3
    },
    {
      id: "f7c034b8-7419-5fc0-930a-8800fe800121",
      color: "purple",
      label: "Mp Selfreg",
      value: "MP_SELFREG",
      position: 4
    },
    {
      id: "ddd626f4-2e6e-509d-8908-0eb62782ad2f",
      color: "pink",
      label: "Mp Care",
      value: "MP_CARE",
      position: 5
    },
    {
      id: "e77e7946-acba-5144-a5da-d8e4febb0e4e",
      color: "red",
      label: "Ref Am",
      value: "REF_AM",
      position: 6
    },
    {
      id: "bc9479e9-0b81-57d6-9145-51827fa4c084",
      color: "orange",
      label: "Ref Partner",
      value: "REF_PARTNER",
      position: 7
    },
    {
      id: "a4b066f6-0c81-590d-bf21-dc8fc0aff167",
      color: "yellow",
      label: "Ref Account",
      value: "REF_ACCOUNT",
      position: 8
    },
    {
      id: "495257b9-0151-5e55-be17-52737ba00f07",
      color: "gray",
      label: "Scrape Maps",
      value: "SCRAPE_MAPS",
      position: 9
    },
    {
      id: "027bb58d-958d-59fa-bbfa-481dd908b9f1",
      color: "green",
      label: "Scrape Bleems",
      value: "SCRAPE_BLEEMS",
      position: 10
    },
    {
      id: "4cf3d3e2-6195-57a9-b449-6eb75be15c8c",
      color: "turquoise",
      label: "Scrape Flooww",
      value: "SCRAPE_FLOOWW",
      position: 11
    },
    {
      id: "0ee03369-4a95-4608-83d8-2cd565a7c421",
      color: "turquoise",
      label: "Scrape Social",
      value: "SCRAPE_SOCIAL",
      position: 12
    },
    {
      id: "7cbb5d2e-bbac-5253-bfdd-d7cf7aebc602",
      color: "sky",
      label: "Scrape Other",
      value: "SCRAPE_OTHER",
      position: 13
    },
    {
      id: "502fd8d6-da28-5050-af73-89f930f8c6fa",
      color: "blue",
      label: "Walk In",
      value: "WALK_IN",
      position: 14
    },
    {
      id: "07d07bdd-d0f3-5f3f-9c1a-c57c242c4bb7",
      color: "purple",
      label: "Event",
      value: "EVENT",
      position: 15
    },
    {
      id: "1cb94465-680f-522c-b027-7500de2296c8",
      color: "pink",
      label: "Outbound",
      value: "OUTBOUND",
      position: 16
    },
    {
      id: "e9a891f4-32f9-5e96-9826-b9c5dfe3ca8c",
      color: "red",
      label: "Inbound Call",
      value: "INBOUND_CALL",
      position: 17
    },
    {
      id: "83060a24-4af3-5a50-8243-d4d6b4ddd088",
      color: "orange",
      label: "Website",
      value: "WEBSITE",
      position: 18
    },
    {
      id: "07f00b18-8bf4-5abd-95ba-1ae64c306851",
      color: "yellow",
      label: "Other",
      value: "OTHER",
      position: 19
    },
    {
      id: "ca5d46df-502b-5690-8110-65cc62cccc28",
      color: "gray",
      label: "Legacy Migration",
      value: "LEGACY_MIGRATION",
      position: 20
    }
  ]
});
