// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, RelationType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "339851e8-f74c-5121-8d66-ef9836b884cc",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.RELATION,
  name: "standingOrders",
  label: "Standing Orders",
  icon: "IconRepeat",
  isNullable: true,
  relationTargetObjectMetadataUniversalIdentifier: "1d2f5ca4-4d73-5f46-9a86-118e41a67839" /* standingOrder */,
  relationTargetFieldMetadataUniversalIdentifier: "278d7932-bbea-5236-9c5a-e404877aa6b6",
  universalSettings: {
    relationType: RelationType.ONE_TO_MANY
  }
});
