// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "9c88542d-3ba2-46bb-816b-b489aadce6c1",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.TEXT,
  name: "state",
  label: "State",
  icon: "IconMapPin",
  isNullable: true
});
