// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, RelationType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "9e360a6a-69a4-5872-8da9-a1ff1cc93ce1",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.RELATION,
  name: "subsidiaries",
  label: "Subsidiaries",
  icon: "IconHierarchy",
  isNullable: true,
  relationTargetObjectMetadataUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  relationTargetFieldMetadataUniversalIdentifier: "edf62a0c-0466-5ac9-b485-cbcaf36e206a",
  universalSettings: {
    relationType: RelationType.ONE_TO_MANY
  }
});
