// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "615fc13e-7a9c-543d-8be1-18f34ddf2c92",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.BOOLEAN,
  name: "tierPinned",
  label: "Tier Pinned",
  description: "Manager pin — skip auto recompute",
  icon: "IconPin",
  isNullable: true
});
