// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "deba79a0-ac03-43bc-b2de-8277cd86a68f",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.LINKS,
  name: "tiktok",
  label: "TikTok",
  icon: "IconBrandTiktok",
  isNullable: true
});
