// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "6a9f2eb2-f62d-50f6-ba60-31b367ea1a69",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.CURRENCY,
  name: "totalReceivable",
  label: "Total Receivable",
  description: "(sync)",
  icon: "IconCashBanknote",
  isNullable: true
});
