// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "0d42013e-3683-5bcd-bd87-2174010b2fc8",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.TEXT,
  name: "tradeLicense",
  label: "Trade License",
  icon: "IconLicense",
  isNullable: true
});
