// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "4a3cc202-d650-54bf-b34a-d51839360b2c",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.TEXT,
  name: "vatNumber",
  label: "VAT Number",
  icon: "IconReceiptTax",
  isNullable: true
});
