// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "34a23bf7-1e17-4518-aea9-9b75805d7b5e",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.TEXT,
  name: "vatNumber",
  label: "VAT Number",
  icon: "IconReceiptTax",
  isNullable: true
});
