// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, RelationType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "aab1a388-8647-5ce7-87bd-4dda841d337d",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.RELATION,
  name: "visits",
  label: "Visits",
  icon: "IconMapPin",
  isNullable: true,
  relationTargetObjectMetadataUniversalIdentifier: "80155072-b338-5bd5-b7f7-2dde833c8c3e" /* visit */,
  relationTargetFieldMetadataUniversalIdentifier: "1ad8b4eb-f844-5eaa-a03d-9d58cdc74965",
  universalSettings: {
    relationType: RelationType.ONE_TO_MANY
  }
});
