// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "907f6268-2c7f-597a-9bd0-576d50091457",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "warehouse",
  label: "Warehouse",
  description: "(sync)",
  icon: "IconBuildingWarehouse",
  isNullable: true,
  options: [
    {
      id: "9fa05ed5-38f8-594b-b8c3-616650bcc533",
      color: "green",
      label: "Dubai Warehouse",
      value: "DUBAI_WAREHOUSE",
      position: 0
    },
    {
      id: "ab775971-ce40-506b-af34-137f9eaaddb5",
      color: "turquoise",
      label: "Other",
      value: "OTHER",
      position: 1
    }
  ]
});
