// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "b6780866-2da2-4085-b099-767dba25ff3d",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.SELECT,
  name: "warehouse",
  label: "Warehouse",
  description: "Expected serving warehouse — set during qualification; the Company mirrors the ERP's actual one after conversion",
  icon: "IconBuildingWarehouse",
  isNullable: true,
  options: [
    {
      id: "ded74d2d-d6ac-46be-9b03-c1fe7c6c4c7a",
      color: "green",
      label: "Dubai Warehouse",
      value: "DUBAI_WAREHOUSE",
      position: 0
    },
    {
      id: "41e3cdf5-d11b-4464-9ac5-12e47541c173",
      color: "turquoise",
      label: "Jeddah Warehouse",
      value: "JEDDAH_WAREHOUSE",
      position: 1
    },
    {
      id: "69b20eb6-b6a6-45cc-886e-23e38d70a929",
      color: "sky",
      label: "Dammam Warehouse",
      value: "DAMMAM_WAREHOUSE",
      position: 2
    },
    {
      id: "9df568ad-f19d-4ce7-922d-ebcea5132589",
      color: "blue",
      label: "Riyadh Warehouse",
      value: "RIYADH_WAREHOUSE",
      position: 3
    },
    {
      id: "27b6bfd9-3b7e-46fe-ba2e-24c426a07f0b",
      color: "purple",
      label: "Medina Warehouse",
      value: "MEDINA_WAREHOUSE",
      position: 4
    },
    {
      id: "e784be9f-7705-4d14-bcf7-f74f8ce748c2",
      color: "pink",
      label: "Qassim Warehouse",
      value: "QASSIM_WAREHOUSE",
      position: 5
    },
    {
      id: "dbc01ee4-41ed-44bf-a2c4-6b9e0ede8c51",
      color: "red",
      label: "Hail Warehouse",
      value: "HAIL_WAREHOUSE",
      position: 6
    },
    {
      id: "aaa61727-daed-40c8-9b0f-e199b93a833e",
      color: "orange",
      label: "Tabuk Warehouse",
      value: "TABUK_WAREHOUSE",
      position: 7
    },
    {
      id: "51901cca-021f-4ab8-ac29-cb36f2ca4038",
      color: "yellow",
      label: "Hafar Warehouse",
      value: "HAFAR_WAREHOUSE",
      position: 8
    },
    {
      id: "30d48c40-e374-49d5-b167-df25c3ad4283",
      color: "gray",
      label: "Jouf Warehouse",
      value: "JOUF_WAREHOUSE",
      position: 9
    },
    {
      id: "c86f45c5-750a-40d2-97a8-28843d4538ea",
      color: "green",
      label: "KSA National Hub",
      value: "KSA_NATIONAL_HUB",
      position: 10
    },
    {
      id: "0442f214-8411-454a-bd2a-92609219fdc5",
      color: "turquoise",
      label: "Jordan Warehouse",
      value: "JORDAN_WAREHOUSE",
      position: 11
    },
    {
      id: "71725e23-a251-4ba3-98b1-78f7c2f47c04",
      color: "sky",
      label: "Kuwait Warehouse",
      value: "KUWAIT_WAREHOUSE",
      position: 12
    },
    {
      id: "4a525179-6674-4bab-bed6-e070ced78f91",
      color: "blue",
      label: "Qatar Warehouse",
      value: "QATAR_WAREHOUSE",
      position: 13
    },
    {
      id: "678b0bb1-c635-42c1-a27f-537b6140bd0d",
      color: "turquoise",
      label: "Other",
      value: "OTHER",
      position: 14
    }
  ]
});
