// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "64cb0e7b-38db-527a-81bd-512a6594f402",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.DATE_TIME,
  name: "welcomeSentAt",
  label: "Welcome Sent At",
  icon: "IconClockCheck",
  isNullable: true
});
