// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "146438f1-bde0-56a2-b6c1-b1f98c140cf9",
  objectUniversalIdentifier: "20202020-e674-48e5-a542-72570eee7213" /* person */,
  type: FieldType.BOOLEAN,
  name: "whatsappCapable",
  label: "WhatsApp Capable",
  icon: "IconBrandWhatsapp",
  isNullable: true
});
