// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "4dc29438-84c7-4242-8045-4322f57466f4",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.SELECT,
  name: "winBackOutcome",
  label: "Win-Back Outcome",
  icon: "IconRotateClockwise",
  isNullable: true,
  options: [
    {
      id: "a98ed1cf-4b34-4c34-aeab-c8b9781591a1",
      color: "green",
      label: "Reactivated",
      value: "REACTIVATED",
      position: 0
    },
    {
      id: "e30a9319-782b-4836-8d72-d88834b5088b",
      color: "red",
      label: "Not Interested",
      value: "NOT_INTERESTED",
      position: 1
    },
    {
      id: "65f5bd99-1e06-4d56-9e98-fdd64ba8d525",
      color: "gray",
      label: "No Response",
      value: "NO_RESPONSE",
      position: 2
    },
    {
      id: "ba6db4ce-b154-4118-bf48-f5fafb8ac1ce",
      color: "yellow",
      label: "Pending",
      value: "PENDING",
      position: 3
    }
  ]
});
