// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "69198799-74c8-445f-b610-8184418dabcc",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: FieldType.DATE,
  name: "winBackAttemptAt",
  label: "Win-Back Attempt",
  icon: "IconRotate",
  isNullable: true
});
