// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, defineField } from 'twenty-sdk/define';

export default defineField({
  universalIdentifier: "4c255020-4376-41a7-9535-aeef0379540a",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: FieldType.SELECT,
  name: "yearsOperating",
  label: "Years Operating",
  icon: "IconHourglass",
  isNullable: true,
  options: [
    {
      id: "a32bcca4-6291-487d-9904-4b9d38064568",
      color: "sky",
      label: "New",
      value: "NEW",
      position: 0
    },
    {
      id: "67a9b6e3-00ca-4b11-9350-7ee745eb90ab",
      color: "green",
      label: "Growing (2 yrs)",
      value: "GROWING",
      position: 1
    },
    {
      id: "093a08a4-0306-4c5e-b1ad-dce03a4088fd",
      color: "blue",
      label: "Established (4+ yrs)",
      value: "ESTABLISHED",
      position: 2
    },
    {
      id: "953ae38b-648d-4db7-a1cf-dc2a01723fd9",
      color: "purple",
      label: "Legacy / Long-standing",
      value: "LEGACY",
      position: 3
    }
  ]
});
