// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineIndex } from 'twenty-sdk/define';

export default defineIndex({
  universalIdentifier: "30472353-0b3b-5430-9651-41f5a69f632a",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  indexType: "BTREE",
  isUnique: true,
  fields: [
    {
      universalIdentifier: "33639fdc-314a-5705-bf8b-ad6e46641d8d",
      fieldUniversalIdentifier: "1ea6631e-c368-5fc4-8854-805c8d5b5245"
    }
  ]
});
