// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineIndex } from 'twenty-sdk/define';

export default defineIndex({
  universalIdentifier: "b8b74a05-37f9-50f3-bc9f-8a85de389913",
  objectUniversalIdentifier: "aa860ef9-896f-5677-84f2-e69fefd3b630" /* orderEvent */,
  indexType: "BTREE",
  isUnique: true,
  fields: [
    {
      universalIdentifier: "bb9f175e-5080-59f1-b2c2-fc7ef9cbc600",
      fieldUniversalIdentifier: "d7b99b3f-156a-5f63-923f-f2faf3e91387"
    }
  ]
});
