export type BackgroundMockCompany = {
  id: string;
  name: string;
  domainName: string;
  createdBy: string | null;
  accountOwner: string | null;
  creationDate: string;
  employees: number;
  address: string;
};

export const BACKGROUND_MOCK_COMPANIES = [
  {
    id: 'royalfloraholland',
    name: 'Royal FloraHolland',
    domainName: 'royalfloraholland.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Lily Hart',
    creationDate: 'about 13 hours ago',
    employees: 3100,
    address: 'Aalsmeer',
  },
  {
    id: 'interflora',
    name: 'Interflora',
    domainName: 'interflora.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Iris Vale',
    creationDate: 'about 13 hours ago',
    employees: 2400,
    address: 'Sleaford',
  },
  {
    id: '1800flowers',
    name: '1-800-Flowers',
    domainName: '1800flowers.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Lily Hart',
    creationDate: 'about 13 hours ago',
    employees: 4300,
    address: 'Jericho',
  },
  {
    id: 'bloomandwild',
    name: 'Bloom & Wild',
    domainName: 'bloomandwild.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Jasmine Reed',
    creationDate: 'about 13 hours ago',
    employees: 320,
    address: 'London',
  },
  {
    id: 'thebouqs',
    name: 'The Bouqs Co.',
    domainName: 'bouqs.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Iris Vale',
    creationDate: 'about 13 hours ago',
    employees: 210,
    address: 'Marina del Rey',
  },
  {
    id: 'ftd',
    name: 'FTD Flowers',
    domainName: 'ftd.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Holly Fern',
    creationDate: 'about 13 hours ago',
    employees: 1600,
    address: 'Downers Grove',
  },
  {
    id: 'proflowers',
    name: 'ProFlowers',
    domainName: 'proflowers.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Lily Hart',
    creationDate: 'about 13 hours ago',
    employees: 540,
    address: 'San Diego',
  },
  {
    id: 'teleflora',
    name: 'Teleflora',
    domainName: 'teleflora.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Jasmine Reed',
    creationDate: 'about 13 hours ago',
    employees: 700,
    address: 'Los Angeles',
  },
  {
    id: 'floom',
    name: 'Floom',
    domainName: 'floom.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Iris Vale',
    creationDate: 'about 13 hours ago',
    employees: 95,
    address: 'London',
  },
  {
    id: 'urbanstems',
    name: 'UrbanStems',
    domainName: 'urbanstems.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Holly Fern',
    creationDate: 'about 13 hours ago',
    employees: 180,
    address: 'Washington',
  },
  {
    id: 'farmgirl',
    name: 'Farmgirl Flowers',
    domainName: 'farmgirlflowers.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Lily Hart',
    creationDate: 'about 13 hours ago',
    employees: 240,
    address: 'San Francisco',
  },
  {
    id: 'bloomnation',
    name: 'BloomNation',
    domainName: 'bloomnation.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Jasmine Reed',
    creationDate: 'about 13 hours ago',
    employees: 130,
    address: 'Santa Monica',
  },
  {
    id: 'petalsnetwork',
    name: 'Petals Network',
    domainName: 'petalsnetwork.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Iris Vale',
    creationDate: 'about 13 hours ago',
    employees: 160,
    address: 'Newcastle',
  },
  {
    id: 'serenata',
    name: 'Serenata Flowers',
    domainName: 'serenataflowers.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Holly Fern',
    creationDate: 'about 13 hours ago',
    employees: 110,
    address: 'London',
  },
  {
    id: 'flowerbx',
    name: 'FLOWERBX',
    domainName: 'flowerbx.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Lily Hart',
    creationDate: 'about 13 hours ago',
    employees: 85,
    address: 'London',
  },
  {
    id: 'bloomon',
    name: 'Bloomon',
    domainName: 'bloomon.co.uk',
    createdBy: 'Rose Bloom',
    accountOwner: 'Jasmine Reed',
    creationDate: 'about 13 hours ago',
    employees: 220,
    address: 'Amsterdam',
  },
  {
    id: 'freddies',
    name: "Freddie's Flowers",
    domainName: 'freddiesflowers.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Iris Vale',
    creationDate: 'about 13 hours ago',
    employees: 140,
    address: 'London',
  },
  {
    id: 'arena',
    name: 'Arena Flowers',
    domainName: 'arenaflowers.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Holly Fern',
    creationDate: 'about 13 hours ago',
    employees: 130,
    address: 'London',
  },
  {
    id: 'appleyard',
    name: 'Appleyard London',
    domainName: 'appleyardflowers.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Lily Hart',
    creationDate: 'about 13 hours ago',
    employees: 70,
    address: 'London',
  },
  {
    id: 'fiftyflowers',
    name: 'FiftyFlowers',
    domainName: 'fiftyflowers.com',
    createdBy: 'Rose Bloom',
    accountOwner: 'Jasmine Reed',
    creationDate: 'about 13 hours ago',
    employees: 95,
    address: 'Watsonville',
  },
] satisfies BackgroundMockCompany[];
