// Base64-encodes the marketplace's qualified-leads.xlsx into a TS module, so the
// export can inject rows into the real workbook instead of rebuilding it.
//
//   npx nx run twenty-front:lead-registration-template:generate
//
// Re-run this whenever the marketplace ships a new template, then commit both
// the .xlsx under scripts/lead-registration-data/ and the generated module.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const TEMPLATE_PATH = resolve(
  __dirname,
  './lead-registration-data/qualified-leads.xlsx',
);

const OUTPUT_PATH = resolve(
  __dirname,
  '../src/modules/object-record/record-index/export/generated/leadRegistrationTemplateBase64.ts',
);

const template = readFileSync(TEMPLATE_PATH);

const module = `// AUTO-GENERATED by scripts/generate-lead-registration-template.ts
// Do not edit by hand. Re-run the generator instead:
//   npx nx run twenty-front:lead-registration-template:generate
//
// The marketplace's qualified-leads.xlsx, base64-encoded. Rows are injected into
// this workbook so its Lists sheet, named ranges and dropdown validation survive
// the export untouched.
export const LEAD_REGISTRATION_TEMPLATE_BASE64 =
  '${template.toString('base64')}';
`;

writeFileSync(OUTPUT_PATH, module);

// eslint-disable-next-line no-console
console.log(
  `Wrote ${template.length} bytes of template as base64 to ${OUTPUT_PATH}`,
);
