// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "356681f0-9670-5b94-ba53-25213e781a56",
  name: "Collections Case Record Page Fields",
  objectUniversalIdentifier: "d9fc138e-e50c-5835-85c1-51793672be07" /* collectionsCase */,
  type: ViewType.FIELDS_WIDGET,
  icon: "IconList",
  position: 0,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "2aa6fd90-0989-5832-a125-ea1e39ba00c0",
      fieldMetadataUniversalIdentifier: "9c3dd4ac-ad02-5a27-93f7-b9a5be2d038d",
      isVisible: true,
      size: 218,
      position: 0
    },
    {
      universalIdentifier: "a1371b3d-531c-5cdf-9182-f9df05803303",
      fieldMetadataUniversalIdentifier: "2e39294c-31ad-542d-92d9-72db3421423a",
      isVisible: true,
      size: 150,
      position: 1
    },
    {
      universalIdentifier: "2f123464-6901-57fc-a6ba-b206c5a125ac",
      fieldMetadataUniversalIdentifier: "c7301e60-ccd6-5a42-926f-b6c6fbb37990",
      isVisible: true,
      size: 150,
      position: 2
    },
    {
      universalIdentifier: "079ff9ff-7816-5aa9-96f4-63363feb2f60",
      fieldMetadataUniversalIdentifier: "36c3a48b-6965-55e4-a57e-0b0463b76749",
      isVisible: true,
      size: 150,
      position: 3
    },
    {
      universalIdentifier: "cec4adad-d208-5176-8b4f-4312b12fc509",
      fieldMetadataUniversalIdentifier: "d3afd584-9c8e-50f7-8178-21aed1bf75c8",
      isVisible: true,
      size: 150,
      position: 4
    },
    {
      universalIdentifier: "6e835ae3-405f-5b99-b8e0-9c380cba8c6c",
      fieldMetadataUniversalIdentifier: "9cabea7e-69f7-5b06-8963-d9dd6d9f5132",
      isVisible: true,
      size: 150,
      position: 5
    },
    {
      universalIdentifier: "1147927c-4460-5c0c-b50e-19bb6cb3a186",
      fieldMetadataUniversalIdentifier: "19a820a1-aed5-5c20-925b-bb7430deb7b9",
      isVisible: true,
      size: 150,
      position: 6
    },
    {
      universalIdentifier: "e2e5ba1e-bb82-5654-b556-2682c1dec14e",
      fieldMetadataUniversalIdentifier: "e07425d4-b2d8-52b3-a39f-2b788abb4be6",
      isVisible: true,
      size: 150,
      position: 7
    },
    {
      universalIdentifier: "0127205e-7dc1-5a12-b64c-69e0516cb8aa",
      fieldMetadataUniversalIdentifier: "234b31a3-9f1e-5fe4-a701-a0751d8700a1",
      isVisible: true,
      size: 150,
      position: 8
    }
  ]
});
