// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { ViewKey, ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "ff1cb332-ff5d-52bb-9010-79a8c336d83a",
  name: "All {objectLabelPlural}",
  objectUniversalIdentifier: "d9fc138e-e50c-5835-85c1-51793672be07" /* collectionsCase */,
  type: ViewType.TABLE,
  key: ViewKey.INDEX,
  icon: "IconList",
  position: 0,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "8fb22a6d-f376-5189-b29c-fc6c22c48565",
      fieldMetadataUniversalIdentifier: "9c3dd4ac-ad02-5a27-93f7-b9a5be2d038d",
      isVisible: true,
      size: 218,
      position: 0
    },
    {
      universalIdentifier: "ebe457f7-687c-555a-8474-543d3740fe4a",
      fieldMetadataUniversalIdentifier: "2e39294c-31ad-542d-92d9-72db3421423a",
      isVisible: true,
      size: 150,
      position: 1
    },
    {
      universalIdentifier: "00d2f232-5b06-5347-8e55-77d5c047c7bf",
      fieldMetadataUniversalIdentifier: "c7301e60-ccd6-5a42-926f-b6c6fbb37990",
      isVisible: true,
      size: 150,
      position: 2
    },
    {
      universalIdentifier: "59f82243-6df7-5dc0-8cde-e76783674e86",
      fieldMetadataUniversalIdentifier: "36c3a48b-6965-55e4-a57e-0b0463b76749",
      isVisible: true,
      size: 150,
      position: 3
    },
    {
      universalIdentifier: "de3c70ac-0fb9-541d-af2e-bb48f816a81c",
      fieldMetadataUniversalIdentifier: "d3afd584-9c8e-50f7-8178-21aed1bf75c8",
      isVisible: true,
      size: 150,
      position: 4
    },
    {
      universalIdentifier: "42d40e56-0dc4-5953-826a-9effdef29eff",
      fieldMetadataUniversalIdentifier: "9cabea7e-69f7-5b06-8963-d9dd6d9f5132",
      isVisible: true,
      size: 150,
      position: 5
    },
    {
      universalIdentifier: "b3e4f123-4fc3-5b43-a2ed-90b2f2b0c33b",
      fieldMetadataUniversalIdentifier: "19a820a1-aed5-5c20-925b-bb7430deb7b9",
      isVisible: true,
      size: 150,
      position: 6
    },
    {
      universalIdentifier: "3ef70c31-381c-50a7-981e-0a6657bf2349",
      fieldMetadataUniversalIdentifier: "e07425d4-b2d8-52b3-a39f-2b788abb4be6",
      isVisible: true,
      size: 150,
      position: 7
    },
    {
      universalIdentifier: "e8620a3e-f540-5864-a141-d9a9822a8193",
      fieldMetadataUniversalIdentifier: "234b31a3-9f1e-5fe4-a701-a0751d8700a1",
      isVisible: true,
      size: 150,
      position: 8
    }
  ]
});
