// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { AggregateOperations, ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "d51faa31-37e6-4b13-a1ff-44936d1dd5aa",
  name: "All Companies",
  objectUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
  type: ViewType.TABLE,
  icon: "Table",
  position: 0,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "0ce6ac5d-314e-458b-89e5-327bcdcdb02c",
      fieldMetadataUniversalIdentifier: "20202020-4d99-4e2e-a84c-4a27837b1ece",
      isVisible: true,
      size: 180,
      position: 0
    },
    {
      universalIdentifier: "8a30bff8-3bbf-406a-8c20-74cfbf68a200",
      fieldMetadataUniversalIdentifier: "20202020-0c28-43d8-8ba5-3659924d3489",
      isVisible: true,
      size: 100,
      position: 1,
      aggregateOperation: AggregateOperations.COUNT
    },
    {
      universalIdentifier: "50df2bad-1826-40fd-b358-b76f893a2775",
      fieldMetadataUniversalIdentifier: "20202020-fabc-451d-ab7d-412170916baa",
      isVisible: true,
      size: 150,
      position: 2
    },
    {
      universalIdentifier: "1aafc5ef-db89-4372-8b71-da22507b8756",
      fieldMetadataUniversalIdentifier: "20202020-95b8-4e10-9881-edb5d4765f9d",
      isVisible: true,
      size: 150,
      position: 3
    },
    {
      universalIdentifier: "19571ebd-5520-4ce9-ba96-bb709446e2cd",
      fieldMetadataUniversalIdentifier: "20202020-c05b-4062-9b62-2f3a4b5c6d7e",
      isVisible: true,
      size: 150,
      position: 4
    },
    {
      universalIdentifier: "2e1eac44-8e58-4f19-9546-0fca7b0baff9",
      fieldMetadataUniversalIdentifier: "20202020-ebeb-4beb-b9ad-6848036fb451",
      isVisible: true,
      size: 170,
      position: 5,
      aggregateOperation: AggregateOperations.PERCENTAGE_EMPTY
    },
    {
      universalIdentifier: "3b3a9c66-2634-437f-aef7-05f874218caf",
      fieldMetadataUniversalIdentifier: "20202020-c5ce-4adc-b7b6-9c0979fc55e7",
      isVisible: true,
      size: 170,
      position: 6,
      aggregateOperation: AggregateOperations.COUNT_NOT_EMPTY
    },
    {
      universalIdentifier: "b9400a62-30d8-4b59-bb20-b159629fdc1a",
      fieldMetadataUniversalIdentifier: "ab2910a1-3e80-56ce-8732-193550e1e30a",
      isVisible: true,
      size: 100,
      position: 7
    }
  ]
});
