// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "7660ba37-8f57-5b5f-b10c-2811f97d79b6",
  name: "Incident Record Page Fields",
  objectUniversalIdentifier: "ab30bd09-9b3b-51be-b096-8554f631b30a" /* incident */,
  type: ViewType.FIELDS_WIDGET,
  icon: "IconList",
  position: 0,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "25b88735-0506-5d4e-b205-3735b224345a",
      fieldMetadataUniversalIdentifier: "6deea410-bb19-5d63-b3a1-a8381a097fc6",
      isVisible: true,
      size: 218,
      position: 0
    },
    {
      universalIdentifier: "4896df02-c17e-5866-b01e-fe74c1b9e2f1",
      fieldMetadataUniversalIdentifier: "ed0fd653-7b04-5ce6-90ad-c5f0758a81c5",
      isVisible: true,
      size: 150,
      position: 1
    },
    {
      universalIdentifier: "6d0245c4-b5b9-5c68-900a-718520e4a179",
      fieldMetadataUniversalIdentifier: "7bbbab9f-a02a-582c-86e9-71ef39b7befb",
      isVisible: true,
      size: 150,
      position: 2
    },
    {
      universalIdentifier: "40ac0fce-3164-535b-9a3d-f67a0f1f27f8",
      fieldMetadataUniversalIdentifier: "fc696a2f-fa74-5c02-afb6-aa3ecc786cc4",
      isVisible: true,
      size: 150,
      position: 3
    },
    {
      universalIdentifier: "aebe861f-33bf-5040-939d-3ddedf3edbcd",
      fieldMetadataUniversalIdentifier: "7e71d0cb-3e99-50f0-b729-16a78f0f058e",
      isVisible: true,
      size: 150,
      position: 4
    },
    {
      universalIdentifier: "d6dd26c4-7f36-58f5-bac1-f63fc13e7aed",
      fieldMetadataUniversalIdentifier: "8c345db3-b260-5307-83f0-b9c6c9cb8a20",
      isVisible: true,
      size: 150,
      position: 5
    },
    {
      universalIdentifier: "8c9f5948-e945-5d61-8e92-add44b00e9d1",
      fieldMetadataUniversalIdentifier: "69fbbab6-7cc0-5fe2-9512-30a46024259d",
      isVisible: true,
      size: 150,
      position: 6
    }
  ]
});
