// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { ViewKey, ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "d47530b1-201b-5965-97c9-c731a3d5fa0d",
  name: "All {objectLabelPlural}",
  objectUniversalIdentifier: "ab30bd09-9b3b-51be-b096-8554f631b30a" /* incident */,
  type: ViewType.TABLE,
  key: ViewKey.INDEX,
  icon: "IconList",
  position: 0,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "9fd929c9-25dc-5bdf-9269-b8a5cd70bc5e",
      fieldMetadataUniversalIdentifier: "6deea410-bb19-5d63-b3a1-a8381a097fc6",
      isVisible: true,
      size: 322,
      position: 0
    },
    {
      universalIdentifier: "d7222f54-387c-55f4-a9a4-f4c726432549",
      fieldMetadataUniversalIdentifier: "ed0fd653-7b04-5ce6-90ad-c5f0758a81c5",
      isVisible: true,
      size: 135,
      position: 1
    },
    {
      universalIdentifier: "de1f20ce-9b10-52e8-a1ff-9f61c136cd6a",
      fieldMetadataUniversalIdentifier: "7bbbab9f-a02a-582c-86e9-71ef39b7befb",
      isVisible: true,
      size: 104,
      position: 2
    },
    {
      universalIdentifier: "48bc8734-bb81-5028-bee3-14cc5414a9c1",
      fieldMetadataUniversalIdentifier: "fc696a2f-fa74-5c02-afb6-aa3ecc786cc4",
      isVisible: true,
      size: 105,
      position: 3
    },
    {
      universalIdentifier: "9f0a55b6-cdd0-59ec-9f1b-14e1ea27e0d4",
      fieldMetadataUniversalIdentifier: "7e71d0cb-3e99-50f0-b729-16a78f0f058e",
      isVisible: true,
      size: 176,
      position: 4
    },
    {
      universalIdentifier: "a7bbfd27-2108-5e1c-90f3-c0395ab9d0a5",
      fieldMetadataUniversalIdentifier: "8c345db3-b260-5307-83f0-b9c6c9cb8a20",
      isVisible: true,
      size: 139,
      position: 5
    },
    {
      universalIdentifier: "801a16e4-00eb-5f8b-9a4e-9295272a58b9",
      fieldMetadataUniversalIdentifier: "69fbbab6-7cc0-5fe2-9512-30a46024259d",
      isVisible: true,
      size: 150,
      position: 6
    }
  ]
});
