// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { ViewFilterOperand, ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "b0f05276-e79c-409a-8196-cdda28bff37d",
  name: "Awaiting Provisioning",
  objectUniversalIdentifier: "20202020-9549-49dd-b2b2-883999db8938" /* opportunity */,
  type: ViewType.TABLE,
  icon: "IconClockPlay",
  position: 10,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "9bebcc9b-33fd-4164-98b4-15ca8c0c3e76",
      fieldMetadataUniversalIdentifier: "20202020-8609-4f65-a2d9-44009eb422b5",
      isVisible: true,
      size: 180,
      position: 0
    },
    {
      universalIdentifier: "d6e3f426-30b0-4a78-af72-c9b3e1586a0a",
      fieldMetadataUniversalIdentifier: "c9dc1d2c-4868-4e95-b3a4-75dab649a5c1",
      isVisible: true,
      size: 140,
      position: 1
    },
    {
      universalIdentifier: "e312a92f-baf5-489b-bca6-d99d5218559b",
      fieldMetadataUniversalIdentifier: "c391f4c1-cae8-4463-9e7b-eb6965cd8cc3",
      isVisible: true,
      size: 180,
      position: 2
    },
    {
      universalIdentifier: "4551103d-ceae-4c01-b5c0-026d1752c535",
      fieldMetadataUniversalIdentifier: "20202020-6f76-477d-8551-28cd65b2b4b9",
      isVisible: true,
      size: 120,
      position: 3
    },
    {
      universalIdentifier: "f9d0e18f-3fb7-4178-91b1-5b6a417b7195",
      fieldMetadataUniversalIdentifier: "20202020-be7e-4d1e-8e19-3d5c7c4b9f2a",
      isVisible: true,
      size: 150,
      position: 4
    },
    {
      universalIdentifier: "3983d836-1dee-413a-a422-fe3ea8dbefdc",
      fieldMetadataUniversalIdentifier: "20202020-8dfb-42fc-92b6-01afb759ed16",
      isVisible: true,
      size: 170,
      position: 5
    },
    {
      universalIdentifier: "54ad8ab5-443a-4275-877b-3d7166212a30",
      fieldMetadataUniversalIdentifier: "a730b7c7-1ffa-4158-a5b3-b15a8e8cd243",
      isVisible: true,
      size: 110,
      position: 6
    },
    {
      universalIdentifier: "c3194bf8-d1bc-4737-8874-6ede4c748d0d",
      fieldMetadataUniversalIdentifier: "ec5127b6-834f-4a3b-a577-e5b27eeb6396",
      isVisible: true,
      size: 100,
      position: 7
    }
  ],
  filters: [
    {
      universalIdentifier: "cbe69196-d945-4ef0-97f0-09bd65abd2d3",
      fieldMetadataUniversalIdentifier: "20202020-6f76-477d-8551-28cd65b2b4b9",
      operand: ViewFilterOperand.IS,
      value: [
        "QUALIFIED"
      ]
    },
    {
      universalIdentifier: "7dce215f-c598-4fb3-892c-c254720e4161",
      fieldMetadataUniversalIdentifier: "c9dc1d2c-4868-4e95-b3a4-75dab649a5c1",
      operand: ViewFilterOperand.IS_NOT_EMPTY,
      value: []
    },
    {
      universalIdentifier: "9a09d113-cde0-4eb4-a243-85f2f0c5d3b1",
      fieldMetadataUniversalIdentifier: "20202020-cbac-457e-b565-adece5fc815f",
      operand: ViewFilterOperand.IS_EMPTY,
      value: []
    }
  ]
});
