// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { ViewKey, ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "022f4d58-fbac-5a47-9dff-d0b31ae697c2",
  name: "All {objectLabelPlural}",
  objectUniversalIdentifier: "aa860ef9-896f-5677-84f2-e69fefd3b630" /* orderEvent */,
  type: ViewType.TABLE,
  key: ViewKey.INDEX,
  icon: "IconList",
  position: 0,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "4dd493f4-671d-52cf-a631-726e01a11ba7",
      fieldMetadataUniversalIdentifier: "9a54ddfa-1da5-5d83-a95a-2b00108f26f4",
      isVisible: true,
      size: 218,
      position: 0
    },
    {
      universalIdentifier: "66b4f91c-d484-59d0-a004-f80b611d61e0",
      fieldMetadataUniversalIdentifier: "d7b99b3f-156a-5f63-923f-f2faf3e91387",
      isVisible: true,
      size: 150,
      position: 1
    },
    {
      universalIdentifier: "ec3f8bc6-80d0-5bee-9ed8-3eefc45f258a",
      fieldMetadataUniversalIdentifier: "56d16a71-6c16-5d7c-9965-0aa1e56e2d2c",
      isVisible: true,
      size: 150,
      position: 2
    },
    {
      universalIdentifier: "364513a6-9bd7-5d32-a21e-bfa0fa491361",
      fieldMetadataUniversalIdentifier: "2911bb99-8b6a-5463-9f2b-e02262e2ed04",
      isVisible: true,
      size: 150,
      position: 3
    },
    {
      universalIdentifier: "f26c19b8-2183-5f39-9291-acec988cd7f8",
      fieldMetadataUniversalIdentifier: "e5e50924-e135-545e-8219-b076f09f0d8d",
      isVisible: true,
      size: 150,
      position: 4
    },
    {
      universalIdentifier: "b701f510-3e5d-5b94-bc92-6d6ff0830a26",
      fieldMetadataUniversalIdentifier: "3c6900fb-8654-5a19-a547-9cd8f0ec1371",
      isVisible: true,
      size: 150,
      position: 5
    },
    {
      universalIdentifier: "309bb905-7841-5a5d-be86-b59c4b12e095",
      fieldMetadataUniversalIdentifier: "cf6bf150-41bf-5253-8cb1-c5117a92ee6d",
      isVisible: true,
      size: 150,
      position: 6
    },
    {
      universalIdentifier: "b1c2aeb7-d2b9-5b56-95a0-fbb1cc30ada4",
      fieldMetadataUniversalIdentifier: "11d6a526-7e7b-54ca-aff9-f59690d1913b",
      isVisible: true,
      size: 150,
      position: 7
    },
    {
      universalIdentifier: "bdd695b3-046c-551b-bd90-7f21528eaabf",
      fieldMetadataUniversalIdentifier: "fcfc3a60-71e7-57c4-a9aa-8e06273c9f7b",
      isVisible: true,
      size: 150,
      position: 8
    },
    {
      universalIdentifier: "e79cf09a-931e-577d-828c-f9124b05e88d",
      fieldMetadataUniversalIdentifier: "12b1bf98-0567-5e64-bb58-fa98770ce6c6",
      isVisible: false,
      size: 150,
      position: 9
    },
    {
      universalIdentifier: "75b9e10d-4a43-53c3-8910-acdab3935168",
      fieldMetadataUniversalIdentifier: "33837ab2-de86-5ab0-95c0-115b1c059c8c",
      isVisible: false,
      size: 150,
      position: 10
    },
    {
      universalIdentifier: "ec3a93ad-e953-5e74-928c-f3f2e78d8df6",
      fieldMetadataUniversalIdentifier: "97373cf8-fdc7-59ae-b3cd-b7004bf35cdb",
      isVisible: false,
      size: 150,
      position: 11
    },
    {
      universalIdentifier: "6152b82f-c49c-592a-a568-1bdcabae6c24",
      fieldMetadataUniversalIdentifier: "e0b467fd-d2dc-554f-bfc5-8cd258af666f",
      isVisible: false,
      size: 150,
      position: 12
    }
  ]
});
