// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "cdfd72fe-f1e1-5d40-bb30-506cf57cfadc",
  name: "Order Event Record Page Fields",
  objectUniversalIdentifier: "aa860ef9-896f-5677-84f2-e69fefd3b630" /* orderEvent */,
  type: ViewType.FIELDS_WIDGET,
  icon: "IconList",
  position: 0,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "2aaf3510-cf13-55d7-a845-ea51380f7015",
      fieldMetadataUniversalIdentifier: "9a54ddfa-1da5-5d83-a95a-2b00108f26f4",
      isVisible: true,
      size: 218,
      position: 0
    },
    {
      universalIdentifier: "9cb833a2-c493-5f7c-b849-e919199d85e8",
      fieldMetadataUniversalIdentifier: "d7b99b3f-156a-5f63-923f-f2faf3e91387",
      isVisible: true,
      size: 150,
      position: 1
    },
    {
      universalIdentifier: "f986a66d-fdcc-5e03-aa47-1dc89badc287",
      fieldMetadataUniversalIdentifier: "56d16a71-6c16-5d7c-9965-0aa1e56e2d2c",
      isVisible: true,
      size: 150,
      position: 2
    },
    {
      universalIdentifier: "e562cace-719f-5f28-8032-c91f2b9c66a4",
      fieldMetadataUniversalIdentifier: "2911bb99-8b6a-5463-9f2b-e02262e2ed04",
      isVisible: true,
      size: 150,
      position: 3
    },
    {
      universalIdentifier: "bdf2c5d7-ad27-5cec-83b6-2b6344d55027",
      fieldMetadataUniversalIdentifier: "e5e50924-e135-545e-8219-b076f09f0d8d",
      isVisible: true,
      size: 150,
      position: 4
    },
    {
      universalIdentifier: "ffd0a8e9-f0ee-51be-86eb-8b5f222bd317",
      fieldMetadataUniversalIdentifier: "3c6900fb-8654-5a19-a547-9cd8f0ec1371",
      isVisible: true,
      size: 150,
      position: 5
    },
    {
      universalIdentifier: "a3508c6c-5064-5def-b548-7b68c15aa87b",
      fieldMetadataUniversalIdentifier: "cf6bf150-41bf-5253-8cb1-c5117a92ee6d",
      isVisible: true,
      size: 150,
      position: 6
    },
    {
      universalIdentifier: "bae7b0bc-ee16-5a0b-b06e-d0a5f67aa332",
      fieldMetadataUniversalIdentifier: "11d6a526-7e7b-54ca-aff9-f59690d1913b",
      isVisible: true,
      size: 150,
      position: 7
    },
    {
      universalIdentifier: "03ba60df-1f13-538b-885f-dd7b96b4e262",
      fieldMetadataUniversalIdentifier: "fcfc3a60-71e7-57c4-a9aa-8e06273c9f7b",
      isVisible: true,
      size: 150,
      position: 8
    },
    {
      universalIdentifier: "90b53945-0f9a-53ee-9491-0232f2d80a2c",
      fieldMetadataUniversalIdentifier: "12b1bf98-0567-5e64-bb58-fa98770ce6c6",
      isVisible: true,
      size: 150,
      position: 9
    },
    {
      universalIdentifier: "878d0d52-f35e-5f44-aca2-a59b77f4e7ec",
      fieldMetadataUniversalIdentifier: "33837ab2-de86-5ab0-95c0-115b1c059c8c",
      isVisible: true,
      size: 150,
      position: 10
    },
    {
      universalIdentifier: "f79944d0-e098-5b94-b2aa-c9cd37cc2eac",
      fieldMetadataUniversalIdentifier: "97373cf8-fdc7-59ae-b3cd-b7004bf35cdb",
      isVisible: true,
      size: 150,
      position: 11
    },
    {
      universalIdentifier: "8b51799c-20c4-5bcd-b475-152f506a5a31",
      fieldMetadataUniversalIdentifier: "e0b467fd-d2dc-554f-bfc5-8cd258af666f",
      isVisible: true,
      size: 150,
      position: 12
    }
  ]
});
