// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "53c60388-6868-52c3-9e91-5cc3e781170f",
  name: "Payment Promise Record Page Fields",
  objectUniversalIdentifier: "730c3de2-6bc0-501d-bbde-d81453da11d2" /* paymentPromise */,
  type: ViewType.FIELDS_WIDGET,
  icon: "IconList",
  position: 0,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "26562d9e-448e-58db-ab23-658e8fb1a7d2",
      fieldMetadataUniversalIdentifier: "36384360-7260-500d-bedf-cc627fa9a37e",
      isVisible: true,
      size: 218,
      position: 0
    },
    {
      universalIdentifier: "d6e250d9-8d79-5302-aced-a79640bb5dfc",
      fieldMetadataUniversalIdentifier: "24066e74-0a78-5f7a-8e92-24a4ade517b3",
      isVisible: true,
      size: 150,
      position: 1
    },
    {
      universalIdentifier: "60fb91f0-3a2b-5a04-92eb-274cec93382e",
      fieldMetadataUniversalIdentifier: "0b3da37a-d448-5774-b5d0-514477f18815",
      isVisible: true,
      size: 150,
      position: 2
    },
    {
      universalIdentifier: "07eb2930-d460-566a-9a22-a375e747a4df",
      fieldMetadataUniversalIdentifier: "9f4e0247-c5cb-5034-92ae-693aa2dd51b0",
      isVisible: true,
      size: 150,
      position: 3
    },
    {
      universalIdentifier: "4611d57e-8673-59db-b098-e00b40e56d3b",
      fieldMetadataUniversalIdentifier: "59e1682f-fb02-5883-8ed5-f47e2d9f4b0c",
      isVisible: true,
      size: 150,
      position: 4
    },
    {
      universalIdentifier: "dc68fbd3-1431-59eb-a182-4781ce220cb0",
      fieldMetadataUniversalIdentifier: "10b0718a-06c7-525f-b848-6bfc55461c67",
      isVisible: true,
      size: 150,
      position: 5
    }
  ]
});
