// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { ViewKey, ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "b2deb78a-e3f3-517b-9277-f8931b519446",
  name: "All {objectLabelPlural}",
  objectUniversalIdentifier: "730c3de2-6bc0-501d-bbde-d81453da11d2" /* paymentPromise */,
  type: ViewType.TABLE,
  key: ViewKey.INDEX,
  icon: "IconList",
  position: 0,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "57062e7f-0e3c-5553-b144-456f9b0dd3be",
      fieldMetadataUniversalIdentifier: "36384360-7260-500d-bedf-cc627fa9a37e",
      isVisible: true,
      size: 218,
      position: 0
    },
    {
      universalIdentifier: "bdb4a35d-00ef-530b-a85b-ee9fd92599a9",
      fieldMetadataUniversalIdentifier: "24066e74-0a78-5f7a-8e92-24a4ade517b3",
      isVisible: true,
      size: 150,
      position: 1
    },
    {
      universalIdentifier: "76607eb4-9c21-5fe6-9e4e-c45947e86e1f",
      fieldMetadataUniversalIdentifier: "0b3da37a-d448-5774-b5d0-514477f18815",
      isVisible: true,
      size: 150,
      position: 2
    },
    {
      universalIdentifier: "808dff34-5e81-5a34-8757-87af43c837cc",
      fieldMetadataUniversalIdentifier: "9f4e0247-c5cb-5034-92ae-693aa2dd51b0",
      isVisible: true,
      size: 150,
      position: 3
    },
    {
      universalIdentifier: "d310d2ee-efc7-5002-9557-77477f15a611",
      fieldMetadataUniversalIdentifier: "59e1682f-fb02-5883-8ed5-f47e2d9f4b0c",
      isVisible: true,
      size: 150,
      position: 4
    },
    {
      universalIdentifier: "83896eb1-4c66-58f3-a5d8-44e165aea17e",
      fieldMetadataUniversalIdentifier: "10b0718a-06c7-525f-b848-6bfc55461c67",
      isVisible: true,
      size: 150,
      position: 5
    }
  ]
});
