// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "cf66a022-0285-5bdf-9442-371ff9f7ba6b",
  name: "Standing Order Record Page Fields",
  objectUniversalIdentifier: "1d2f5ca4-4d73-5f46-9a86-118e41a67839" /* standingOrder */,
  type: ViewType.FIELDS_WIDGET,
  icon: "IconList",
  position: 0,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "8e36c46c-4935-5a75-8a5a-a00c667d5bb5",
      fieldMetadataUniversalIdentifier: "b4d63e96-2869-5b55-b7de-add813581c2b",
      isVisible: true,
      size: 218,
      position: 0
    },
    {
      universalIdentifier: "4e21b19c-1b61-5c29-89e1-eee0644d966d",
      fieldMetadataUniversalIdentifier: "7b560719-fdcf-597c-a9d3-6cc822a945ea",
      isVisible: true,
      size: 150,
      position: 1
    },
    {
      universalIdentifier: "eef25402-4061-5db2-983a-6b385f6cf62b",
      fieldMetadataUniversalIdentifier: "b69bc0c6-0943-592b-8dc2-64c37766822f",
      isVisible: true,
      size: 150,
      position: 2
    },
    {
      universalIdentifier: "3ad1d595-8c85-5411-bf71-6cc310b44228",
      fieldMetadataUniversalIdentifier: "1368fb6f-37a4-5b1d-9c04-6039c8bddd8a",
      isVisible: true,
      size: 150,
      position: 3
    },
    {
      universalIdentifier: "1fd93929-1f20-5a96-8b0a-b85c0f7c2f3a",
      fieldMetadataUniversalIdentifier: "9732c019-ce03-5398-b74f-1c76e3aeacaa",
      isVisible: true,
      size: 150,
      position: 4
    },
    {
      universalIdentifier: "9590b798-759c-5f3d-b8a5-1d687d1525c3",
      fieldMetadataUniversalIdentifier: "c56476a5-d2ca-5bd5-82cf-4a59739dfef7",
      isVisible: true,
      size: 150,
      position: 5
    },
    {
      universalIdentifier: "1229f512-3787-53f6-88e0-a28187efaff7",
      fieldMetadataUniversalIdentifier: "2478ad60-e3b5-52ba-862b-9d139d48ff88",
      isVisible: true,
      size: 150,
      position: 6
    },
    {
      universalIdentifier: "8ffd086c-8384-5dc7-8f88-f9727b05ec44",
      fieldMetadataUniversalIdentifier: "dc04d700-60e2-57bb-b423-93b2d06be1ff",
      isVisible: true,
      size: 150,
      position: 7
    },
    {
      universalIdentifier: "00829465-9ac8-560a-8364-8fec74a9b464",
      fieldMetadataUniversalIdentifier: "2f145325-8312-5908-bc7d-f2e1e0d9d387",
      isVisible: true,
      size: 150,
      position: 8
    }
  ]
});
