// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { ViewKey, ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "cb213d09-84bf-5c83-84b1-574e1945a47b",
  name: "All {objectLabelPlural}",
  objectUniversalIdentifier: "1d2f5ca4-4d73-5f46-9a86-118e41a67839" /* standingOrder */,
  type: ViewType.TABLE,
  key: ViewKey.INDEX,
  icon: "IconList",
  position: 0,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "4c0fc1ff-3258-54d2-9813-79de536a246b",
      fieldMetadataUniversalIdentifier: "b4d63e96-2869-5b55-b7de-add813581c2b",
      isVisible: true,
      size: 218,
      position: 0
    },
    {
      universalIdentifier: "77495d97-c25f-51af-b502-ee5d5f58d737",
      fieldMetadataUniversalIdentifier: "7b560719-fdcf-597c-a9d3-6cc822a945ea",
      isVisible: true,
      size: 150,
      position: 1
    },
    {
      universalIdentifier: "062f9bcf-54c9-5297-9d45-c18f9e332092",
      fieldMetadataUniversalIdentifier: "b69bc0c6-0943-592b-8dc2-64c37766822f",
      isVisible: true,
      size: 150,
      position: 2
    },
    {
      universalIdentifier: "64616f10-aae8-56db-87a1-7647e9994991",
      fieldMetadataUniversalIdentifier: "1368fb6f-37a4-5b1d-9c04-6039c8bddd8a",
      isVisible: true,
      size: 150,
      position: 3
    },
    {
      universalIdentifier: "6b8c6fcf-d24d-50ef-9048-a088b14ba5ea",
      fieldMetadataUniversalIdentifier: "9732c019-ce03-5398-b74f-1c76e3aeacaa",
      isVisible: true,
      size: 150,
      position: 4
    },
    {
      universalIdentifier: "44c16e6d-92cc-5945-81cc-85a8f32fcb7b",
      fieldMetadataUniversalIdentifier: "c56476a5-d2ca-5bd5-82cf-4a59739dfef7",
      isVisible: true,
      size: 150,
      position: 5
    },
    {
      universalIdentifier: "e7bbbfdd-ec9f-5ed1-a7b1-758b0c95f9df",
      fieldMetadataUniversalIdentifier: "2478ad60-e3b5-52ba-862b-9d139d48ff88",
      isVisible: true,
      size: 150,
      position: 6
    },
    {
      universalIdentifier: "4edaa5e1-bd08-55e0-a90f-6ec2b43de092",
      fieldMetadataUniversalIdentifier: "dc04d700-60e2-57bb-b423-93b2d06be1ff",
      isVisible: true,
      size: 150,
      position: 7
    },
    {
      universalIdentifier: "931f519f-97fa-5d5d-9bd4-d52a88f134f7",
      fieldMetadataUniversalIdentifier: "2f145325-8312-5908-bc7d-f2e1e0d9d387",
      isVisible: true,
      size: 150,
      position: 8
    }
  ]
});
