// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "7f089831-ec3e-5e33-89e3-f1e23526b666",
  name: "Visit Record Page Fields",
  objectUniversalIdentifier: "80155072-b338-5bd5-b7f7-2dde833c8c3e" /* visit */,
  type: ViewType.FIELDS_WIDGET,
  icon: "IconList",
  position: 0,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "8af1245a-aca0-5768-8de2-53d47fcccc93",
      fieldMetadataUniversalIdentifier: "a046ed79-e891-56da-bc3c-4322d979bb9f",
      isVisible: true,
      size: 218,
      position: 0
    },
    {
      universalIdentifier: "19a4563a-ca52-5874-abfd-e57f486f1416",
      fieldMetadataUniversalIdentifier: "2084f58e-b6fc-55f7-8c0f-a1b3afe36022",
      isVisible: true,
      size: 150,
      position: 1
    },
    {
      universalIdentifier: "a47fb80c-218f-595e-afb7-145b78f57eba",
      fieldMetadataUniversalIdentifier: "48c96d55-a25c-52e2-9e7d-f73b8cd4b63d",
      isVisible: true,
      size: 150,
      position: 2
    },
    {
      universalIdentifier: "9034cf2d-3d87-56ab-919c-ff12609cf93b",
      fieldMetadataUniversalIdentifier: "c389b240-c536-5e82-94be-5fd71596f320",
      isVisible: true,
      size: 150,
      position: 3
    },
    {
      universalIdentifier: "96ad04fa-19ce-5bcc-9963-1bebda38b0fc",
      fieldMetadataUniversalIdentifier: "585af935-d352-5f01-a3ae-b2ae701af210",
      isVisible: true,
      size: 150,
      position: 4
    },
    {
      universalIdentifier: "1c02dd58-10f8-574d-81e7-45018eb54f66",
      fieldMetadataUniversalIdentifier: "f79174d4-1d0d-59c1-b18d-71b56887f208",
      isVisible: true,
      size: 150,
      position: 5
    },
    {
      universalIdentifier: "a4da5220-bef5-5e8a-ba03-67845ad21b6b",
      fieldMetadataUniversalIdentifier: "4613dd6d-5f78-5ac7-9528-51c2e691da02",
      isVisible: true,
      size: 150,
      position: 6
    },
    {
      universalIdentifier: "9915f9f0-cb1b-5ef7-a329-329f9475b4f3",
      fieldMetadataUniversalIdentifier: "23c8a3a7-0501-5864-8268-a110cc0f5c60",
      isVisible: true,
      size: 150,
      position: 7
    },
    {
      universalIdentifier: "82350bc9-ee3a-55ad-8cc2-970be0c1c3be",
      fieldMetadataUniversalIdentifier: "7057549a-8e13-5308-989e-2ad62871236f",
      isVisible: true,
      size: 150,
      position: 8
    },
    {
      universalIdentifier: "33dcbfb1-4649-5fca-83dd-ce3d6c82c83d",
      fieldMetadataUniversalIdentifier: "3f7ae80f-03da-54aa-a810-8a2dd468ce8c",
      isVisible: true,
      size: 150,
      position: 9
    },
    {
      universalIdentifier: "510ef120-9dd5-5949-8a47-3504653e8e0a",
      fieldMetadataUniversalIdentifier: "3e5383a4-a720-5742-ad5a-da802a3323ac",
      isVisible: true,
      size: 150,
      position: 10
    },
    {
      universalIdentifier: "2701d2e9-2343-5ccd-abbc-ff5ac42b7ac6",
      fieldMetadataUniversalIdentifier: "2aa43a91-a4f5-5314-9af4-22967857607b",
      isVisible: true,
      size: 150,
      position: 11
    },
    {
      universalIdentifier: "6f42c2dc-197f-5ff1-bfaf-1f28d0e944bb",
      fieldMetadataUniversalIdentifier: "084705d3-99fa-5f46-bc0f-9b53032f39f4",
      isVisible: true,
      size: 150,
      position: 12
    },
    {
      universalIdentifier: "f7dc23ef-2035-5c9c-aa04-164812c2fe42",
      fieldMetadataUniversalIdentifier: "7f56457e-4e23-5bff-9c87-fc40244dd4d7",
      isVisible: true,
      size: 150,
      position: 13
    },
    {
      universalIdentifier: "15d4baf5-8a37-5b2b-a483-f11856c476d1",
      fieldMetadataUniversalIdentifier: "9b18c1ac-59c2-558f-bc56-f4b957d466cd",
      isVisible: true,
      size: 150,
      position: 14
    },
    {
      universalIdentifier: "55af1f68-3ef0-5c78-af6b-05370511d9c3",
      fieldMetadataUniversalIdentifier: "a42db3f7-d14f-5372-b242-5d4b0263a02b",
      isVisible: true,
      size: 150,
      position: 15
    }
  ]
});
