// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { ViewKey, ViewOpenRecordIn, ViewType, ViewVisibility, defineView } from 'twenty-sdk/define';

export default defineView({
  universalIdentifier: "022f16ac-d0e1-5948-b7d8-c96c9091b4b1",
  name: "All {objectLabelPlural}",
  objectUniversalIdentifier: "80155072-b338-5bd5-b7f7-2dde833c8c3e" /* visit */,
  type: ViewType.TABLE,
  key: ViewKey.INDEX,
  icon: "IconList",
  position: 0,
  isCompact: false,
  visibility: ViewVisibility.WORKSPACE,
  openRecordIn: ViewOpenRecordIn.SIDE_PANEL,
  shouldHideEmptyGroups: false,
  fields: [
    {
      universalIdentifier: "b709d308-8d41-5f15-b832-9e48aea0b8a7",
      fieldMetadataUniversalIdentifier: "a046ed79-e891-56da-bc3c-4322d979bb9f",
      isVisible: true,
      size: 218,
      position: 0
    },
    {
      universalIdentifier: "b44800e1-d7e0-5669-a9af-12fc62d2283f",
      fieldMetadataUniversalIdentifier: "2084f58e-b6fc-55f7-8c0f-a1b3afe36022",
      isVisible: true,
      size: 150,
      position: 1
    },
    {
      universalIdentifier: "f0ebfa69-2cf5-5023-be80-12634ad6e2dd",
      fieldMetadataUniversalIdentifier: "48c96d55-a25c-52e2-9e7d-f73b8cd4b63d",
      isVisible: true,
      size: 150,
      position: 2
    },
    {
      universalIdentifier: "d4f3e061-c06f-5583-9e85-9a125ed8884c",
      fieldMetadataUniversalIdentifier: "c389b240-c536-5e82-94be-5fd71596f320",
      isVisible: true,
      size: 150,
      position: 3
    },
    {
      universalIdentifier: "4b78fc03-8970-5da2-8879-3cd14f617d6c",
      fieldMetadataUniversalIdentifier: "585af935-d352-5f01-a3ae-b2ae701af210",
      isVisible: true,
      size: 150,
      position: 4
    },
    {
      universalIdentifier: "88963cbe-6255-5a2f-b838-b7dc55b42d1f",
      fieldMetadataUniversalIdentifier: "f79174d4-1d0d-59c1-b18d-71b56887f208",
      isVisible: true,
      size: 150,
      position: 5
    },
    {
      universalIdentifier: "bb678a7a-40a3-5da5-9933-363f770c5a81",
      fieldMetadataUniversalIdentifier: "4613dd6d-5f78-5ac7-9528-51c2e691da02",
      isVisible: true,
      size: 150,
      position: 6
    },
    {
      universalIdentifier: "f9d1d666-8f17-5bcb-a33b-63d48fff4a73",
      fieldMetadataUniversalIdentifier: "23c8a3a7-0501-5864-8268-a110cc0f5c60",
      isVisible: true,
      size: 150,
      position: 7
    },
    {
      universalIdentifier: "2134fb26-bf03-5d31-beca-a853335db206",
      fieldMetadataUniversalIdentifier: "7057549a-8e13-5308-989e-2ad62871236f",
      isVisible: true,
      size: 150,
      position: 8
    },
    {
      universalIdentifier: "2f32e343-c2a8-561f-b49d-30454b0383de",
      fieldMetadataUniversalIdentifier: "3f7ae80f-03da-54aa-a810-8a2dd468ce8c",
      isVisible: false,
      size: 150,
      position: 9
    },
    {
      universalIdentifier: "ccea57fd-2feb-505e-9f53-f607b922f8c4",
      fieldMetadataUniversalIdentifier: "3e5383a4-a720-5742-ad5a-da802a3323ac",
      isVisible: false,
      size: 150,
      position: 10
    },
    {
      universalIdentifier: "fb640f1a-ade1-5ec3-8224-ac4326efd17f",
      fieldMetadataUniversalIdentifier: "2aa43a91-a4f5-5314-9af4-22967857607b",
      isVisible: false,
      size: 150,
      position: 11
    },
    {
      universalIdentifier: "3909e6c0-fd61-5cce-ae34-aeef9e4bc9a1",
      fieldMetadataUniversalIdentifier: "084705d3-99fa-5f46-bc0f-9b53032f39f4",
      isVisible: false,
      size: 150,
      position: 12
    },
    {
      universalIdentifier: "1b6081c8-c77e-5781-a8d9-c7dd1f2dfabe",
      fieldMetadataUniversalIdentifier: "7f56457e-4e23-5bff-9c87-fc40244dd4d7",
      isVisible: false,
      size: 150,
      position: 13
    },
    {
      universalIdentifier: "7ec04a3d-c307-59b2-8cf7-50bb86b5ca12",
      fieldMetadataUniversalIdentifier: "9b18c1ac-59c2-558f-bc56-f4b957d466cd",
      isVisible: false,
      size: 150,
      position: 14
    },
    {
      universalIdentifier: "8a62597c-dcc6-545d-979e-6defbeedf104",
      fieldMetadataUniversalIdentifier: "a42db3f7-d14f-5372-b242-5d4b0263a02b",
      isVisible: false,
      size: 150,
      position: 15
    },
    {
      universalIdentifier: "ad8e23c2-f68b-483d-9eb1-8616405e1924",
      fieldMetadataUniversalIdentifier: "1ad8b4eb-f844-5eaa-a03d-9d58cdc74965",
      isVisible: true,
      size: 100,
      position: 16
    }
  ]
});
