// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "cb8090da-2451-4a80-988e-6f09bad4788a",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "ab2fd4ee-e098-58ab-9e2d-b37674758415",
  isVisible: true,
  size: 150,
  position: 0
});
