// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "a56e7740-8902-4860-b3e8-69383cf90dd2",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "a9c56b73-af40-5199-a20f-7ccf0b2a216a",
  isVisible: true,
  size: 150,
  position: 9
});
