// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "1a45ba3c-0f39-46cf-b95a-c4b56aa05acf",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "ab2910a1-3e80-56ce-8732-193550e1e30a",
  isVisible: true,
  size: 150,
  position: 4
});
