// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "661e1ba3-67e1-4f44-8cbe-d1c23802558b",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c0001" /* company / All {objectLabelPlural} */,
  fieldMetadataUniversalIdentifier: "ab2910a1-3e80-56ce-8732-193550e1e30a",
  isVisible: true,
  size: 100,
  position: 7
});
