// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "44248292-88d7-4d71-9ed2-8eb9944fb91f",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "dc14a0b9-2add-58e8-a833-a5e5ee205914",
  isVisible: true,
  size: 150,
  position: 3
});
