// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "c58ad55c-31ce-4180-97ab-e63c8797c8e9",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca3001" /* opportunity / Opportunity Record Page Fields */,
  fieldMetadataUniversalIdentifier: "95a4ea1e-9de5-4ab3-be1c-328bcb4dc9f9",
  isVisible: true,
  size: 180,
  position: 1
});
