// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "71b89141-7ed5-4da4-a287-7603178438f6",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "97c9f266-01a4-5bff-a35c-e5a2037d5593",
  isVisible: true,
  size: 150,
  position: 2
});
