// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "d21d061a-b6c9-4806-967e-bd7d86ba33bf",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca3001" /* opportunity / Opportunity Record Page Fields */,
  fieldMetadataUniversalIdentifier: "c391f4c1-cae8-4463-9e7b-eb6965cd8cc3",
  isVisible: true,
  size: 180,
  position: 0
});
