// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "0d827b0b-fd6f-42ed-9e9e-c454d1965cf3",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca3001" /* opportunity / Opportunity Record Page Fields */,
  fieldMetadataUniversalIdentifier: "a730b7c7-1ffa-4158-a5b3-b15a8e8cd243",
  isVisible: true,
  size: 180,
  position: 3
});
