// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "06ee88f0-e47b-42c0-ab9d-451461e2410b",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "8aa9ae46-80c8-51f3-b7e8-f4feb9f23ab5",
  isVisible: true,
  size: 150,
  position: 3
});
