// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "cde4cf8b-0ba5-4d4a-bf9a-7699fb30e3a7",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "e6741110-d9a5-5240-b2ce-5a09423b0c9e",
  isVisible: true,
  size: 150,
  position: 2
});
