// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "bd06d02e-ae60-4c93-b987-d2f7c3dbc248",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "8942d97d-790a-50cc-a77c-e6a1093a2808",
  isVisible: true,
  size: 150,
  position: 8
});
