// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "cfdfce7b-cac2-417e-822e-058fbc8c9f77",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca3001" /* opportunity / Opportunity Record Page Fields */,
  fieldMetadataUniversalIdentifier: "ec5127b6-834f-4a3b-a577-e5b27eeb6396",
  isVisible: true,
  size: 180,
  position: 0
});
