// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "ddd1a630-40d5-4efd-b89c-c5564f0b3f1e",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "b23c0b93-b252-5644-97de-a1d0033e28bb",
  isVisible: true,
  size: 150,
  position: 5
});
