// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "f9b8ab56-2b27-4a8f-a7c4-7b1d2fbd77ea",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca3001" /* opportunity / Opportunity Record Page Fields */,
  fieldMetadataUniversalIdentifier: "59ddc2c6-7c7a-463b-b4c1-68c4fc58b3d2",
  isVisible: true,
  size: 180,
  position: 5,
  viewFieldGroupUniversalIdentifier: "917443e8-7f3c-466a-8733-b060d38595fc"
});
