// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "dd2f1f12-e0a8-4983-8e1c-e0b076a9ca84",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "2e3c4f02-c367-58a9-897b-0773ff609b49",
  isVisible: true,
  size: 150,
  position: 10
});
