// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "9ae28d7a-c6b2-48d7-bb68-f216bf638e46",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "1ea6631e-c368-5fc4-8854-805c8d5b5245",
  isVisible: true,
  size: 150,
  position: 0
});
