// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "0bcb0380-d32f-40d8-a6c2-3036530d2a60",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "81b6ffb2-3869-5618-a9ad-bc4b0d38839b",
  isVisible: true,
  size: 150,
  position: 5
});
