// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "9f9b0660-7923-4bd8-9b60-0349e9df523d",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca3001" /* opportunity / Opportunity Record Page Fields */,
  fieldMetadataUniversalIdentifier: "639c52c3-e181-52aa-a5d2-26d793d85ed3",
  isVisible: true,
  size: 180,
  position: 2,
  viewFieldGroupUniversalIdentifier: "17f4a41f-720f-4e20-9526-3eee6c3d4f5f"
});
