// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "db0c7f5d-883f-464a-b484-2a0b7930ff52",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca3001" /* opportunity / Opportunity Record Page Fields */,
  fieldMetadataUniversalIdentifier: "0d7d96ad-f4d0-4272-8fe9-57e777faa1d0",
  isVisible: true,
  size: 180,
  position: 9
});
