// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "f6637481-c9d7-443f-ac65-79d3e81a8e8c",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "41dd11c0-a6b3-5aa8-88bb-01c80d0f313e",
  isVisible: true,
  size: 150,
  position: 6
});
