// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "5672551f-3fa2-4862-bb58-e0a0c18c6ce0",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "61f6f577-913b-5f00-ac96-5fcb4c195386",
  isVisible: true,
  size: 150,
  position: 6
});
