// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "a0dd36da-fd72-46ed-a5d1-ffba8ccffb9a",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "2d13ea2c-2087-5f74-aa00-eac72fa63092",
  isVisible: true,
  size: 150,
  position: 1
});
