// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "ed896176-baeb-459f-ba2d-b6e022a55bc4",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "9f5f3940-5523-5884-8b06-79b72c56d42f",
  isVisible: true,
  size: 150,
  position: 0
});
