// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "44c5194e-9f80-4970-af6d-9a1a0d89c06d",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "fb60b80a-1548-5dd4-b09c-041a9c61cdaf",
  isVisible: true,
  size: 150,
  position: 1
});
