// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "9174084d-729b-4c81-b04b-6b9a02219230",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "d8e4c5f6-ef3c-5faa-9a63-fc0211504cad",
  isVisible: true,
  size: 150,
  position: 7
});
