// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "019ff313-af87-46a2-b591-80c54ec12d58",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "ee40828b-2dc8-48d2-986f-7ba48dd80be3",
  isVisible: true,
  size: 180,
  position: 17
});
