// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "ee5bb854-54ab-48c6-b75d-ae769b496ddd",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "eb06a59d-f8b8-542f-a299-c87c6d9628d5",
  isVisible: true,
  size: 150,
  position: 6
});
