// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "e49b93da-9e4d-4c99-9825-9ae288317822",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "60dc9a4b-98a8-568b-bd6b-7e934c3544ed",
  isVisible: true,
  size: 150,
  position: 2
});
