// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "c98549ca-1482-4346-a3c9-9773093a223a",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca3001" /* opportunity / Opportunity Record Page Fields */,
  fieldMetadataUniversalIdentifier: "6cbaf470-a3c2-4970-a43a-3e5f98998f0e",
  isVisible: true,
  size: 180,
  position: 5
});
