// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "9c21407c-f079-42e2-9f7c-0c38ebe9f69a",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "e3c731f7-0af8-5056-8169-2c3d390b0d13",
  isVisible: true,
  size: 150,
  position: 4
});
