// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "fb8c8e0e-a2b8-4c30-8687-b25e964b69cb",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "11ca0949-87bc-54a3-a5f6-f43a39288a71",
  isVisible: true,
  size: 150,
  position: 15
});
