// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "f6399ffe-288e-4abe-b9b9-43a32488a02e",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "c67dc77b-1690-5d0f-99f2-72aefdcd4edc",
  isVisible: true,
  size: 150,
  position: 13
});
