// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "3853079c-3441-40d5-80cd-48ef79c1dcae",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "d9ee784f-c33f-5b02-a1c0-d30bd6f8942f",
  isVisible: true,
  size: 150,
  position: 1
});
