// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "40dcbeec-fdbb-489b-81d6-1bf7d571c19d",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca3001" /* opportunity / Opportunity Record Page Fields */,
  fieldMetadataUniversalIdentifier: "a15a5193-ec1a-499f-a5c0-2738525c7f83",
  isVisible: true,
  size: 180,
  position: 3
});
