// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "0b477cdb-6610-46b7-807c-d0f537bbde7e",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "d6017527-9f46-5e09-9259-2b27282c34fa",
  isVisible: true,
  size: 150,
  position: 1
});
