// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "ca88afa7-a3aa-43f1-ac1a-9a30c499066b",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "b28edb52-526c-5a7b-9cbe-9d1e5cfd1e92",
  isVisible: true,
  size: 150,
  position: 2
});
