// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "1de250d8-e82a-4213-8a37-c9c0c1845d4a",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "bad58d59-3eae-5c9d-84d4-08cab95bad4e",
  isVisible: true,
  size: 150,
  position: 0
});
