// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "88eed249-c782-4f77-9e62-5ece10c320c5",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "10bed5fe-bf6b-4630-95fa-f16f055db13d",
  isVisible: true,
  size: 180,
  position: 16
});
