// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "cd737119-1b59-4d46-a86d-474d03a68fbf",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca3001" /* opportunity / Opportunity Record Page Fields */,
  fieldMetadataUniversalIdentifier: "ee2819ad-3cc2-4c5c-a673-97a6fd7f33d9",
  isVisible: true,
  size: 180,
  position: 10,
  viewFieldGroupUniversalIdentifier: "917443e8-7f3c-466a-8733-b060d38595fc"
});
