// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "ff751b6b-cd51-46c8-8212-d350c46b1a38",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "bb94938b-98a5-54e1-9e2f-00c84a301cfb",
  isVisible: true,
  size: 150,
  position: 10
});
