// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "9c11a7a3-de3a-4503-bc3e-a7456192c1af",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "bbae4390-f35d-53ce-8c4b-afcc407d092f",
  isVisible: true,
  size: 150,
  position: 0
});
