// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "d1a39c96-96a5-4083-bfed-0ab520e3f1b8",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "ad8d53e0-e7c0-5c6a-a715-4f31a1ba66aa",
  isVisible: true,
  size: 150,
  position: 3
});
