// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "ab1b1dcb-4ef3-444e-a647-16e56f08060c",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "0f69bc82-756c-5ab4-88d6-1a777f258c48",
  isVisible: true,
  size: 150,
  position: 1
});
