// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "21b4d7d2-6336-4fda-9210-a3f3cbb0bbd0",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "92637bc4-e7e4-5ccf-a5f1-0fb8daeb9286",
  isVisible: true,
  size: 150,
  position: 6
});
