// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "b25a1913-8813-4766-be47-225ee6b99bc7",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "cb838d33-9a3c-58a0-b70c-47c609f9ff2e",
  isVisible: true,
  size: 150,
  position: 7
});
