// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "2d6983ac-c654-4881-a332-925f5968dc32",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "5602ab24-fb2c-58d9-ad14-e84cb412dfd6",
  isVisible: true,
  size: 150,
  position: 9
});
