// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "05abcc08-18f6-4c02-a0c2-a51453ec6408",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "ffc01070-0f5a-5ed4-b654-a40e96bcb15d",
  isVisible: true,
  size: 150,
  position: 8
});
