// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "e691a916-99e6-480e-9cbb-acb1f35dcba9",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "4662fea5-eef3-4aea-ae67-666f8cae72c7",
  isVisible: true,
  size: 180,
  position: 3
});
