// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "d9d4a96d-135b-4984-b6ec-0fbac315276f",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca3001" /* opportunity / Opportunity Record Page Fields */,
  fieldMetadataUniversalIdentifier: "0a108f9c-7b38-47be-b9fd-a351b6df7443",
  isVisible: true,
  size: 180,
  position: 5
});
