// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "d96358d2-96bf-4b10-a310-4aea5e11985d",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "0595cdf0-f7a2-4b2b-8522-4554b86f2232",
  isVisible: true,
  size: 180,
  position: 18
});
