// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "a9c62d8b-ebdd-4a22-8a6b-790dfc2f1612",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "6734b6fe-6492-490c-ae8a-815124e979f1",
  isVisible: true,
  size: 180,
  position: 19
});
