// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "85c12b11-33ec-4e8a-ba0c-7a55a452cd32",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "3d34a6a8-f70a-566f-bc34-cd2fe791d0a0",
  isVisible: true,
  size: 150,
  position: 7
});
