// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "8639728b-e1d2-4b52-a652-c9f2c2547f4f",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "f85277a5-35f3-43a6-94cb-e86e0e06c849",
  isVisible: true,
  size: 180,
  position: 0
});
