// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "17f5788a-6e7a-4218-992d-57d2841e9c6c",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca3001" /* opportunity / Opportunity Record Page Fields */,
  fieldMetadataUniversalIdentifier: "d8d2967b-877d-5109-8bfb-2dc33d1fc2b1",
  isVisible: true,
  size: 200,
  position: 0
});
