// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "93a8c2c1-5aad-4abb-80c3-43434a11e199",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca1ba0" /* opportunity / All {objectLabelPlural} */,
  fieldMetadataUniversalIdentifier: "d8d2967b-877d-5109-8bfb-2dc33d1fc2b1",
  isVisible: true,
  size: 150,
  position: 6
});
