// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "cee6b269-2639-4f45-ae39-0a318530e8bf",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "6a9f2eb2-f62d-50f6-ba60-31b367ea1a69",
  isVisible: true,
  size: 150,
  position: 4
});
