// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "59f0ce0a-84af-45c7-922a-a5324f49596d",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "0d42013e-3683-5bcd-bd87-2174010b2fc8",
  isVisible: true,
  size: 150,
  position: 12
});
