// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "c17432a6-ca5f-4fa2-a925-79a3ca4fff50",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "4a3cc202-d650-54bf-b34a-d51839360b2c",
  isVisible: true,
  size: 150,
  position: 11
});
