// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "8fed5b78-2a06-4555-876a-cdb41a3127ab",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "907f6268-2c7f-597a-9bd0-576d50091457",
  isVisible: true,
  size: 150,
  position: 7
});
