// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "cd490f5e-d1c3-4a97-99a8-c8f4c0a1637a",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "64cb0e7b-38db-527a-81bd-512a6594f402",
  isVisible: true,
  size: 150,
  position: 5
});
