// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "83640c2f-8d2f-4752-8888-73dad9c0c5e0",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "4dc29438-84c7-4242-8045-4322f57466f4",
  isVisible: true,
  size: 180,
  position: 2,
  viewFieldGroupUniversalIdentifier: "ca358b4c-f504-438f-b1dc-b7e23e18b172"
});
