// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "121d62de-a13b-4702-b800-9e2f776ecf66",
  viewUniversalIdentifier: "20202020-a001-4a01-8a01-c0aba11c1001" /* company / Company Record Page Fields */,
  fieldMetadataUniversalIdentifier: "69198799-74c8-445f-b610-8184418dabcc",
  isVisible: true,
  size: 180,
  position: 1,
  viewFieldGroupUniversalIdentifier: "ca358b4c-f504-438f-b1dc-b7e23e18b172"
});
