// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { defineViewField } from 'twenty-sdk/define';

export default defineViewField({
  universalIdentifier: "22abf585-477f-4907-ae99-8a9c84d5a9c0",
  viewUniversalIdentifier: "20202020-a003-4a03-8a03-0aa0b1ca3001" /* opportunity / Opportunity Record Page Fields */,
  fieldMetadataUniversalIdentifier: "4c255020-4376-41a7-9535-aeef0379540a",
  isVisible: true,
  size: 180,
  position: 5
});
