// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { PageLayoutTabLayoutMode, definePageLayout } from 'twenty-sdk/define';

export default definePageLayout({
  universalIdentifier: "e3eac72d-2467-4dde-8e68-ff91ae880fea",
  name: "Dashboard Layout",
  type: "DASHBOARD",
  tabs: [
    {
      universalIdentifier: "20ccd192-424f-4a24-9642-fddd350f5e08",
      title: "Tab 1",
      position: 0,
      layoutMode: PageLayoutTabLayoutMode.GRID
    }
  ]
});
