// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { PageLayoutTabLayoutMode, definePageLayout } from 'twenty-sdk/define';

export default definePageLayout({
  universalIdentifier: "72160d98-caeb-4d12-8d3b-0c7f0de98a2e",
  name: "Dashboard Layout",
  type: "DASHBOARD",
  tabs: [
    {
      universalIdentifier: "489bb1d1-5222-45f9-bb70-07534e6f91d5",
      title: "Tab 1",
      position: 0,
      layoutMode: PageLayoutTabLayoutMode.GRID
    }
  ]
});
