// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { PageLayoutTabLayoutMode, definePageLayout } from 'twenty-sdk/define';

export default definePageLayout({
  universalIdentifier: "61354c2e-ddf9-586b-a105-232724da062f",
  name: "Default Visit Layout",
  type: "RECORD_PAGE",
  objectUniversalIdentifier: "80155072-b338-5bd5-b7f7-2dde833c8c3e",
  tabs: [
    {
      universalIdentifier: "c9e9a835-c9c4-5a3e-82cc-a583b0de10a9",
      title: "Home",
      position: 10,
      icon: "IconHome",
      layoutMode: PageLayoutTabLayoutMode.VERTICAL_LIST,
      widgets: [
        {
          universalIdentifier: "d0b68007-0c79-5d36-8da1-450f24ba8129",
          title: "Fields",
          type: "FIELDS",
          objectUniversalIdentifier: "80155072-b338-5bd5-b7f7-2dde833c8c3e",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 12,
            columnSpan: 12
          },
          configuration: {
            viewUniversalIdentifier: "7f089831-ec3e-5e33-89e3-f1e23526b666",
            configurationType: "FIELDS",
            newFieldDefaultVisibility: true,
            shouldAllowUserToSeeHiddenFields: true
          }
        }
      ]
    },
    {
      universalIdentifier: "65c962dd-a76d-5d09-b8c1-429d710f35c3",
      title: "Timeline",
      position: 20,
      icon: "IconTimelineEvent",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "30d88bfb-1c7d-5d20-afad-5c1c76127e94",
          title: "Timeline",
          type: "TIMELINE",
          objectUniversalIdentifier: "80155072-b338-5bd5-b7f7-2dde833c8c3e",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "TIMELINE"
          }
        }
      ]
    },
    {
      universalIdentifier: "ca931139-c6d4-52d6-9f91-3a4f596c528e",
      title: "Tasks",
      position: 30,
      icon: "IconCheckbox",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "44fd02d7-7ebb-55ed-82c9-148db239ac12",
          title: "Tasks",
          type: "TASKS",
          objectUniversalIdentifier: "80155072-b338-5bd5-b7f7-2dde833c8c3e",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "TASKS"
          }
        }
      ]
    },
    {
      universalIdentifier: "dff3d060-97dc-5f8f-b312-cb239d02378b",
      title: "Notes",
      position: 40,
      icon: "IconNotes",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "d0c28848-907a-5966-b774-9fbf1d356af4",
          title: "Notes",
          type: "NOTES",
          objectUniversalIdentifier: "80155072-b338-5bd5-b7f7-2dde833c8c3e",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "NOTES"
          }
        }
      ]
    },
    {
      universalIdentifier: "692c16a3-da3f-5952-9c07-6b126278ca6c",
      title: "Files",
      position: 50,
      icon: "IconPaperclip",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "66bb711c-d449-5280-bedd-e0e3e8db8239",
          title: "Files",
          type: "FILES",
          objectUniversalIdentifier: "80155072-b338-5bd5-b7f7-2dde833c8c3e",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "FILES"
          }
        }
      ]
    }
  ]
});
