// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { PageLayoutTabLayoutMode, definePageLayout } from 'twenty-sdk/define';

export default definePageLayout({
  universalIdentifier: "093c7593-0b9b-51d3-b99b-f63e69ae1e9d",
  name: "Default Incident Layout",
  type: "RECORD_PAGE",
  objectUniversalIdentifier: "ab30bd09-9b3b-51be-b096-8554f631b30a",
  tabs: [
    {
      universalIdentifier: "01cfb4e0-e7f0-59aa-8537-4f01308a1ba7",
      title: "Home",
      position: 10,
      icon: "IconHome",
      layoutMode: PageLayoutTabLayoutMode.VERTICAL_LIST,
      widgets: [
        {
          universalIdentifier: "2c0045a4-2c7c-50b4-9a46-9485ae6e7027",
          title: "Fields",
          type: "FIELDS",
          objectUniversalIdentifier: "ab30bd09-9b3b-51be-b096-8554f631b30a",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 12,
            columnSpan: 12
          },
          configuration: {
            viewUniversalIdentifier: "7660ba37-8f57-5b5f-b10c-2811f97d79b6",
            configurationType: "FIELDS",
            newFieldDefaultVisibility: true
          }
        }
      ]
    },
    {
      universalIdentifier: "b84c0d0b-a0e4-5aa6-b690-0a48e729132c",
      title: "Timeline",
      position: 20,
      icon: "IconTimelineEvent",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "c6ab810c-b559-541d-b70a-cd4972635f69",
          title: "Timeline",
          type: "TIMELINE",
          objectUniversalIdentifier: "ab30bd09-9b3b-51be-b096-8554f631b30a",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "TIMELINE"
          }
        }
      ]
    },
    {
      universalIdentifier: "9e7d453b-eccd-5d97-9ad1-13d01e93c5b5",
      title: "Tasks",
      position: 30,
      icon: "IconCheckbox",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "57c0e603-3b72-5ec9-b785-61b3694a9d34",
          title: "Tasks",
          type: "TASKS",
          objectUniversalIdentifier: "ab30bd09-9b3b-51be-b096-8554f631b30a",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "TASKS"
          }
        }
      ]
    },
    {
      universalIdentifier: "e94e094b-a0c6-533d-a43f-b6a2850a513b",
      title: "Notes",
      position: 40,
      icon: "IconNotes",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "83cdb46a-1eee-510d-b2b9-34c49ecf2e0b",
          title: "Notes",
          type: "NOTES",
          objectUniversalIdentifier: "ab30bd09-9b3b-51be-b096-8554f631b30a",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "NOTES"
          }
        }
      ]
    },
    {
      universalIdentifier: "fb5d3d65-9587-530b-a5ae-abb6663bf7b6",
      title: "Files",
      position: 50,
      icon: "IconPaperclip",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "d829eb59-47bf-5655-9749-c6beaaaa09f2",
          title: "Files",
          type: "FILES",
          objectUniversalIdentifier: "ab30bd09-9b3b-51be-b096-8554f631b30a",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "FILES"
          }
        }
      ]
    }
  ]
});
