// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { PageLayoutTabLayoutMode, definePageLayout } from 'twenty-sdk/define';

export default definePageLayout({
  universalIdentifier: "00b5df8e-e471-514a-8be8-9ea99d986f6b",
  name: "Default Payment Promise Layout",
  type: "RECORD_PAGE",
  objectUniversalIdentifier: "730c3de2-6bc0-501d-bbde-d81453da11d2",
  tabs: [
    {
      universalIdentifier: "69b9b5f5-d38a-5b86-a594-ce6c77bba1ee",
      title: "Home",
      position: 10,
      icon: "IconHome",
      layoutMode: PageLayoutTabLayoutMode.VERTICAL_LIST,
      widgets: [
        {
          universalIdentifier: "702e7ac6-f899-56f9-8127-2518959b0a8b",
          title: "Fields",
          type: "FIELDS",
          objectUniversalIdentifier: "730c3de2-6bc0-501d-bbde-d81453da11d2",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 12,
            columnSpan: 12
          },
          configuration: {
            viewUniversalIdentifier: "53c60388-6868-52c3-9e91-5cc3e781170f",
            configurationType: "FIELDS",
            newFieldDefaultVisibility: true
          }
        }
      ]
    },
    {
      universalIdentifier: "8129e6f3-a6ce-5fb6-ade7-a5fd0fc617c4",
      title: "Timeline",
      position: 20,
      icon: "IconTimelineEvent",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "aae2130c-fba3-57ca-a470-f53b3859a405",
          title: "Timeline",
          type: "TIMELINE",
          objectUniversalIdentifier: "730c3de2-6bc0-501d-bbde-d81453da11d2",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "TIMELINE"
          }
        }
      ]
    },
    {
      universalIdentifier: "089a1afb-b961-50e3-925f-8de6c49ec02a",
      title: "Tasks",
      position: 30,
      icon: "IconCheckbox",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "944e4ec5-f03f-5cf5-81cc-d3969c4cc541",
          title: "Tasks",
          type: "TASKS",
          objectUniversalIdentifier: "730c3de2-6bc0-501d-bbde-d81453da11d2",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "TASKS"
          }
        }
      ]
    },
    {
      universalIdentifier: "707ffd32-cfe4-5aa6-a05e-bc12659046a7",
      title: "Notes",
      position: 40,
      icon: "IconNotes",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "826a7beb-fb80-55b4-8bc5-a89ac512b7bf",
          title: "Notes",
          type: "NOTES",
          objectUniversalIdentifier: "730c3de2-6bc0-501d-bbde-d81453da11d2",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "NOTES"
          }
        }
      ]
    },
    {
      universalIdentifier: "8108a9aa-13fa-5573-a0a1-253e5691fe9f",
      title: "Files",
      position: 50,
      icon: "IconPaperclip",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "884e87e1-b48d-5006-b75c-7aa4cab5ac24",
          title: "Files",
          type: "FILES",
          objectUniversalIdentifier: "730c3de2-6bc0-501d-bbde-d81453da11d2",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "FILES"
          }
        }
      ]
    }
  ]
});
