// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { PageLayoutTabLayoutMode, definePageLayout } from 'twenty-sdk/define';

export default definePageLayout({
  universalIdentifier: "bb480fca-9d77-517b-be5e-499186f17bf2",
  name: "Default Collections Case Layout",
  type: "RECORD_PAGE",
  objectUniversalIdentifier: "d9fc138e-e50c-5835-85c1-51793672be07",
  tabs: [
    {
      universalIdentifier: "567f36c7-39b4-5ba7-8043-38abae0cedd6",
      title: "Home",
      position: 10,
      icon: "IconHome",
      layoutMode: PageLayoutTabLayoutMode.VERTICAL_LIST,
      widgets: [
        {
          universalIdentifier: "35cfecfd-7cc2-5fce-9033-34a6a9899503",
          title: "Fields",
          type: "FIELDS",
          objectUniversalIdentifier: "d9fc138e-e50c-5835-85c1-51793672be07",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 12,
            columnSpan: 12
          },
          configuration: {
            viewUniversalIdentifier: "356681f0-9670-5b94-ba53-25213e781a56",
            configurationType: "FIELDS",
            newFieldDefaultVisibility: true
          }
        }
      ]
    },
    {
      universalIdentifier: "0ab9f90d-e3eb-58f6-8b39-a4aefdf04ed2",
      title: "Timeline",
      position: 20,
      icon: "IconTimelineEvent",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "a6f24ca0-b8ee-5548-b9ae-9083d27c0e66",
          title: "Timeline",
          type: "TIMELINE",
          objectUniversalIdentifier: "d9fc138e-e50c-5835-85c1-51793672be07",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "TIMELINE"
          }
        }
      ]
    },
    {
      universalIdentifier: "e8d049d3-00d7-5f2f-9ede-da84deffb516",
      title: "Tasks",
      position: 30,
      icon: "IconCheckbox",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "b699b8eb-fa74-5f28-bab3-58a5bc2b72b5",
          title: "Tasks",
          type: "TASKS",
          objectUniversalIdentifier: "d9fc138e-e50c-5835-85c1-51793672be07",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "TASKS"
          }
        }
      ]
    },
    {
      universalIdentifier: "2d9fff2d-ebcc-56fe-81d9-7070e0175be7",
      title: "Notes",
      position: 40,
      icon: "IconNotes",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "ce599a32-b890-5f66-af5e-6eea5ab169f5",
          title: "Notes",
          type: "NOTES",
          objectUniversalIdentifier: "d9fc138e-e50c-5835-85c1-51793672be07",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "NOTES"
          }
        }
      ]
    },
    {
      universalIdentifier: "b118da3b-33bb-522d-a244-ef222bbe2a86",
      title: "Files",
      position: 50,
      icon: "IconPaperclip",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "70b661cf-7446-5051-a28c-e16b15a22158",
          title: "Files",
          type: "FILES",
          objectUniversalIdentifier: "d9fc138e-e50c-5835-85c1-51793672be07",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "FILES"
          }
        }
      ]
    }
  ]
});
