// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { PageLayoutTabLayoutMode, definePageLayout } from 'twenty-sdk/define';

export default definePageLayout({
  universalIdentifier: "a3a37786-1ccb-57c7-ac1d-d293e425037d",
  name: "Default Standing Order Layout",
  type: "RECORD_PAGE",
  objectUniversalIdentifier: "1d2f5ca4-4d73-5f46-9a86-118e41a67839",
  tabs: [
    {
      universalIdentifier: "7635523d-7280-5b0c-b178-fe9a0ac8e0ae",
      title: "Home",
      position: 10,
      icon: "IconHome",
      layoutMode: PageLayoutTabLayoutMode.VERTICAL_LIST,
      widgets: [
        {
          universalIdentifier: "d3c9c88c-1c57-516c-906a-5dfabc55a966",
          title: "Fields",
          type: "FIELDS",
          objectUniversalIdentifier: "1d2f5ca4-4d73-5f46-9a86-118e41a67839",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 12,
            columnSpan: 12
          },
          configuration: {
            viewUniversalIdentifier: "cf66a022-0285-5bdf-9442-371ff9f7ba6b",
            configurationType: "FIELDS",
            newFieldDefaultVisibility: true
          }
        }
      ]
    },
    {
      universalIdentifier: "a166e5bc-0acd-5019-ae46-90061c7772bb",
      title: "Timeline",
      position: 20,
      icon: "IconTimelineEvent",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "427d6691-1539-5491-8324-901008905f16",
          title: "Timeline",
          type: "TIMELINE",
          objectUniversalIdentifier: "1d2f5ca4-4d73-5f46-9a86-118e41a67839",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "TIMELINE"
          }
        }
      ]
    },
    {
      universalIdentifier: "cd2bc62c-0b16-5415-9005-067e51d56b2d",
      title: "Tasks",
      position: 30,
      icon: "IconCheckbox",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "ddb13c4d-6e20-52aa-bbab-7a45e074da0d",
          title: "Tasks",
          type: "TASKS",
          objectUniversalIdentifier: "1d2f5ca4-4d73-5f46-9a86-118e41a67839",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "TASKS"
          }
        }
      ]
    },
    {
      universalIdentifier: "3740b3b3-8eee-583e-b389-b92c8054f86f",
      title: "Notes",
      position: 40,
      icon: "IconNotes",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "aef72c4b-85ff-52d4-9783-0b0d8faf76b8",
          title: "Notes",
          type: "NOTES",
          objectUniversalIdentifier: "1d2f5ca4-4d73-5f46-9a86-118e41a67839",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "NOTES"
          }
        }
      ]
    },
    {
      universalIdentifier: "4eb984f2-ceba-59e0-b6e4-ed6359a26e09",
      title: "Files",
      position: 50,
      icon: "IconPaperclip",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "e574c468-5ea8-590a-8eeb-dbe9c3b9bdd5",
          title: "Files",
          type: "FILES",
          objectUniversalIdentifier: "1d2f5ca4-4d73-5f46-9a86-118e41a67839",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "FILES"
          }
        }
      ]
    }
  ]
});
