// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { PageLayoutTabLayoutMode, definePageLayout } from 'twenty-sdk/define';

export default definePageLayout({
  universalIdentifier: "2f57e88f-690b-5d14-9145-afe8c393b0b4",
  name: "Default Order Event Layout",
  type: "RECORD_PAGE",
  objectUniversalIdentifier: "aa860ef9-896f-5677-84f2-e69fefd3b630",
  tabs: [
    {
      universalIdentifier: "ae7dcb1a-7135-59cc-a464-1114115e259e",
      title: "Home",
      position: 10,
      icon: "IconHome",
      layoutMode: PageLayoutTabLayoutMode.VERTICAL_LIST,
      widgets: [
        {
          universalIdentifier: "226218b7-c00b-5289-9892-cd762b61014e",
          title: "Fields",
          type: "FIELDS",
          objectUniversalIdentifier: "aa860ef9-896f-5677-84f2-e69fefd3b630",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 12,
            columnSpan: 12
          },
          configuration: {
            viewUniversalIdentifier: "cdfd72fe-f1e1-5d40-bb30-506cf57cfadc",
            configurationType: "FIELDS",
            newFieldDefaultVisibility: true
          }
        }
      ]
    },
    {
      universalIdentifier: "498d9cc1-ed31-56e2-9564-7650e349e961",
      title: "Timeline",
      position: 20,
      icon: "IconTimelineEvent",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "d124fa93-5300-5951-9c8e-4027a5d73a84",
          title: "Timeline",
          type: "TIMELINE",
          objectUniversalIdentifier: "aa860ef9-896f-5677-84f2-e69fefd3b630",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "TIMELINE"
          }
        }
      ]
    },
    {
      universalIdentifier: "682b9c77-2ee9-595d-bac0-b33a20aca0f2",
      title: "Tasks",
      position: 30,
      icon: "IconCheckbox",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "6f5821fc-82eb-52fd-b714-119a43f48bf7",
          title: "Tasks",
          type: "TASKS",
          objectUniversalIdentifier: "aa860ef9-896f-5677-84f2-e69fefd3b630",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "TASKS"
          }
        }
      ]
    },
    {
      universalIdentifier: "6c9e6a58-10b3-5bcf-8de0-6fe905e3f589",
      title: "Notes",
      position: 40,
      icon: "IconNotes",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "7aab098b-8db7-558a-a484-e658bcb352df",
          title: "Notes",
          type: "NOTES",
          objectUniversalIdentifier: "aa860ef9-896f-5677-84f2-e69fefd3b630",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "NOTES"
          }
        }
      ]
    },
    {
      universalIdentifier: "5b508ae7-5781-515a-8e3f-c298a31858fa",
      title: "Files",
      position: 50,
      icon: "IconPaperclip",
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      widgets: [
        {
          universalIdentifier: "db1ce55e-d6f4-564d-a246-7386e43137b4",
          title: "Files",
          type: "FILES",
          objectUniversalIdentifier: "aa860ef9-896f-5677-84f2-e69fefd3b630",
          gridPosition: {
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12
          },
          configuration: {
            configurationType: "FILES"
          }
        }
      ]
    }
  ]
});
