// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, OnDeleteAction, RelationType, defineObject } from 'twenty-sdk/define';

export const COLLECTIONS_CASE_OBJECT_UNIVERSAL_IDENTIFIER = "d9fc138e-e50c-5835-85c1-51793672be07";

export default defineObject({
  universalIdentifier: COLLECTIONS_CASE_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: "collectionsCase",
  namePlural: "collectionsCases",
  labelSingular: "Collections Case",
  labelPlural: "Collections Cases",
  icon: "IconGavel",
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: "9c3dd4ac-ad02-5a27-93f7-b9a5be2d038d",
  fields: [
    {
      universalIdentifier: "2e39294c-31ad-542d-92d9-72db3421423a",
      type: FieldType.SELECT,
      name: "caseStatus",
      label: "Case Status",
      icon: "IconProgress",
      isNullable: true,
      defaultValue: "'OPEN'",
      options: [
        {
          id: "2f2fb682-f419-5cad-818d-a9f3351d2e49",
          color: "sky",
          label: "Open",
          value: "OPEN",
          position: 0
        },
        {
          id: "b62a903c-5428-5095-86ff-f7dbaf88203f",
          color: "turquoise",
          label: "Handover",
          value: "HANDOVER",
          position: 1
        },
        {
          id: "794c77c9-07be-5dc8-90aa-d10a8284b4fa",
          color: "sky",
          label: "Legal",
          value: "LEGAL",
          position: 2
        },
        {
          id: "f4506eb2-d2e0-50f7-a1c0-f8bbcea4a58f",
          color: "green",
          label: "Resolved",
          value: "RESOLVED",
          position: 3
        },
        {
          id: "23b6acb8-6427-5dc1-a38c-24b3f36aadaf",
          color: "purple",
          label: "Written Off",
          value: "WRITTEN_OFF",
          position: 4
        }
      ]
    },
    {
      universalIdentifier: "47c22935-fe39-5f89-b4b0-8049f41e242b",
      type: FieldType.RELATION,
      name: "company",
      label: "Company",
      icon: "IconGavel",
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
      relationTargetFieldMetadataUniversalIdentifier: "6bc07c35-3763-5160-88dd-64d5a6b0b58d",
      universalSettings: {
        onDelete: OnDeleteAction.SET_NULL,
        relationType: RelationType.MANY_TO_ONE,
        joinColumnName: "companyId"
      }
    },
    {
      universalIdentifier: "b4a32d52-77a7-55ac-9058-5fde382d9782",
      type: FieldType.DATE_TIME,
      name: "createdAt",
      label: "Creation date",
      icon: "IconCalendar",
      isNullable: false,
      defaultValue: "now"
    },
    {
      universalIdentifier: "75d75787-b5c9-5a26-855f-3423791195ed",
      type: FieldType.ACTOR,
      name: "createdBy",
      label: "Created by",
      icon: "IconCreativeCommonsSa",
      isNullable: false,
      defaultValue: {
        name: "''",
        source: "'MANUAL'"
      }
    },
    {
      universalIdentifier: "e678c3e7-3c4f-5ffb-8168-111666ee30be",
      type: FieldType.DATE_TIME,
      name: "deletedAt",
      label: "Deleted at",
      icon: "IconCalendarClock",
      isNullable: true
    },
    {
      universalIdentifier: "9cabea7e-69f7-5b06-8963-d9dd6d9f5132",
      type: FieldType.LINKS,
      name: "handoverPackUrl",
      label: "Handover Pack",
      description: "Generated history PDF (W-19)",
      icon: "IconFileText",
      isNullable: true
    },
    {
      universalIdentifier: "e9f7a8af-42df-52f4-8462-f984cd3652a2",
      type: FieldType.UUID,
      name: "id",
      label: "Id",
      icon: "Icon123",
      isNullable: false,
      defaultValue: "uuid"
    },
    {
      universalIdentifier: "36c3a48b-6965-55e4-a57e-0b0463b76749",
      type: FieldType.SELECT,
      name: "ladderStep",
      label: "Ladder Step",
      icon: "IconStairsUp",
      isNullable: true,
      options: [
        {
          id: "ace00a39-9aaf-518e-b6ec-2d4f30c8b1fa",
          color: "green",
          label: "None",
          value: "NONE",
          position: 0
        },
        {
          id: "3ecfd4ee-5892-57c0-9f92-3a926707974b",
          color: "turquoise",
          label: "D1",
          value: "D1",
          position: 1
        },
        {
          id: "065f0287-8b65-56e4-9722-87076614b16c",
          color: "sky",
          label: "D3",
          value: "D3",
          position: 2
        },
        {
          id: "0e124d23-21aa-5ba8-87ee-4217e8937af9",
          color: "blue",
          label: "D7",
          value: "D7",
          position: 3
        },
        {
          id: "d72e9cf8-1362-50c6-aacd-5b782dfdc0f3",
          color: "purple",
          label: "Handed Over",
          value: "HANDED_OVER",
          position: 4
        },
        {
          id: "c6ff777d-940d-5550-963a-0223a6a4a045",
          color: "pink",
          label: "D14 Legal",
          value: "D14_LEGAL",
          position: 5
        },
        {
          id: "1f64ccc6-2da3-5c16-9060-dc188a728806",
          color: "red",
          label: "D21 Court",
          value: "D21_COURT",
          position: 6
        },
        {
          id: "925d2f9c-14d1-5748-898f-2a92764dad48",
          color: "orange",
          label: "Write Off",
          value: "WRITE_OFF",
          position: 7
        }
      ]
    },
    {
      universalIdentifier: "19a820a1-aed5-5c20-925b-bb7430deb7b9",
      type: FieldType.SELECT,
      name: "legalPath",
      label: "Legal Path",
      icon: "IconScale",
      isNullable: true,
      options: [
        {
          id: "980f510a-ab6d-5176-88ce-a55d47f7a14c",
          color: "green",
          label: "None",
          value: "NONE",
          position: 0
        },
        {
          id: "9f45f87c-58b3-56ef-b8ba-0ac69d51b23c",
          color: "turquoise",
          label: "Pdc Execution Court",
          value: "PDC_EXECUTION_COURT",
          position: 1
        },
        {
          id: "62b10374-b522-58a9-80cd-9300e795e5a6",
          color: "sky",
          label: "Payment Order Art62",
          value: "PAYMENT_ORDER_ART62",
          position: 2
        },
        {
          id: "9525a2e7-fced-5736-be1c-8ea6393c446e",
          color: "blue",
          label: "Civil Claim Sct",
          value: "CIVIL_CLAIM_SCT",
          position: 3
        }
      ]
    },
    {
      universalIdentifier: "9c3dd4ac-ad02-5a27-93f7-b9a5be2d038d",
      type: FieldType.TEXT,
      name: "name",
      label: "Name",
      icon: "IconAbc",
      isNullable: true
    },
    {
      universalIdentifier: "d3afd584-9c8e-50f7-8178-21aed1bf75c8",
      type: FieldType.DATE,
      name: "nextActionDate",
      label: "Next Action Date",
      icon: "IconCalendarDue",
      isNullable: true
    },
    {
      universalIdentifier: "c7301e60-ccd6-5a42-926f-b6c6fbb37990",
      type: FieldType.SELECT,
      name: "owner",
      label: "Owner",
      icon: "IconUserCog",
      isNullable: true,
      options: [
        {
          id: "129eb6b8-e35c-57af-a467-e8f56bd2e777",
          color: "green",
          label: "Am",
          value: "AM",
          position: 0
        },
        {
          id: "5aa67c64-7410-51fe-a555-0cabfc43c6d0",
          color: "turquoise",
          label: "Finance",
          value: "FINANCE",
          position: 1
        }
      ]
    },
    {
      universalIdentifier: "fd6f138f-b1fb-54ae-86fa-88ec65856b29",
      type: FieldType.POSITION,
      name: "position",
      label: "Position",
      icon: "IconHierarchy2",
      isNullable: false,
      defaultValue: 0
    },
    {
      universalIdentifier: "e9ef5d1b-d37b-50ea-adf2-434f3b3a0311",
      type: FieldType.TS_VECTOR,
      name: "searchVector",
      label: "Search vector",
      icon: "IconSearch",
      isNullable: true,
      universalSettings: {
        asExpression: "to_tsvector('simple', COALESCE(public.unaccent_immutable(\"name\"), ''))",
        generatedType: "STORED"
      }
    },
    {
      universalIdentifier: "98a0db67-bb5a-5d21-93d6-68b08f02f2c3",
      type: FieldType.DATE_TIME,
      name: "updatedAt",
      label: "Last update",
      icon: "IconCalendarClock",
      isNullable: false,
      defaultValue: "now"
    },
    {
      universalIdentifier: "e0e59d71-b1ce-5965-adf4-aee9a49b117f",
      type: FieldType.ACTOR,
      name: "updatedBy",
      label: "Updated by",
      icon: "IconUserCircle",
      isNullable: false,
      defaultValue: {
        name: "''",
        source: "'MANUAL'"
      }
    },
    {
      universalIdentifier: "e07425d4-b2d8-52b3-a39f-2b788abb4be6",
      type: FieldType.TEXT,
      name: "writeOffApprovedBy",
      label: "Write-Off Approved By",
      description: "Manager sign-off BR-21.1",
      icon: "IconSignature",
      isNullable: true
    },
    {
      universalIdentifier: "234b31a3-9f1e-5fe4-a701-a0751d8700a1",
      type: FieldType.DATE_TIME,
      name: "writeOffAt",
      label: "Write-Off At",
      icon: "IconCalendarX",
      isNullable: true
    }
  ]
});
