// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, OnDeleteAction, RelationType, defineObject } from 'twenty-sdk/define';

export const INCIDENT_OBJECT_UNIVERSAL_IDENTIFIER = "ab30bd09-9b3b-51be-b096-8554f631b30a";

export default defineObject({
  universalIdentifier: INCIDENT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: "incident",
  namePlural: "incidents",
  labelSingular: "Incident",
  labelPlural: "Incidents",
  icon: "IconAlertHexagon",
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: "6deea410-bb19-5d63-b3a1-a8381a097fc6",
  fields: [
    {
      universalIdentifier: "ed0fd653-7b04-5ce6-90ad-c5f0758a81c5",
      type: FieldType.SELECT,
      name: "category",
      label: "Category",
      icon: "IconCategory",
      isNullable: true,
      options: [
        {
          id: "cf17c434-acbc-5ad2-9f95-3c861559da78",
          color: "green",
          label: "Damage",
          value: "DAMAGE",
          position: 0
        },
        {
          id: "2d4c0f1b-3f3e-5943-8038-327a89a1bb12",
          color: "turquoise",
          label: "Quality",
          value: "QUALITY",
          position: 1
        },
        {
          id: "e1cd2d76-a2e3-5b56-81d1-1bd6c392f141",
          color: "sky",
          label: "Missing Item",
          value: "MISSING_ITEM",
          position: 2
        },
        {
          id: "63bc7b53-25e6-5fba-9c7c-02f84a6523ec",
          color: "blue",
          label: "Catalogue Mismatch",
          value: "CATALOGUE_MISMATCH",
          position: 3
        },
        {
          id: "f0f86f03-a96a-538f-943f-e112db48d515",
          color: "purple",
          label: "Delivery",
          value: "DELIVERY",
          position: 4
        },
        {
          id: "eaaff29f-35bd-55a5-9809-95a8e1020216",
          color: "pink",
          label: "Comms",
          value: "COMMS",
          position: 5
        },
        {
          id: "fd1d62bc-2eb5-5323-80ea-784b060ce68d",
          color: "red",
          label: "Cod Violation",
          value: "COD_VIOLATION",
          position: 6
        }
      ]
    },
    {
      universalIdentifier: "35582677-183a-568e-9013-4cacf47b4d72",
      type: FieldType.RELATION,
      name: "company",
      label: "Company",
      icon: "IconAlertHexagon",
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
      relationTargetFieldMetadataUniversalIdentifier: "c90c62a7-6b11-5fee-82e2-e9227f058550",
      universalSettings: {
        onDelete: OnDeleteAction.SET_NULL,
        relationType: RelationType.MANY_TO_ONE,
        joinColumnName: "companyId"
      }
    },
    {
      universalIdentifier: "7e71d0cb-3e99-50f0-b729-16a78f0f058e",
      type: FieldType.SELECT,
      name: "compensationAction",
      label: "Compensation Action",
      description: "Proactive per R7",
      icon: "IconGift",
      isNullable: true,
      options: [
        {
          id: "926c346c-02e3-51bd-8aed-8b00f0fb091f",
          color: "green",
          label: "None",
          value: "NONE",
          position: 0
        },
        {
          id: "547fd31f-4102-5fa4-aad9-29ba6222f97f",
          color: "turquoise",
          label: "Credit Next Order",
          value: "CREDIT_NEXT_ORDER",
          position: 1
        },
        {
          id: "8a34127d-e24e-5067-87a2-269c7f53928f",
          color: "sky",
          label: "Replacement",
          value: "REPLACEMENT",
          position: 2
        },
        {
          id: "0cdff024-6c1a-537d-9ed9-dd042ece8bcb",
          color: "blue",
          label: "Voucher",
          value: "VOUCHER",
          position: 3
        }
      ]
    },
    {
      universalIdentifier: "63f70ab6-f7f2-5d38-9977-5b561e8a24c7",
      type: FieldType.DATE_TIME,
      name: "createdAt",
      label: "Creation date",
      icon: "IconCalendar",
      isNullable: false,
      defaultValue: "now"
    },
    {
      universalIdentifier: "82200995-4dac-56e8-a5e6-201e5ed2c4cf",
      type: FieldType.ACTOR,
      name: "createdBy",
      label: "Created by",
      icon: "IconCreativeCommonsSa",
      isNullable: false,
      defaultValue: {
        name: "''",
        source: "'MANUAL'"
      }
    },
    {
      universalIdentifier: "69fbbab6-7cc0-5fe2-9512-30a46024259d",
      type: FieldType.TEXT,
      name: "creditNoteRef",
      label: "Credit Note Ref",
      description: "ERP credit-note invoice number",
      icon: "IconReceiptRefund",
      isNullable: true
    },
    {
      universalIdentifier: "240265cd-d29c-5e83-928b-fdc3f3bf4d88",
      type: FieldType.DATE_TIME,
      name: "deletedAt",
      label: "Deleted at",
      icon: "IconCalendarClock",
      isNullable: true
    },
    {
      universalIdentifier: "8c345db3-b260-5307-83f0-b9c6c9cb8a20",
      type: FieldType.NUMBER,
      name: "erpIncidentId",
      label: "ERP Incident Id",
      description: "ERP product_incidents.id",
      icon: "IconDatabase",
      isNullable: true
    },
    {
      universalIdentifier: "d2ce884f-c593-56d8-a859-6531761d1984",
      type: FieldType.UUID,
      name: "id",
      label: "Id",
      icon: "Icon123",
      isNullable: false,
      defaultValue: "uuid"
    },
    {
      universalIdentifier: "6deea410-bb19-5d63-b3a1-a8381a097fc6",
      type: FieldType.TEXT,
      name: "name",
      label: "Name",
      icon: "IconAbc",
      isNullable: true
    },
    {
      universalIdentifier: "027db794-9593-5702-b8b7-ccfd613fbd79",
      type: FieldType.POSITION,
      name: "position",
      label: "Position",
      icon: "IconHierarchy2",
      isNullable: false,
      defaultValue: 0
    },
    {
      universalIdentifier: "c460db67-e1ae-5a82-8b32-80bbfc7c5cf3",
      type: FieldType.TS_VECTOR,
      name: "searchVector",
      label: "Search vector",
      icon: "IconSearch",
      isNullable: true,
      universalSettings: {
        asExpression: "to_tsvector('simple', COALESCE(public.unaccent_immutable(\"name\"), ''))",
        generatedType: "STORED"
      }
    },
    {
      universalIdentifier: "7bbbab9f-a02a-582c-86e9-71ef39b7befb",
      type: FieldType.SELECT,
      name: "severity",
      label: "Severity",
      icon: "IconAlertTriangle",
      isNullable: true,
      options: [
        {
          id: "9f9db77d-6383-515d-99dc-6a7f8405958f",
          color: "gray",
          label: "Low",
          value: "LOW",
          position: 0
        },
        {
          id: "df381b86-f161-557b-971f-ec26719206ad",
          color: "yellow",
          label: "Medium",
          value: "MEDIUM",
          position: 1
        },
        {
          id: "894fdd8d-68ec-546e-b38d-a08dbb5be236",
          color: "red",
          label: "High",
          value: "HIGH",
          position: 2
        }
      ]
    },
    {
      universalIdentifier: "f8330c48-f389-5c46-a509-1d30c1d14d12",
      type: FieldType.RELATION,
      name: "sourceOrder",
      label: "Source Order",
      icon: "IconAlertHexagon",
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: "aa860ef9-896f-5677-84f2-e69fefd3b630" /* orderEvent */,
      relationTargetFieldMetadataUniversalIdentifier: "7eebe8ee-6c10-5ddb-8b48-0e06b2c07696",
      universalSettings: {
        onDelete: OnDeleteAction.SET_NULL,
        relationType: RelationType.MANY_TO_ONE,
        joinColumnName: "sourceOrderId"
      }
    },
    {
      universalIdentifier: "fc696a2f-fa74-5c02-afb6-aa3ecc786cc4",
      type: FieldType.SELECT,
      name: "status",
      label: "Status",
      icon: "IconProgress",
      isNullable: true,
      defaultValue: "'OPEN'",
      options: [
        {
          id: "c6e94878-76a2-5f24-9b4c-7121834ac5f0",
          color: "sky",
          label: "Open",
          value: "OPEN",
          position: 0
        },
        {
          id: "b690dbf9-e6c7-5b4e-9b9d-b53ad953bd64",
          color: "green",
          label: "Resolved",
          value: "RESOLVED",
          position: 1
        }
      ]
    },
    {
      universalIdentifier: "18fe0a7a-6a83-5747-bf49-4ec99c2c3436",
      type: FieldType.DATE_TIME,
      name: "updatedAt",
      label: "Last update",
      icon: "IconCalendarClock",
      isNullable: false,
      defaultValue: "now"
    },
    {
      universalIdentifier: "77ba9986-2a52-57e5-b35b-0f24c2375d59",
      type: FieldType.ACTOR,
      name: "updatedBy",
      label: "Updated by",
      icon: "IconUserCircle",
      isNullable: false,
      defaultValue: {
        name: "''",
        source: "'MANUAL'"
      }
    }
  ]
});
