// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, OnDeleteAction, RelationType, defineObject } from 'twenty-sdk/define';

export const ORDER_EVENT_OBJECT_UNIVERSAL_IDENTIFIER = "aa860ef9-896f-5677-84f2-e69fefd3b630";

export default defineObject({
  universalIdentifier: ORDER_EVENT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: "orderEvent",
  namePlural: "orderEvents",
  labelSingular: "Order Event",
  labelPlural: "Order Events",
  icon: "IconTruckDelivery",
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: "9a54ddfa-1da5-5d83-a95a-2b00108f26f4",
  fields: [
    {
      universalIdentifier: "97373cf8-fdc7-59ae-b3cd-b7004bf35cdb",
      type: FieldType.DATE_TIME,
      name: "amAcknowledgedAt",
      label: "AM Acknowledged At",
      icon: "IconClockCheck",
      isNullable: true
    },
    {
      universalIdentifier: "e5e50924-e135-545e-8219-b076f09f0d8d",
      type: FieldType.SELECT,
      name: "channel",
      label: "Channel",
      icon: "IconDeviceMobile",
      isNullable: true,
      options: [
        {
          id: "30c45b13-4ade-5c6a-9608-cc51cfeed0b0",
          color: "green",
          label: "Online",
          value: "ONLINE",
          position: 0
        },
        {
          id: "3bae631f-fd62-5d9c-8740-26aaf62a4ba8",
          color: "orange",
          label: "Offline",
          value: "OFFLINE",
          position: 1
        }
      ]
    },
    {
      universalIdentifier: "e0b467fd-d2dc-554f-bfc5-8cd258af666f",
      type: FieldType.DATE_TIME,
      name: "clientInformedAt",
      label: "Client Informed At",
      icon: "IconClockCheck",
      isNullable: true
    },
    {
      universalIdentifier: "6628254f-03b7-5fa8-8d4b-2511aed38443",
      type: FieldType.RELATION,
      name: "company",
      label: "Company",
      icon: "IconTruckDelivery",
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
      relationTargetFieldMetadataUniversalIdentifier: "fc564050-d8b6-5668-9936-52b8ced972cc",
      universalSettings: {
        onDelete: OnDeleteAction.SET_NULL,
        relationType: RelationType.MANY_TO_ONE,
        joinColumnName: "companyId"
      }
    },
    {
      universalIdentifier: "ba414589-b57d-55f3-b48e-8741624ef227",
      type: FieldType.DATE_TIME,
      name: "createdAt",
      label: "Creation date",
      icon: "IconCalendar",
      isNullable: false,
      defaultValue: "now"
    },
    {
      universalIdentifier: "5eaad4a0-317d-5376-b331-080ad56e2455",
      type: FieldType.ACTOR,
      name: "createdBy",
      label: "Created by",
      icon: "IconCreativeCommonsSa",
      isNullable: false,
      defaultValue: {
        name: "''",
        source: "'MANUAL'"
      }
    },
    {
      universalIdentifier: "ac4c9b9f-2736-5245-baca-6632668aaff9",
      type: FieldType.DATE_TIME,
      name: "deletedAt",
      label: "Deleted at",
      icon: "IconCalendarClock",
      isNullable: true
    },
    {
      universalIdentifier: "56d16a71-6c16-5d7c-9965-0aa1e56e2d2c",
      type: FieldType.NUMBER,
      name: "erpOrderId",
      label: "ERP Order Id",
      icon: "IconDatabase",
      isNullable: true
    },
    {
      universalIdentifier: "3c6900fb-8654-5a19-a547-9cd8f0ec1371",
      type: FieldType.SELECT,
      name: "eventType",
      label: "Event Type",
      icon: "IconBolt",
      isNullable: true,
      options: [
        {
          id: "a97a7dcf-70d5-59f3-abcd-b615a8a6c26e",
          color: "green",
          label: "Created",
          value: "CREATED",
          position: 0
        },
        {
          id: "3c169072-f14e-572b-ad19-b596992b3669",
          color: "turquoise",
          label: "Dispatched",
          value: "DISPATCHED",
          position: 1
        },
        {
          id: "f430b59e-2f1d-5240-8a8a-7540a54800b2",
          color: "sky",
          label: "Delivered",
          value: "DELIVERED",
          position: 2
        },
        {
          id: "71f3cf0d-d2db-59f9-a7ad-a7820cf2ffd2",
          color: "blue",
          label: "Rating Received",
          value: "RATING_RECEIVED",
          position: 3
        },
        {
          id: "1bb5a882-dc94-5557-8bfc-f85b4f042672",
          color: "purple",
          label: "Blocked Attempt",
          value: "BLOCKED_ATTEMPT",
          position: 4
        }
      ]
    },
    {
      universalIdentifier: "ce97391e-f03b-5d6f-89da-998dbc989b83",
      type: FieldType.UUID,
      name: "id",
      label: "Id",
      icon: "Icon123",
      isNullable: false,
      defaultValue: "uuid"
    },
    {
      universalIdentifier: "7eebe8ee-6c10-5ddb-8b48-0e06b2c07696",
      type: FieldType.RELATION,
      name: "incidents",
      label: "Incidents",
      icon: "IconAlertHexagon",
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: "ab30bd09-9b3b-51be-b096-8554f631b30a" /* incident */,
      relationTargetFieldMetadataUniversalIdentifier: "f8330c48-f389-5c46-a509-1d30c1d14d12",
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY
      }
    },
    {
      universalIdentifier: "33837ab2-de86-5ab0-95c0-115b1c059c8c",
      type: FieldType.SELECT,
      name: "itemRemovalReason",
      label: "Item Removal Reason",
      description: "UC-08 chain",
      icon: "IconAlertTriangle",
      isNullable: true,
      options: [
        {
          id: "86f5a372-3692-5f55-a73b-035f9924c25d",
          color: "green",
          label: "None",
          value: "NONE",
          position: 0
        },
        {
          id: "3ae77324-e724-55fe-ab33-81070bde5bf3",
          color: "turquoise",
          label: "Quality Fail",
          value: "QUALITY_FAIL",
          position: 1
        },
        {
          id: "5c2d6a97-7427-5fc0-887b-8b5a7292ad67",
          color: "sky",
          label: "Stock Discrepancy",
          value: "STOCK_DISCREPANCY",
          position: 2
        }
      ]
    },
    {
      universalIdentifier: "9a54ddfa-1da5-5d83-a95a-2b00108f26f4",
      type: FieldType.TEXT,
      name: "name",
      label: "Name",
      icon: "IconAbc",
      isNullable: true
    },
    {
      universalIdentifier: "d7b99b3f-156a-5f63-923f-f2faf3e91387",
      type: FieldType.TEXT,
      name: "orderRef",
      label: "Order Ref",
      description: "ERP orders.order_number — idempotency key",
      icon: "IconHash",
      isNullable: true
    },
    {
      universalIdentifier: "31e9e81c-0780-5d27-ba45-e0fee72ae8fb",
      type: FieldType.POSITION,
      name: "position",
      label: "Position",
      icon: "IconHierarchy2",
      isNullable: false,
      defaultValue: 0
    },
    {
      universalIdentifier: "cf6bf150-41bf-5253-8cb1-c5117a92ee6d",
      type: FieldType.BOOLEAN,
      name: "protectedFlag",
      label: "Protected",
      description: "stamped from Company.newClientProtected (W-07)",
      icon: "IconShield",
      isNullable: true
    },
    {
      universalIdentifier: "12b1bf98-0567-5e64-bb58-fa98770ce6c6",
      type: FieldType.DATE_TIME,
      name: "qcSignoffAt",
      label: "QC Sign-off At",
      icon: "IconClockCheck",
      isNullable: true
    },
    {
      universalIdentifier: "fcfc3a60-71e7-57c4-a9aa-8e06273c9f7b",
      type: FieldType.TEXT,
      name: "qcSignoffBy",
      label: "QC Sign-off By",
      icon: "IconSignature",
      isNullable: true
    },
    {
      universalIdentifier: "11d6a526-7e7b-54ca-aff9-f59690d1913b",
      type: FieldType.NUMBER,
      name: "rating",
      label: "Rating",
      description: "1-tap WhatsApp rating 1–5",
      icon: "IconStar",
      isNullable: true
    },
    {
      universalIdentifier: "b49ae8c7-3ee6-5a27-84ba-6bfefdf7d22b",
      type: FieldType.TS_VECTOR,
      name: "searchVector",
      label: "Search vector",
      icon: "IconSearch",
      isNullable: true,
      universalSettings: {
        asExpression: "to_tsvector('simple', COALESCE(public.unaccent_immutable(\"name\"), ''))",
        generatedType: "STORED"
      }
    },
    {
      universalIdentifier: "a4a8d0fe-bbd1-5fd1-aae0-b67052799484",
      type: FieldType.DATE_TIME,
      name: "updatedAt",
      label: "Last update",
      icon: "IconCalendarClock",
      isNullable: false,
      defaultValue: "now"
    },
    {
      universalIdentifier: "4809e5d9-d8f7-55e5-b319-66a95331d94d",
      type: FieldType.ACTOR,
      name: "updatedBy",
      label: "Updated by",
      icon: "IconUserCircle",
      isNullable: false,
      defaultValue: {
        name: "''",
        source: "'MANUAL'"
      }
    },
    {
      universalIdentifier: "2911bb99-8b6a-5463-9f2b-e02262e2ed04",
      type: FieldType.CURRENCY,
      name: "value",
      label: "Value",
      icon: "IconCash",
      isNullable: true
    }
  ]
});
