// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, OnDeleteAction, RelationType, defineObject } from 'twenty-sdk/define';

export const PAYMENT_PROMISE_OBJECT_UNIVERSAL_IDENTIFIER = "730c3de2-6bc0-501d-bbde-d81453da11d2";

export default defineObject({
  universalIdentifier: PAYMENT_PROMISE_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: "paymentPromise",
  namePlural: "paymentPromises",
  labelSingular: "Payment Promise",
  labelPlural: "Payment Promises",
  icon: "IconHeartHandshake",
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: "36384360-7260-500d-bedf-cc627fa9a37e",
  fields: [
    {
      universalIdentifier: "24066e74-0a78-5f7a-8e92-24a4ade517b3",
      type: FieldType.CURRENCY,
      name: "amount",
      label: "Amount",
      icon: "IconCash",
      isNullable: true
    },
    {
      universalIdentifier: "59e1682f-fb02-5883-8ed5-f47e2d9f4b0c",
      type: FieldType.SELECT,
      name: "channel",
      label: "Channel",
      icon: "IconPhone",
      isNullable: true,
      options: [
        {
          id: "0a38bdc3-df2a-5d4e-8efb-0ca8648e7579",
          color: "green",
          label: "Visit",
          value: "VISIT",
          position: 0
        },
        {
          id: "9c3f2d6d-0704-50d3-a151-f5ab8c69343e",
          color: "turquoise",
          label: "Call",
          value: "CALL",
          position: 1
        },
        {
          id: "14acaab2-4338-53ac-b442-e1d114b1b1ae",
          color: "sky",
          label: "Whatsapp",
          value: "WHATSAPP",
          position: 2
        }
      ]
    },
    {
      universalIdentifier: "c31868c9-638f-5ebe-8d70-b4eeb7c4df23",
      type: FieldType.RELATION,
      name: "company",
      label: "Company",
      icon: "IconHeartHandshake",
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
      relationTargetFieldMetadataUniversalIdentifier: "ca976ddd-e5f2-5fdc-846e-c3fbc21c7fbc",
      universalSettings: {
        onDelete: OnDeleteAction.SET_NULL,
        relationType: RelationType.MANY_TO_ONE,
        joinColumnName: "companyId"
      }
    },
    {
      universalIdentifier: "bef67d0a-e4fe-51c9-a927-9b0f71bfb4c6",
      type: FieldType.DATE_TIME,
      name: "createdAt",
      label: "Creation date",
      icon: "IconCalendar",
      isNullable: false,
      defaultValue: "now"
    },
    {
      universalIdentifier: "cd7fbb00-4025-5f48-acf7-3ba53b4cd80a",
      type: FieldType.ACTOR,
      name: "createdBy",
      label: "Created by",
      icon: "IconCreativeCommonsSa",
      isNullable: false,
      defaultValue: {
        name: "''",
        source: "'MANUAL'"
      }
    },
    {
      universalIdentifier: "e5baa298-6e59-5be9-a8e5-f9cb37e9a326",
      type: FieldType.DATE_TIME,
      name: "deletedAt",
      label: "Deleted at",
      icon: "IconCalendarClock",
      isNullable: true
    },
    {
      universalIdentifier: "10b0718a-06c7-525f-b848-6bfc55461c67",
      type: FieldType.LINKS,
      name: "evidenceUrl",
      label: "Evidence",
      description: "Signed acknowledgement photo >AED 5k",
      icon: "IconPhoto",
      isNullable: true
    },
    {
      universalIdentifier: "81cfc708-590e-58c9-ac03-10528f6726ba",
      type: FieldType.UUID,
      name: "id",
      label: "Id",
      icon: "Icon123",
      isNullable: false,
      defaultValue: "uuid"
    },
    {
      universalIdentifier: "36384360-7260-500d-bedf-cc627fa9a37e",
      type: FieldType.TEXT,
      name: "name",
      label: "Name",
      icon: "IconAbc",
      isNullable: true
    },
    {
      universalIdentifier: "b6e86230-5fdd-537d-b148-8adcd1418ea5",
      type: FieldType.POSITION,
      name: "position",
      label: "Position",
      icon: "IconHierarchy2",
      isNullable: false,
      defaultValue: 0
    },
    {
      universalIdentifier: "0b3da37a-d448-5774-b5d0-514477f18815",
      type: FieldType.DATE,
      name: "promisedDate",
      label: "Promised Date",
      description: "Required — BR-17.1 no date, no promise",
      icon: "IconCalendarDue",
      isNullable: true
    },
    {
      universalIdentifier: "83670ab1-1bab-5b94-a6bd-0b9c5f8aa3f5",
      type: FieldType.TS_VECTOR,
      name: "searchVector",
      label: "Search vector",
      icon: "IconSearch",
      isNullable: true,
      universalSettings: {
        asExpression: "to_tsvector('simple', COALESCE(public.unaccent_immutable(\"name\"), ''))",
        generatedType: "STORED"
      }
    },
    {
      universalIdentifier: "42c2bbd1-a5f1-5dfd-89f1-c930b7027a95",
      type: FieldType.RELATION,
      name: "sourceVisit",
      label: "Source Visit",
      icon: "IconHeartHandshake",
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: "80155072-b338-5bd5-b7f7-2dde833c8c3e" /* visit */,
      relationTargetFieldMetadataUniversalIdentifier: "4d356c0d-8faa-5a5b-bea4-0c69f5194e96",
      universalSettings: {
        onDelete: OnDeleteAction.SET_NULL,
        relationType: RelationType.MANY_TO_ONE,
        joinColumnName: "sourceVisitId"
      }
    },
    {
      universalIdentifier: "9f4e0247-c5cb-5034-92ae-693aa2dd51b0",
      type: FieldType.SELECT,
      name: "status",
      label: "Status",
      icon: "IconProgress",
      isNullable: true,
      defaultValue: "'OPEN'",
      options: [
        {
          id: "d48bdd29-09b8-5628-bd5d-5b8424807967",
          color: "sky",
          label: "Open",
          value: "OPEN",
          position: 0
        },
        {
          id: "46db2e31-f8ad-58f3-80a3-756e4304eb32",
          color: "green",
          label: "Kept",
          value: "KEPT",
          position: 1
        },
        {
          id: "8e543b84-f3bd-53ff-9c3a-e015358d4368",
          color: "red",
          label: "Broken",
          value: "BROKEN",
          position: 2
        },
        {
          id: "98b63671-d38d-51ea-9df4-88c8e6e7b778",
          color: "orange",
          label: "Refused",
          value: "REFUSED",
          position: 3
        }
      ]
    },
    {
      universalIdentifier: "e629bd80-bc77-50f2-a3c7-7b93c12895ae",
      type: FieldType.DATE_TIME,
      name: "updatedAt",
      label: "Last update",
      icon: "IconCalendarClock",
      isNullable: false,
      defaultValue: "now"
    },
    {
      universalIdentifier: "22534063-da92-5e36-ae15-358e40b39b66",
      type: FieldType.ACTOR,
      name: "updatedBy",
      label: "Updated by",
      icon: "IconUserCircle",
      isNullable: false,
      defaultValue: {
        name: "''",
        source: "'MANUAL'"
      }
    }
  ]
});
