// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, OnDeleteAction, RelationType, defineObject } from 'twenty-sdk/define';

export const STANDING_ORDER_OBJECT_UNIVERSAL_IDENTIFIER = "1d2f5ca4-4d73-5f46-9a86-118e41a67839";

export default defineObject({
  universalIdentifier: STANDING_ORDER_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: "standingOrder",
  namePlural: "standingOrders",
  labelSingular: "Standing Order",
  labelPlural: "Standing Orders",
  icon: "IconRepeat",
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: "b4d63e96-2869-5b55-b7de-add813581c2b",
  fields: [
    {
      universalIdentifier: "7b560719-fdcf-597c-a9d3-6cc822a945ea",
      type: FieldType.TEXT,
      name: "basketSummary",
      label: "Basket Summary",
      icon: "IconBasket",
      isNullable: true
    },
    {
      universalIdentifier: "278d7932-bbea-5236-9c5a-e404877aa6b6",
      type: FieldType.RELATION,
      name: "company",
      label: "Company",
      icon: "IconRepeat",
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
      relationTargetFieldMetadataUniversalIdentifier: "339851e8-f74c-5121-8d66-ef9836b884cc",
      universalSettings: {
        onDelete: OnDeleteAction.SET_NULL,
        relationType: RelationType.MANY_TO_ONE,
        joinColumnName: "companyId"
      }
    },
    {
      universalIdentifier: "b69bc0c6-0943-592b-8dc2-64c37766822f",
      type: FieldType.NUMBER,
      name: "confirmedQuantity",
      label: "Confirmed Quantity",
      description: "aligns to ERP standing_orders",
      icon: "IconStack2",
      isNullable: true
    },
    {
      universalIdentifier: "77449b7f-8e13-5540-8c76-43501821a72f",
      type: FieldType.DATE_TIME,
      name: "createdAt",
      label: "Creation date",
      icon: "IconCalendar",
      isNullable: false,
      defaultValue: "now"
    },
    {
      universalIdentifier: "40cce588-181d-5d2e-8745-aa15fa4bcfc9",
      type: FieldType.ACTOR,
      name: "createdBy",
      label: "Created by",
      icon: "IconCreativeCommonsSa",
      isNullable: false,
      defaultValue: {
        name: "''",
        source: "'MANUAL'"
      }
    },
    {
      universalIdentifier: "9ba88968-ef90-5d76-8262-d12eb101b6c4",
      type: FieldType.DATE_TIME,
      name: "deletedAt",
      label: "Deleted at",
      icon: "IconCalendarClock",
      isNullable: true
    },
    {
      universalIdentifier: "1368fb6f-37a4-5b1d-9c04-6039c8bddd8a",
      type: FieldType.SELECT,
      name: "deliveryDay",
      label: "Delivery Day",
      icon: "IconCalendarWeek",
      isNullable: true,
      options: [
        {
          id: "b27f7fc5-f708-5250-9458-46e371e854ca",
          color: "green",
          label: "Saturday",
          value: "SATURDAY",
          position: 0
        },
        {
          id: "4a497107-9183-597b-814e-abadca13abb5",
          color: "turquoise",
          label: "Sunday",
          value: "SUNDAY",
          position: 1
        },
        {
          id: "7259ab36-eda0-5341-ab30-9321ea7f797a",
          color: "sky",
          label: "Monday",
          value: "MONDAY",
          position: 2
        },
        {
          id: "b13e9063-de22-5c3e-821c-944fa7b51cc1",
          color: "blue",
          label: "Tuesday",
          value: "TUESDAY",
          position: 3
        },
        {
          id: "8596a2f4-c7c6-581d-b342-3a0a0774c02d",
          color: "purple",
          label: "Wednesday",
          value: "WEDNESDAY",
          position: 4
        },
        {
          id: "c82edb15-e815-554e-a8cd-36be4647c4a5",
          color: "pink",
          label: "Thursday",
          value: "THURSDAY",
          position: 5
        },
        {
          id: "8508be1d-9e5d-5d02-88c4-8ec4fc76bb41",
          color: "red",
          label: "Friday",
          value: "FRIDAY",
          position: 6
        }
      ]
    },
    {
      universalIdentifier: "2478ad60-e3b5-52ba-862b-9d139d48ff88",
      type: FieldType.TEXT,
      name: "erpReference",
      label: "ERP Reference",
      description: "ERP standing_orders.id",
      icon: "IconDatabase",
      isNullable: true
    },
    {
      universalIdentifier: "9732c019-ce03-5398-b74f-1c76e3aeacaa",
      type: FieldType.SELECT,
      name: "frequency",
      label: "Frequency",
      icon: "IconRepeat",
      isNullable: true,
      options: [
        {
          id: "39dd5337-8e86-5dd0-bfa8-e4ef605db445",
          color: "green",
          label: "Weekly",
          value: "WEEKLY",
          position: 0
        },
        {
          id: "202f8525-46cd-52a4-8825-203cace3fbb8",
          color: "turquoise",
          label: "Bi Weekly",
          value: "BI_WEEKLY",
          position: 1
        }
      ]
    },
    {
      universalIdentifier: "8019fb45-5833-5f6f-b59f-485f642a6ad1",
      type: FieldType.UUID,
      name: "id",
      label: "Id",
      icon: "Icon123",
      isNullable: false,
      defaultValue: "uuid"
    },
    {
      universalIdentifier: "b4d63e96-2869-5b55-b7de-add813581c2b",
      type: FieldType.TEXT,
      name: "name",
      label: "Name",
      icon: "IconAbc",
      isNullable: true
    },
    {
      universalIdentifier: "5d5bd629-8a82-5497-bfdf-426a45d8f5cb",
      type: FieldType.POSITION,
      name: "position",
      label: "Position",
      icon: "IconHierarchy2",
      isNullable: false,
      defaultValue: 0
    },
    {
      universalIdentifier: "2f145325-8312-5908-bc7d-f2e1e0d9d387",
      type: FieldType.DATE,
      name: "reviewDate",
      label: "Review Date",
      description: "Renewal task at reviewDate − 7 (W-20)",
      icon: "IconCalendarDue",
      isNullable: true
    },
    {
      universalIdentifier: "918e05e1-a79f-5cfc-bac8-d6efd51c8ae8",
      type: FieldType.TS_VECTOR,
      name: "searchVector",
      label: "Search vector",
      icon: "IconSearch",
      isNullable: true,
      universalSettings: {
        asExpression: "to_tsvector('simple', COALESCE(public.unaccent_immutable(\"name\"), ''))",
        generatedType: "STORED"
      }
    },
    {
      universalIdentifier: "dc04d700-60e2-57bb-b423-93b2d06be1ff",
      type: FieldType.DATE,
      name: "startDate",
      label: "Start Date",
      icon: "IconCalendar",
      isNullable: true
    },
    {
      universalIdentifier: "c56476a5-d2ca-5bd5-82cf-4a59739dfef7",
      type: FieldType.SELECT,
      name: "status",
      label: "Status",
      description: "Active requires ERP Reference (UC-15 E1)",
      icon: "IconProgress",
      isNullable: true,
      defaultValue: "'DRAFT'",
      options: [
        {
          id: "bad99877-3871-5aca-9830-d4b63e7c087f",
          color: "green",
          label: "Draft",
          value: "DRAFT",
          position: 0
        },
        {
          id: "419a845f-fdd9-553b-9f19-eed0d2116912",
          color: "green",
          label: "Active",
          value: "ACTIVE",
          position: 1
        },
        {
          id: "dcf08d82-949b-5f6a-a6c6-4ececc5e79a5",
          color: "sky",
          label: "Paused",
          value: "PAUSED",
          position: 2
        },
        {
          id: "0d1d024a-549d-539b-8df4-75639cd7be0c",
          color: "blue",
          label: "Ended",
          value: "ENDED",
          position: 3
        }
      ]
    },
    {
      universalIdentifier: "ffcb3ea0-0523-5afb-a110-6cf2f31ef4ff",
      type: FieldType.DATE_TIME,
      name: "updatedAt",
      label: "Last update",
      icon: "IconCalendarClock",
      isNullable: false,
      defaultValue: "now"
    },
    {
      universalIdentifier: "d8099afb-b9cf-5bd3-b817-26623455406b",
      type: FieldType.ACTOR,
      name: "updatedBy",
      label: "Updated by",
      icon: "IconUserCircle",
      isNullable: false,
      defaultValue: {
        name: "''",
        source: "'MANUAL'"
      }
    }
  ]
});
