// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { FieldType, OnDeleteAction, RelationType, defineObject } from 'twenty-sdk/define';

export const VISIT_OBJECT_UNIVERSAL_IDENTIFIER = "80155072-b338-5bd5-b7f7-2dde833c8c3e";

export default defineObject({
  universalIdentifier: VISIT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: "visit",
  namePlural: "visits",
  labelSingular: "Visit",
  labelPlural: "Visits",
  icon: "IconMapPin",
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: "a046ed79-e891-56da-bc3c-4322d979bb9f",
  fields: [
    {
      universalIdentifier: "7057549a-8e13-5308-989e-2ad62871236f",
      type: FieldType.SELECT,
      name: "chillerState",
      label: "Chiller State",
      icon: "IconFridge",
      isNullable: true,
      options: [
        {
          id: "0d2f5313-766c-5f09-a576-f12d1dfe14d6",
          color: "green",
          label: "Full",
          value: "FULL",
          position: 0
        },
        {
          id: "ee706892-443e-508d-b470-d9f45c7d2fb7",
          color: "turquoise",
          label: "Partial Floranow",
          value: "PARTIAL_FLORANOW",
          position: 1
        },
        {
          id: "e712700b-7c4e-53f9-8798-4005f49ae441",
          color: "sky",
          label: "Competitor Stock",
          value: "COMPETITOR_STOCK",
          position: 2
        },
        {
          id: "92205b3c-0617-5e02-858d-761fb16fac46",
          color: "blue",
          label: "Empty",
          value: "EMPTY",
          position: 3
        }
      ]
    },
    {
      universalIdentifier: "1ad8b4eb-f844-5eaa-a03d-9d58cdc74965",
      type: FieldType.RELATION,
      name: "company",
      label: "Company",
      icon: "IconMapPin",
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: "20202020-b374-4779-a561-80086cb2e17f" /* company */,
      relationTargetFieldMetadataUniversalIdentifier: "aab1a388-8647-5ce7-87bd-4dda841d337d",
      universalSettings: {
        onDelete: OnDeleteAction.SET_NULL,
        relationType: RelationType.MANY_TO_ONE,
        joinColumnName: "companyId"
      }
    },
    {
      universalIdentifier: "a58c4245-ada8-5a06-8a69-f68e6c91c570",
      type: FieldType.DATE_TIME,
      name: "createdAt",
      label: "Creation date",
      icon: "IconCalendar",
      isNullable: false,
      defaultValue: "now"
    },
    {
      universalIdentifier: "38ae72b0-7504-5345-b8af-dec5a1a59949",
      type: FieldType.ACTOR,
      name: "createdBy",
      label: "Created by",
      icon: "IconCreativeCommonsSa",
      isNullable: false,
      defaultValue: {
        name: "''",
        source: "'MANUAL'"
      }
    },
    {
      universalIdentifier: "5d89369f-b682-5a9c-b538-dbc971a0fe86",
      type: FieldType.DATE_TIME,
      name: "deletedAt",
      label: "Deleted at",
      icon: "IconCalendarClock",
      isNullable: true
    },
    {
      universalIdentifier: "9b18c1ac-59c2-558f-bc56-f4b957d466cd",
      type: FieldType.NUMBER,
      name: "echoConfidence",
      label: "ECHO Confidence %",
      description: "<80 routes to SC review",
      icon: "IconPercentage",
      isNullable: true
    },
    {
      universalIdentifier: "7f56457e-4e23-5bff-9c87-fc40244dd4d7",
      type: FieldType.TEXT,
      name: "echoTranscript",
      label: "ECHO Transcript",
      icon: "IconMicrophone",
      isNullable: true
    },
    {
      universalIdentifier: "ea42d3f0-c779-536b-903d-94f6fe2eecd7",
      type: FieldType.UUID,
      name: "id",
      label: "Id",
      icon: "Icon123",
      isNullable: false,
      defaultValue: "uuid"
    },
    {
      universalIdentifier: "a046ed79-e891-56da-bc3c-4322d979bb9f",
      type: FieldType.TEXT,
      name: "name",
      label: "Name",
      icon: "IconAbc",
      isNullable: true
    },
    {
      universalIdentifier: "4613dd6d-5f78-5ac7-9528-51c2e691da02",
      type: FieldType.SELECT,
      name: "orderChannel",
      label: "Order Channel",
      icon: "IconDeviceMobile",
      isNullable: true,
      options: [
        {
          id: "a04111bd-00c8-5fa8-87f0-88e8e3d0b102",
          color: "green",
          label: "Online",
          value: "ONLINE",
          position: 0
        },
        {
          id: "0190f48c-39ab-5b8e-b55e-7887abc95504",
          color: "orange",
          label: "Offline",
          value: "OFFLINE",
          position: 1
        },
        {
          id: "23aeefbf-677c-54db-b5c1-f12311cb9ab9",
          color: "sky",
          label: "None",
          value: "NONE",
          position: 2
        }
      ]
    },
    {
      universalIdentifier: "f79174d4-1d0d-59c1-b18d-71b56887f208",
      type: FieldType.CURRENCY,
      name: "orderValue",
      label: "Order Value",
      icon: "IconShoppingCart",
      isNullable: true
    },
    {
      universalIdentifier: "585af935-d352-5f01-a3ae-b2ae701af210",
      type: FieldType.TEXT,
      name: "outcome",
      label: "Outcome",
      icon: "IconMessage",
      isNullable: true
    },
    {
      universalIdentifier: "23c8a3a7-0501-5864-8268-a110cc0f5c60",
      type: FieldType.CURRENCY,
      name: "paymentCollected",
      label: "Payment Collected",
      icon: "IconCash",
      isNullable: true
    },
    {
      universalIdentifier: "4d356c0d-8faa-5a5b-bea4-0c69f5194e96",
      type: FieldType.RELATION,
      name: "paymentPromises",
      label: "Payment Promises",
      icon: "IconHeartHandshake",
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: "730c3de2-6bc0-501d-bbde-d81453da11d2" /* paymentPromise */,
      relationTargetFieldMetadataUniversalIdentifier: "42c2bbd1-a5f1-5dfd-89f1-c930b7027a95",
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY
      }
    },
    {
      universalIdentifier: "a42db3f7-d14f-5372-b242-5d4b0263a02b",
      type: FieldType.TEXT,
      name: "plannedWeek",
      label: "Planned Week",
      description: "e.g. 2026-W27 — planned-vs-actual BR-24.1",
      icon: "IconCalendarWeek",
      isNullable: true
    },
    {
      universalIdentifier: "65b5c138-5da4-54b8-8573-edd54c5ba90f",
      type: FieldType.POSITION,
      name: "position",
      label: "Position",
      icon: "IconHierarchy2",
      isNullable: false,
      defaultValue: 0
    },
    {
      universalIdentifier: "2aa43a91-a4f5-5314-9af4-22967857607b",
      type: FieldType.CURRENCY,
      name: "promiseStatedAmount",
      label: "Promise Stated Amount",
      icon: "IconCashBanknote",
      isNullable: true
    },
    {
      universalIdentifier: "084705d3-99fa-5f46-bc0f-9b53032f39f4",
      type: FieldType.DATE,
      name: "promiseStatedDate",
      label: "Promise Stated Date",
      icon: "IconCalendarDue",
      isNullable: true
    },
    {
      universalIdentifier: "3f7ae80f-03da-54aa-a810-8a2dd468ce8c",
      type: FieldType.BOOLEAN,
      name: "pushListAttach",
      label: "Push-List Attach",
      description: "FR-25 margin push attach",
      icon: "IconFlame",
      isNullable: true
    },
    {
      universalIdentifier: "64b92504-b793-56d0-b82d-fe7329257bca",
      type: FieldType.TS_VECTOR,
      name: "searchVector",
      label: "Search vector",
      icon: "IconSearch",
      isNullable: true,
      universalSettings: {
        asExpression: "to_tsvector('simple', COALESCE(public.unaccent_immutable(\"name\"), ''))",
        generatedType: "STORED"
      }
    },
    {
      universalIdentifier: "48c96d55-a25c-52e2-9e7d-f73b8cd4b63d",
      type: FieldType.SELECT,
      name: "status",
      label: "Status",
      icon: "IconProgress",
      isNullable: true,
      defaultValue: "'PLANNED'",
      options: [
        {
          id: "fd621c03-2956-5638-bfc7-0f57418be11a",
          color: "sky",
          label: "Planned",
          value: "PLANNED",
          position: 0
        },
        {
          id: "170cb605-e8b7-59aa-8352-8c9ab049f717",
          color: "green",
          label: "Completed",
          value: "COMPLETED",
          position: 1
        },
        {
          id: "4cd56ac0-2e4f-5d7f-9f0d-0b2ca60e6af6",
          color: "red",
          label: "Missed",
          value: "MISSED",
          position: 2
        }
      ]
    },
    {
      universalIdentifier: "3e5383a4-a720-5742-ad5a-da802a3323ac",
      type: FieldType.SELECT,
      name: "subTagStated",
      label: "Sub-Tag Stated",
      icon: "IconTag",
      isNullable: true,
      options: [
        {
          id: "17932bfc-0600-5b77-a694-367cde8612ae",
          color: "green",
          label: "Market Slow",
          value: "MARKET_SLOW",
          position: 0
        },
        {
          id: "29203f65-bc9b-5ac0-978e-12b40bf25276",
          color: "turquoise",
          label: "Waiting To Restart",
          value: "WAITING_TO_RESTART",
          position: 1
        },
        {
          id: "d50bfd36-3475-58f0-9e9d-2bdb2e03db61",
          color: "sky",
          label: "Switched Supplier",
          value: "SWITCHED_SUPPLIER",
          position: 2
        },
        {
          id: "49476ef2-3561-5929-ac14-e7a0208d4452",
          color: "blue",
          label: "Wrong Account",
          value: "WRONG_ACCOUNT",
          position: 3
        },
        {
          id: "4099050f-6d4f-54e5-b6e3-f5d26f0711c7",
          color: "purple",
          label: "Seasonal Sleeper",
          value: "SEASONAL_SLEEPER",
          position: 4
        },
        {
          id: "e27c47d6-e8e0-5192-b7b0-3f9a8c21cf8f",
          color: "pink",
          label: "Closed Business",
          value: "CLOSED_BUSINESS",
          position: 5
        }
      ]
    },
    {
      universalIdentifier: "c409f8e3-af15-5031-836e-18257a83b6b6",
      type: FieldType.DATE_TIME,
      name: "updatedAt",
      label: "Last update",
      icon: "IconCalendarClock",
      isNullable: false,
      defaultValue: "now"
    },
    {
      universalIdentifier: "772de184-e28c-5b95-ba38-3f13afa139e6",
      type: FieldType.ACTOR,
      name: "updatedBy",
      label: "Updated by",
      icon: "IconUserCircle",
      isNullable: false,
      defaultValue: {
        name: "''",
        source: "'MANUAL'"
      }
    },
    {
      universalIdentifier: "c389b240-c536-5e82-94be-5fd71596f320",
      type: FieldType.DATE_TIME,
      name: "visitDate",
      label: "Visit Date",
      icon: "IconCalendar",
      isNullable: true
    },
    {
      universalIdentifier: "2084f58e-b6fc-55f7-8c0f-a1b3afe36022",
      type: FieldType.SELECT,
      name: "visitType",
      label: "Visit Type",
      icon: "IconCategory",
      isNullable: true,
      options: [
        {
          id: "c0dd94c9-9a6e-59c0-b53a-67c1c873fc1e",
          color: "green",
          label: "First Visit",
          value: "FIRST_VISIT",
          position: 0
        },
        {
          id: "338468a4-031f-53f6-9fd6-fad4e153e3ce",
          color: "turquoise",
          label: "Revenue",
          value: "REVENUE",
          position: 1
        },
        {
          id: "32307703-e9f4-5f8b-91e7-637ccc17b308",
          color: "sky",
          label: "Payment",
          value: "PAYMENT",
          position: 2
        },
        {
          id: "68818603-4598-5b29-8d8c-96abbdc25859",
          color: "blue",
          label: "Reactivation",
          value: "REACTIVATION",
          position: 3
        },
        {
          id: "9361e83e-a567-5ea8-8f97-aaca6d4bc9ed",
          color: "purple",
          label: "Win Back",
          value: "WIN_BACK",
          position: 4
        },
        {
          id: "dd742f02-a88d-514d-bc7f-a8cd2faca5a5",
          color: "pink",
          label: "Acquisition",
          value: "ACQUISITION",
          position: 5
        }
      ]
    }
  ]
});
