// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { NavigationMenuItemType, defineNavigationMenuItem } from 'twenty-sdk/define';

export default defineNavigationMenuItem({
  universalIdentifier: "0d879883-67f0-59d8-9d91-bf6c81a69062",
  type: NavigationMenuItemType.OBJECT,
  color: "red",
  position: 10,
  targetObjectUniversalIdentifier: "d9fc138e-e50c-5835-85c1-51793672be07"
});
