// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { NavigationMenuItemType, defineNavigationMenuItem } from 'twenty-sdk/define';

export default defineNavigationMenuItem({
  universalIdentifier: "9d952945-f07e-5bdb-b3ee-f7f8966348ab",
  type: NavigationMenuItemType.OBJECT,
  color: "orange",
  position: 13,
  targetObjectUniversalIdentifier: "ab30bd09-9b3b-51be-b096-8554f631b30a"
});
