// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { NavigationMenuItemType, defineNavigationMenuItem } from 'twenty-sdk/define';

export default defineNavigationMenuItem({
  universalIdentifier: "28cca203-6bb1-52cb-9817-ad8fc07faa07",
  type: NavigationMenuItemType.OBJECT,
  color: "purple",
  position: 12,
  targetObjectUniversalIdentifier: "aa860ef9-896f-5677-84f2-e69fefd3b630"
});
