// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { NavigationMenuItemType, defineNavigationMenuItem } from 'twenty-sdk/define';

export default defineNavigationMenuItem({
  universalIdentifier: "730864ed-6638-5e27-bedc-2e600d37d7fe",
  type: NavigationMenuItemType.OBJECT,
  color: "blue",
  position: 9,
  targetObjectUniversalIdentifier: "730c3de2-6bc0-501d-bbde-d81453da11d2"
});
