// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { NavigationMenuItemType, defineNavigationMenuItem } from 'twenty-sdk/define';

export default defineNavigationMenuItem({
  universalIdentifier: "601711c6-03fb-54dd-86bb-833605f8c6fd",
  type: NavigationMenuItemType.OBJECT,
  color: "turquoise",
  position: 11,
  targetObjectUniversalIdentifier: "1d2f5ca4-4d73-5f46-9a86-118e41a67839"
});
