// AUTO-GENERATED by `yarn model:pull` from the dev workspace.
// Do not edit by hand — your changes will be overwritten on the next pull.

import { NavigationMenuItemType, defineNavigationMenuItem } from 'twenty-sdk/define';

export default defineNavigationMenuItem({
  universalIdentifier: "1ee5684f-ebff-584c-b38c-2387351ffa26",
  type: NavigationMenuItemType.OBJECT,
  color: "green",
  position: 8,
  targetObjectUniversalIdentifier: "80155072-b338-5bd5-b7f7-2dde833c8c3e"
});
